# -*- coding: utf-8 -*-
# Power Platformのビジネス価値 (22問) — 本番難度版（紛らわしい実在の選択肢中心）
A = "Power Platformのビジネス価値"
PA = [
# ---- サービスのビジネス価値 (16) ----
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"現場の担当者が、在庫を確認・登録するモバイル業務アプリをコーディングなしで内製したい。最も適したサービスはどれですか？",
 "options":["Power Apps","Power Automate","Power Pages","Copilot Studio"],"correct":["Power Apps"],
 "explanation":"アプリ（UIを持つ業務アプリ）の構築はPower Appsです。Power Automateは自動化、Power Pagesは外部向けWebサイト、Copilot Studioは会話型ボット作成が主目的です。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"経費精算の申請が出るたびに、承認依頼の送信と台帳への記録を自動で行いたい。最も適したサービスはどれですか？",
 "options":["Power Automate","Power Apps","Power Pages","Microsoft Dataverse"],"correct":["Power Automate"],
 "explanation":"承認や通知、記録などの繰り返し処理の自動化はPower Automateです。Dataverseはデータ基盤、Power Appsはアプリ、Power PagesはWebサイトです。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"取引先が自分でログインして注文状況を確認できる、外部公開のWebポータルを作りたい。最も適したサービスはどれですか？",
 "options":["Power Pages","Power Apps（キャンバスアプリ）","Power Automate","Dataverse for Teams"],"correct":["Power Pages"],
 "explanation":"外部ユーザー向けの公開Webサイト／ポータルはPower Pagesです。Power Appsは主に組織内ユーザー向けの業務アプリに使われます。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"問い合わせ対応を自動化する会話型のAIエージェントを、ローコードで作成・公開したい。最も適したサービスはどれですか？",
 "options":["Microsoft Copilot Studio","Power Automate デスクトップ","Power Pages","AI Builder"],"correct":["Microsoft Copilot Studio"],
 "explanation":"会話型ボット（コパイロット）の作成はCopilot Studioです。AI Builderはフォーム読み取りや予測などのAIモデルを既存サービスに組み込む機能で、ボット作成そのものではありません。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"Power Platformの各サービスが共通して接続できる、業務データの中心的な格納先として設計されているのはどれですか？",
 "options":["Microsoft Dataverse","Power Fx","Power BI","SharePoint リスト"],"correct":["Microsoft Dataverse"],
 "explanation":"Dataverseはセキュリティ・リレーションシップ・ロジックを備えた標準データ基盤で、Power Platformの中心的データストアです。SharePointリストも接続先になり得ますが、プラットフォーム標準の中核基盤はDataverseです。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"コネクタを利用する主なビジネス価値として最も適切なものはどれですか？",
 "options":["既存のサービスやデータをコードを書かずに統合できる","アプリのUIを自由にデザインできる","データを正規化して保存できる","会話型ボットを学習させられる"],"correct":["既存のサービスやデータをコードを書かずに統合できる"],
 "explanation":"コネクタはOutlookやSharePoint、SQL、サードパーティなど多様なサービス／データへの接続を容易にし、サイロ化した情報をつなぎます。UI設計やデータ正規化はコネクタの役割ではありません。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"生成AI（Copilot）をPower Platformで使う主なビジネス価値として最も適切なものはどれですか？",
 "options":["自然言語の指示でアプリ・フロー・テーブル作成を支援し開発を加速する","コネクタで外部サービスとデータを接続する","Dataverseのテーブルにリレーションシップを定義する","Power BIでレポートのビジュアルを配置する"],"correct":["自然言語の指示でアプリ・フロー・テーブル作成を支援し開発を加速する"],
 "explanation":"Power PlatformのCopilotは、自然言語からアプリ・フロー・テーブルなどの生成・編集を支援し開発を加速します。コネクタ接続・リレーションシップ定義・レポート作成はそれぞれ別機能の役割で、生成AIそのものの価値ではありません。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"Excelの数式に近い構文で、ローコード開発の学習コストを下げるPower Platformの言語はどれですか？",
 "options":["Power Fx","DAX","Power Query (M)","KQL"],"correct":["Power Fx"],
 "explanation":"Power FxはExcel数式に似た宣言的言語でPower Apps等で使います。DAXはPower BIのメジャー、MはPower Queryの変換、KQLはログ分析の言語で、いずれも用途が異なります。"},
{"area":A,"sub":"サービスのビジネス価値","type":"multi",
 "q":"Power Platformでアプリやデータと連携する『コパイロット（会話型AI）』を作成・拡張できるものを2つ選んでください。",
 "options":["Microsoft Copilot Studio","Power Appsに追加するCopilotコントロール","Power Fxの数式","Power Automateのクラウドフロー"],"correct":["Microsoft Copilot Studio","Power Appsに追加するCopilotコントロール"],
 "explanation":"Copilot Studioは独立した会話型ボットを作成し、Power AppsのCopilotコントロールはアプリ内で会話的にデータを操作できます。Power Fxの数式やPower Automateのクラウドフローはロジック・自動化の機能で、コパイロット（会話型AI）の作成・拡張そのものではありません。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"Power Appsの価値を最もよく表すのはどれですか？（Power Automateとの違いに注意）",
 "options":["UIを持つ業務アプリを構築し、人がデータを操作できるようにする","トリガーとアクションで処理を自動実行する","外部公開のWebサイトをSEO込みで作る","ストリーミングデータを集計する"],"correct":["UIを持つ業務アプリを構築し、人がデータを操作できるようにする"],
 "explanation":"Power Appsは人が操作するUIを持つアプリを作ります。トリガー/アクションでの自動化はPower Automate、外部WebサイトはPower Pagesの役割です。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"Power Automateの価値として、Power Appsと最も異なる点はどれですか？",
 "options":["人手を介さずバックグラウンドで処理を自動実行できる","ピクセル単位でUIを設計できる","外部ユーザーにWebページを公開できる","レポートのビジュアルを作成できる"],"correct":["人手を介さずバックグラウンドで処理を自動実行できる"],
 "explanation":"Power Automateはトリガーに応じて自動でフローを実行します。UI設計はPower Apps、外部公開はPower Pages、可視化はPower BIの領域です。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"請求書PDFから項目を自動抽出して入力の手間を省きたい。Power Platformで活用すべき機能はどれですか？",
 "options":["AI Builder（ドキュメント処理）","Power Fx","Power Automateのスケジュールトリガー","Dataverseのビジネスルール"],"correct":["AI Builder（ドキュメント処理）"],
 "explanation":"AI Builderは、フォーム/請求書からの情報抽出や予測などのAI機能をローコードで組み込めます。Power Fxは数式、スケジュールトリガーは時刻起動、ビジネスルールは入力ロジックで、いずれも文書からの自動抽出は行いません。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"Dataverseを採用する価値として、SharePointリストや個別ファイルでの管理と比べた利点はどれですか？",
 "options":["役割ベースのセキュリティとリレーションシップを備えた標準データ基盤に集約できる","ピクセル単位のUIを自動生成できる","フローのトリガーが無料で増える","Webサイトのテーマを変更できる"],"correct":["役割ベースのセキュリティとリレーションシップを備えた標準データ基盤に集約できる"],
 "explanation":"Dataverseはセキュリティロール、リレーションシップ、ビジネスロジックを標準で備え、複数サービスから一貫して安全に利用できる点が価値です。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"Power Pagesが提供する価値として最も適切なものはどれですか？",
 "options":["認証された外部ユーザーも含むWebサイトをローコードで公開できる","社内のPC操作をRPAで自動化できる","Dataverseの物理ストレージを管理できる","レポートのDAXメジャーを作成できる"],"correct":["認証された外部ユーザーも含むWebサイトをローコードで公開できる"],
 "explanation":"Power Pagesは外部公開のWebサイト/ポータルをローコードで構築・公開します。RPAはPower Automateデスクトップ、可視化はPower BIの領域です。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"Power Fxを『ローコードソリューション』として位置づける理由として最も適切なものはどれですか？",
 "options":["宣言的でExcelに近く、コーディング未経験者でもロジックを表現しやすい","コンパイル済みバイナリを生成する低水準言語だから","SQLサーバー専用の問い合わせ言語だから","Webページのスタイルシートだから"],"correct":["宣言的でExcelに近く、コーディング未経験者でもロジックを表現しやすい"],
 "explanation":"Power FxはExcel数式に似た宣言的言語で、ローコード開発の敷居を下げます。低水準言語でもSQLでもCSSでもありません。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"会話型ボットと『アプリ内Copilot』の違いとして正しいものはどれですか？",
 "options":["Copilot Studioは独立したボットを作り、Copilotコントロールはアプリ内でデータ操作を助ける","両者は同一機能である","Copilot StudioはWebサイト専用である","Copilotコントロールはフロー専用である"],"correct":["Copilot Studioは独立したボットを作り、Copilotコントロールはアプリ内でデータ操作を助ける"],
 "explanation":"Copilot Studioは公開可能な会話型ボットを作成、Power AppsのCopilotコントロールはアプリ利用者の自然言語でのデータ操作を支援します。役割が異なります。"},

# ---- ソリューション拡張のビジネス価値 (6) ----
{"area":A,"sub":"ソリューション拡張のビジネス価値","type":"single",
 "q":"Power AppsアプリやPower AutomateフローをMicrosoft Teamsに統合する主な価値はどれですか？",
 "options":["ユーザーが日常使うTeams内で業務アプリや自動化・ボットを直接利用できる","Teamsのライセンスが不要になる","アプリが自動的に一般公開される","Dataverseが不要になる"],"correct":["ユーザーが日常使うTeams内で業務アプリや自動化・ボットを直接利用できる"],
 "explanation":"Power PlatformはTeamsと統合でき、利用者は普段のTeams内でアプリ・フロー・ボットを使えるため定着しやすくなります。"},
{"area":A,"sub":"ソリューション拡張のビジネス価値","type":"multi",
 "q":"Power PlatformとMicrosoft 365を組み合わせた典型的な連携例を2つ選んでください。",
 "options":["Microsoft Formsの回答をPower AutomateでSharePointリストに保存する","Power AppsからOutlookの予定表に予約を登録する","Power BIのレポートからAzure仮想マシンを起動する","Power PagesでオンプレミスのActive Directoryを新規構築する"],"correct":["Microsoft Formsの回答をPower AutomateでSharePointリストに保存する","Power AppsからOutlookの予定表に予約を登録する"],
 "explanation":"Forms→Automate→SharePointや、Power Apps→Outlook連携はMicrosoft 365統合の典型例です。Power BIからの仮想マシン起動やActive Directoryの構築はインフラ運用の領域で、Power PlatformとM365の連携例ではありません。"},
{"area":A,"sub":"ソリューション拡張のビジネス価値","type":"single",
 "q":"『市民開発者（現場の業務担当者）』がローコードで開発に参加できることの組織的価値はどれですか？",
 "options":["IT部門の負荷を抑えつつ現場主導で迅速に業務改善できる","必ず外部ベンダーへ委託する必要が生じる","アプリの共有が一切できなくなる","ガバナンスを完全に放棄できる"],"correct":["IT部門の負荷を抑えつつ現場主導で迅速に業務改善できる"],
 "explanation":"ローコードにより市民開発者が内製でき、IT部門は統制（ガバナンス）に集中しつつ現場主導で素早く改善できます。ガバナンスは放棄せず管理者が枠組みを用意します。"},
{"area":A,"sub":"ソリューション拡張のビジネス価値","type":"single",
 "q":"各サービスを組み合わせたエンドツーエンドのソリューション例として最も適切なものはどれですか？",
 "options":["Power Pagesで受付→Power Automateで承認→Power Appsで管理→Dataverseに保存","Power BIで受付→Copilot Studioで承認→Power Pointで保存","Power Automateで受付→Power BIで管理→Power Pagesで承認","Dataverseで受付→Power Fxで承認→AI Builderで保存"],"correct":["Power Pagesで受付→Power Automateで承認→Power Appsで管理→Dataverseに保存"],
 "explanation":"外部受付（Power Pages）→自動承認（Power Automate）→社内管理（Power Apps）→データ基盤（Dataverse）が、各サービスを役割どおり組み合わせた一連の流れです。"},
{"area":A,"sub":"ソリューション拡張のビジネス価値","type":"single",
 "q":"Power Platformのサービスが『連携して動作する』ことを最もよく示す説明はどれですか？",
 "options":["アプリのボタンからフローを起動し、結果をDataverseに保存して通知できる","各サービスは独立し相互にデータを渡せない","Power AppsはPower Automateを呼び出せない","Dataverseは1つのアプリからしか使えない"],"correct":["アプリのボタンからフローを起動し、結果をDataverseに保存して通知できる"],
 "explanation":"Power Platformの各サービスは相互連携します。アプリからフロー起動、共有のDataverse参照、通知などを組み合わせられます。"},
{"area":A,"sub":"ソリューション拡張のビジネス価値","type":"single",
 "q":"Power AppsとDataverseの関係として正しいものはどれですか？",
 "options":["Power AppsはDataverseを含む多様なデータソースに接続して表示・更新できる","Power AppsはDataverse専用で他に接続できない","DataverseはPower Appsからは読み取れない","両者は連携できない"],"correct":["Power AppsはDataverseを含む多様なデータソースに接続して表示・更新できる"],
 "explanation":"Power Appsはコネクタを通じてDataverseやSharePoint、SQLなど多様なソースに接続できます。モデル駆動型は特にDataverseを基盤とします。"},
# ---- 追加：本番難度（複数選択・最新トピック） ----
{"area":A,"sub":"サービスのビジネス価値","type":"multi",
 "q":"Power Platformの生成AI（Copilot）が開発者にもたらすビジネス価値として正しいものを2つ選んでください。",
 "options":["自然言語の指示からアプリ・フロー・テーブルの作成を支援する","モデル駆動アプリのフォーム上で会話的にデータを要約・操作できる","Power BIのデータセットを自動で最適化する","Dataverseの物理ストレージ容量を自動で拡張する","プレミアムコネクタを標準コネクタに自動変換する"],"correct":["自然言語の指示からアプリ・フロー・テーブルの作成を支援する","モデル駆動アプリのフォーム上で会話的にデータを要約・操作できる"],
 "explanation":"Power PlatformのCopilotは、自然言語からのアプリ/フロー/テーブル生成支援と、アプリ内での会話的なデータ操作を提供します。残りは実在しないか、Copilotの役割ではありません（ストレージ拡張・データセット最適化・コネクタ変換は自動では行われません）。"},
{"area":A,"sub":"サービスのビジネス価値","type":"multi",
 "q":"Power Platformで『会話型のAIエージェント（コパイロット）』を作成・拡張できるものを2つ選んでください。",
 "options":["Microsoft Copilot Studio","Power Appsに追加するCopilotコントロール","プロセス マイニング","AI Builderのフォーム処理","オンプレミスデータゲートウェイ"],"correct":["Microsoft Copilot Studio","Power Appsに追加するCopilotコントロール"],
 "explanation":"独立したボットはCopilot Studio、アプリ内の会話操作はCopilotコントロールで実現します。プロセスマイニングは業務分析、AI Builderは文書からの情報抽出、ゲートウェイはオンプレ接続で、いずれもボット作成ではありません。"},
{"area":A,"sub":"サービスのビジネス価値","type":"single",
 "q":"業務プロセスの実行ログを分析してボトルネックを可視化し、自動化すべき箇所を特定するPower Automateの機能はどれですか？",
 "options":["プロセス マイニング","AI Builder（フォーム処理）","Power Fx","Dataverseの監査ログ"],"correct":["プロセス マイニング"],
 "explanation":"プロセスマイニングはイベントログから業務プロセスを分析し改善・自動化の機会を示します。AI Builderは情報抽出、Power Fxは数式言語、監査ログは変更履歴の記録で、目的が異なります。"},
{"area":A,"sub":"ソリューション拡張のビジネス価値","type":"single",
 "q":"Power Platform を Microsoft Teams 内で利用する価値として最も適切なものはどれですか？",
 "options":["Teams内でアプリやボットを構築・配布し、日常の共同作業に組み込める","Teamsの通話品質を自動で改善する","Teamsの会議を自動で文字起こしする","Teamsの管理者ロールを自動で付与する"],"correct":["Teams内でアプリやボットを構築・配布し、日常の共同作業に組み込める"],
 "explanation":"Power Platformは（Dataverse for Teams等で）Teams内にアプリ・フロー・ボットを構築して配布でき、共同作業に組み込めます。他はTeams自体の機能であり、連携の価値ではありません。"},
]
