# -*- coding: utf-8 -*-
# Power Pagesの機能 (20問) — 本番難度版
E = "Power Pagesの機能"
PE = [
# ---- Power Pagesの機能 (10) ----
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"外部の顧客がログインして申請状況を確認できるWebポータルを作りたい。最適なサービスはどれですか？",
 "options":["Power Pages","Power Apps（モデル駆動型）","Power Automate","Copilot Studio"],"correct":["Power Pages"],
 "explanation":"外部公開のWebサイト/ポータルはPower Pagesです。モデル駆動型は社内業務向け、Power Automateは自動化、Copilot Studioはボット作成です。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"Power Pagesサイトのフォームやリストが表示・収集するデータの主な格納先はどれですか？",
 "options":["Microsoft Dataverse","端末のローカルストレージ","Power BIデータセット","Power Fxの変数"],"correct":["Microsoft Dataverse"],
 "explanation":"Power PagesはDataverseと統合され、フォーム/リストでDataverseのデータを表示・収集します。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"Power Pagesのユースケースとして最も適切なものはどれですか？",
 "options":["顧客向けのセルフサービスポータルやコミュニティサイト","社内PCの画面操作の自動化","レポートのDAXメジャー作成","Dataverseの物理ストレージ管理"],"correct":["顧客向けのセルフサービスポータルやコミュニティサイト"],
 "explanation":"Power Pagesは外部向けセルフサービスポータルやFAQ、コミュニティなどに適します。RPAや可視化、ストレージ管理は別サービスの領域です。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"Power Pagesサイトを新規に作成する方法として正しいものはどれですか？",
 "options":["テンプレート/空のサイト/Copilotから作成しデザインスタジオで編集する","Power Apps Studioでキャンバスを配置する","Power Automateのフローを録画する","Power BIでデータモデルを作る"],"correct":["テンプレート/空のサイト/Copilotから作成しデザインスタジオで編集する"],
 "explanation":"Power Pagesはテンプレート・空のサイト・Copilotから作成し、デザインスタジオで仕上げます。他はそれぞれ別サービスの作業です。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"サイトの一部を『サインインした登録ユーザーだけに見せる』ために使う仕組みはどれですか？",
 "options":["Webロール（とテーブル/ページのアクセス許可）","DLPポリシー","セキュリティロール（Dataverse）","ビジネスルール"],"correct":["Webロール（とテーブル/ページのアクセス許可）"],
 "explanation":"Power PagesではWebロールにテーブル/ページのアクセス許可を割り当て、匿名/認証ユーザーで見える範囲を制御します。Dataverseのセキュリティロールとは別の仕組みです。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"Power Pagesで外部ユーザーがサインインできるようにする認証について正しいものはどれですか？",
 "options":["Microsoft/Google等の各種IDプロバイダーやローカルサインインを構成できる","認証は一切構成できない","社内ADのみ必須である","常に匿名アクセスのみになる"],"correct":["Microsoft/Google等の各種IDプロバイダーやローカルサインインを構成できる"],
 "explanation":"Power Pagesは外部IDプロバイダーやローカルサインインなど複数の認証を構成でき、保護されたコンテンツを提供できます。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"Power Pagesが『ローコード』であることの利点として最も適切なものはどれですか？",
 "options":["Web開発の専門知識が浅くてもサイトを素早く構築・公開できる","必ずHTML/CSSを全て手書きする必要がある","データに接続できない","社内ユーザーにしか公開できない"],"correct":["Web開発の専門知識が浅くてもサイトを素早く構築・公開できる"],
 "explanation":"Power Pagesはローコードでページ・フォーム・リストを構成して素早く公開できます。必要に応じてコードでの拡張も可能です。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"Power Pagesで外部ユーザーからの申請入力を受け取り、Dataverseに保存するために配置するものはどれですか？",
 "options":["フォーム","ビジネスプロセスフロー","ギャラリー","デスクトップフロー"],"correct":["フォーム"],
 "explanation":"Power PagesのフォームはDataverseテーブルと連動し、外部ユーザーの入力を保存します。ギャラリーはキャンバス、ビジネスプロセスフローはモデル駆動型の要素です。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"Power Pagesでデータの一覧を外部サイトに表示するために使うコンポーネントはどれですか？",
 "options":["リスト（List）","ギャラリー","ダッシュボード","ビュー（モデル駆動型）"],"correct":["リスト（List）"],
 "explanation":"Power Pagesのリストコンポーネントは、Dataverseテーブルのレコードをサイト上に一覧表示します。ギャラリーやダッシュボードは他サービスの要素です。"},
{"area":E,"sub":"Power Pagesの機能","type":"single",
 "q":"Power Pagesと社内向けPower Appsの主な違いはどれですか？",
 "options":["Power Pagesは外部公開のWebサイト、Power Appsは主に社内業務アプリ向け","両者は完全に同じ","Power PagesはRPA専用である","Power Appsは外部公開専用である"],"correct":["Power Pagesは外部公開のWebサイト、Power Appsは主に社内業務アプリ向け"],
 "explanation":"Power Pagesは認証外部ユーザーも含むWebサイト向け、Power Appsは主に組織内ユーザー向けの業務アプリという用途の違いがあります。"},

# ---- Power Pagesサイトの作成 (10) ----
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"Power Pagesでサイトやページを自然言語の指示から生成できる機能はどれですか？",
 "options":["Copilot","Power Query","AI Builder のフォーム処理","Power Fx のみ"],"correct":["Copilot"],
 "explanation":"Power PagesのCopilotは自然言語からサイトやページ、フォームを生成します。Power QueryやAI Builderは別目的の機能です。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"Power Pagesでページ編集・コンポーネント配置・スタイル設定を行う作業環境はどれですか？",
 "options":["デザインスタジオ","Power Apps Studio","Power Automate ポータル","Power BI Desktop"],"correct":["デザインスタジオ"],
 "explanation":"Power Pagesのデザインスタジオはページ・スタイル・データ・セットアップのワークスペースを備え、サイトを視覚的に編集します。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"multi",
 "q":"Power Pages デザインスタジオのワークスペースとして適切なものを2つ選んでください。",
 "options":["ページ","スタイル","フローの実行履歴","DAXメジャー"],"correct":["ページ","スタイル"],
 "explanation":"デザインスタジオには『ページ』『スタイル』『データ』『セットアップ』などがあります。フローの実行履歴はPower Automate、DAXメジャーはPower BIの要素です。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"サイト全体の配色やフォントなどの見た目を一括変更したい。使うのはどれですか？",
 "options":["テーマ（スタイル設定）","Webロール","クラウドフロー","ビジネスルール"],"correct":["テーマ（スタイル設定）"],
 "explanation":"テーマ（スタイルワークスペース）で配色・フォント・ボタン等を一括設定し、サイトの外観を統一します。Webロールは権限、他は別機能です。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"Power Pagesでページに文章・画像・ボタン・フォームを追加するには何を配置しますか？",
 "options":["セクション内のコンポーネント","セキュリティロール","クラウドフロー","環境変数"],"correct":["セクション内のコンポーネント"],
 "explanation":"ページにセクションを置き、その中にテキスト・画像・ボタン・フォーム・リスト等のコンポーネントを配置します。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"作成したサイトをインターネット上で利用可能にする操作はどれですか？",
 "options":["サイトを発行（公開）する","環境を削除する","フローを停止する","テーブルをエクスポートする"],"correct":["サイトを発行（公開）する"],
 "explanation":"編集したサイトは『発行（公開）』することで対象ユーザーがアクセスできるようになります。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"Power Pagesのフォームから送信されたデータはどこに保存されますか？",
 "options":["連動するDataverseテーブル","端末のクッキー","Power BIデータセット","フローの変数"],"correct":["連動するDataverseテーブル"],
 "explanation":"Power Pagesのフォームは特定のDataverseテーブルに紐づき、送信内容はそのテーブルのレコードとして保存されます。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"特定のページを『サインイン済みユーザーだけに表示』したい。設定するのはどれですか？",
 "options":["ページのアクセス許可（Webロールに基づく）","テーマの色","フローのトリガー","DAXメジャー"],"correct":["ページのアクセス許可（Webロールに基づく）"],
 "explanation":"ページのアクセス許可をWebロールに基づき設定すると、匿名ユーザーには非表示、認証ユーザーだけに表示などの制御ができます。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"編集中のサイトを公開前に表示・動作確認するために役立つ機能はどれですか？",
 "options":["プレビュー","発行のロールバック","DLPポリシー","環境変数"],"correct":["プレビュー"],
 "explanation":"デザインスタジオではプレビューで編集中のサイトを確認し、問題がなければ発行（公開）します。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"single",
 "q":"Power Pagesサイト作成を始める一般的な方法として正しいものはどれですか？",
 "options":["テンプレートを選ぶ、空のサイトから始める、Copilotで生成する","必ず一からサーバーを構築する","Excelで雛形を作る","Power BIでレポートを作る"],"correct":["テンプレートを選ぶ、空のサイトから始める、Copilotで生成する"],
 "explanation":"Power Pagesはテンプレート・空のサイト・Copilot生成のいずれかから開始し、デザインスタジオで仕上げます。サーバー構築は不要です。"},
# ---- 追加：本番難度（複数選択・最新トピック） ----
{"area":E,"sub":"Power Pagesの機能","type":"multi",
 "q":"Power Pages の機能として正しいものを2つ選んでください（各正解は完全な解決策）。",
 "options":["ローコードツールで外部公開のWebサイトを構築する","Dataverseのデータを認証付きで外部ユーザーに公開する","業務プロセスを自動化する","テンプレートから文書を生成する","ドキュメントからデータを抽出する"],"correct":["ローコードツールで外部公開のWebサイトを構築する","Dataverseのデータを認証付きで外部ユーザーに公開する"],
 "explanation":"Power Pagesはローコードで外部向けWebサイトを構築し、Dataverseデータを認証付きで公開できます。プロセス自動化はPower Automate、文書生成/抽出はAI Builderの領域です。"},
{"area":E,"sub":"Power Pagesサイトの作成","type":"multi",
 "q":"Power Pagesサイトでデータを表示するために使えるコンポーネントを2つ選んでください。",
 "options":["フォーム","リスト","iframe","テキスト"],"correct":["フォーム","リスト"],
 "explanation":"データの表示にはフォーム（1件の詳細）とリスト（一覧）を使います。iframeは外部コンテンツの埋め込み、テキストは静的な文章用で、Dataverseデータの表示コンポーネントではありません。"},
]
