# -*- coding: utf-8 -*-
# Microsoft Entraの機能 (33問)
B = "Microsoft Entraの機能"
SB = [
# ---- Entra IDの機能とID種別 (8) ----
{"area":B,"sub":"Entra IDの機能とID種別","type":"single",
 "q":"クラウドベースのID・アクセス管理サービス（旧Azure Active Directory）はどれですか？",
 "options":["Microsoft Entra ID","Active Directory Domain Services","Microsoft Defender for Identity","Microsoft Sentinel"],"correct":["Microsoft Entra ID"],
 "explanation":"Microsoft Entra ID（旧Azure AD）はクラウドのID・アクセス管理サービスです。AD DSはオンプレミス、Defender for Identityは脅威検知で役割が異なります。"},
{"area":B,"sub":"Entra IDの機能とID種別","type":"single",
 "q":"Microsoft Entra IDで、アプリケーションやサービスが自身を認証するために使うIDの種類はどれですか？",
 "options":["サービスプリンシパル","ユーザー","グループ","管理単位"],"correct":["サービスプリンシパル"],
 "explanation":"サービスプリンシパルはアプリ/サービスがリソースにアクセスするためのIDです。人のIDはユーザーです。"},
{"area":B,"sub":"Entra IDの機能とID種別","type":"single",
 "q":"資格情報（シークレット）を自分で管理せずにAzureリソースが他サービスへ認証できる、Entraが自動管理するIDはどれですか？",
 "options":["マネージドID","ユーザーアカウント","ゲストユーザー","セキュリティグループ"],"correct":["マネージドID"],
 "explanation":"マネージドIDはAzureが資格情報を自動管理するサービスプリンシパルで、シークレットの保管・ローテーションが不要になります。"},
{"area":B,"sub":"Entra IDの機能とID種別","type":"single",
 "q":"取引先など外部組織のユーザーを招待して自社リソースに共同作業させる、Entraの外部ID機能はどれですか？",
 "options":["B2Bコラボレーション","B2C","ハイブリッドID","PIM"],"correct":["B2Bコラボレーション"],
 "explanation":"B2Bコラボレーションは外部組織のユーザーをゲストとして招待し共同作業させます。B2Cは消費者向けアプリのID管理です。"},
{"area":B,"sub":"Entra IDの機能とID種別","type":"single",
 "q":"オンプレミスのActive DirectoryとMicrosoft Entra IDを連携し、同じIDで両方にアクセスできるようにする構成を何と呼びますか？",
 "options":["ハイブリッドID","フェデレーションのみ","B2C","ゲストアクセス"],"correct":["ハイブリッドID"],
 "explanation":"ハイブリッドIDはオンプレADとEntra IDを同期/連携し、ユーザーが単一のIDで双方のリソースにアクセスできるようにします。"},
{"area":B,"sub":"Entra IDの機能とID種別","type":"single",
 "q":"オンプレミスADのユーザーやグループをMicrosoft Entra IDへ同期するためのツールはどれですか？",
 "options":["Microsoft Entra Connect（Cloud Sync）","Microsoft Sentinel","Azure Bastion","Microsoft Defender for Endpoint"],"correct":["Microsoft Entra Connect（Cloud Sync）"],
 "explanation":"Microsoft Entra Connect / Cloud SyncはオンプレADのIDをEntra IDへ同期し、ハイブリッドIDを実現します。"},
{"area":B,"sub":"Entra IDの機能とID種別","type":"single",
 "q":"消費者向けアプリで、ソーシャルアカウントやローカルアカウントによるサインアップ/サインインを提供するEntraのソリューションはどれですか？",
 "options":["Microsoft Entra External ID（B2C）","B2Bコラボレーション","ハイブリッドID","PIM"],"correct":["Microsoft Entra External ID（B2C）"],
 "explanation":"B2C（External ID for customers）は消費者向けアプリの登録・サインインを、ソーシャル/ローカルアカウントで提供します。"},
{"area":B,"sub":"Entra IDの機能とID種別","type":"single",
 "q":"Microsoft Entra IDとオンプレミスのAD DSの違いとして正しいものはどれですか？",
 "options":["Entra IDはクラウドのIDサービスで、AD DSはオンプレミスのドメインサービス","両者は同じ製品","AD DSはクラウド専用","Entra IDはオンプレ専用"],"correct":["Entra IDはクラウドのIDサービスで、AD DSはオンプレミスのドメインサービス"],
 "explanation":"Entra IDはクラウドのIaaS/SaaS向けID管理、AD DSはオンプレミスのドメイン/グループポリシー管理で、設計思想が異なります。"},

# ---- 認証機能 (9) ----
{"area":B,"sub":"認証機能","type":"single",
 "q":"パスワードに加え、スマホ承認やコードなど2つ以上の要素で本人確認する仕組みはどれですか？",
 "options":["多要素認証（MFA）","シングルサインオン（SSO）","条件付きアクセス","セルフサービスパスワードリセット"],"correct":["多要素認証（MFA）"],
 "explanation":"MFAは『知っているもの・持っているもの・自分自身』のうち2つ以上で認証し、セキュリティを大幅に高めます。"},
{"area":B,"sub":"認証機能","type":"single",
 "q":"パスワードを使わず、Windows Hello・FIDO2セキュリティキー・Microsoft Authenticatorで認証する方式を何と呼びますか？",
 "options":["パスワードレス認証","ベーシック認証","証明書失効","フェデレーション"],"correct":["パスワードレス認証"],
 "explanation":"パスワードレス認証はWindows Hello・FIDO2・Authenticatorアプリなどを使い、パスワードに依存せず安全に認証します。"},
{"area":B,"sub":"認証機能","type":"single",
 "q":"ユーザーが管理者を介さず自分でパスワードを再設定できるEntraの機能はどれですか？",
 "options":["セルフサービスパスワードリセット（SSPR）","条件付きアクセス","PIM","アクセスレビュー"],"correct":["セルフサービスパスワードリセット（SSPR）"],
 "explanation":"SSPRはユーザーが本人確認を経て自分でパスワードをリセットでき、ヘルプデスクの負担を減らします。"},
{"area":B,"sub":"認証機能","type":"single",
 "q":"推測されやすい弱いパスワードや禁止語を含むパスワードの設定を防ぐEntraの機能はどれですか？",
 "options":["パスワード保護（グローバル/カスタム禁止パスワード）","多要素認証","条件付きアクセス","アクセスレビュー"],"correct":["パスワード保護（グローバル/カスタム禁止パスワード）"],
 "explanation":"パスワード保護はグローバル/カスタムの禁止パスワードリストで、弱い・推測されやすいパスワードの使用を防ぎます。"},
{"area":B,"sub":"認証機能","type":"single",
 "q":"一度サインインすれば複数のアプリに再認証なしでアクセスできる仕組みはどれですか？",
 "options":["シングルサインオン（SSO）","多要素認証（MFA）","条件付きアクセス","SSPR"],"correct":["シングルサインオン（SSO）"],
 "explanation":"SSOは一度の認証で複数アプリにアクセスでき、利便性とID管理の効率を高めます。"},
{"area":B,"sub":"認証機能","type":"multi",
 "q":"多要素認証（MFA）の要素として適切なものを2つ選んでください。",
 "options":["知っているもの（パスワード）","持っているもの（スマホ/トークン）","アクセスするリソースの場所","リソースのタグ"],"correct":["知っているもの（パスワード）","持っているもの（スマホ/トークン）"],
 "explanation":"MFAの要素は『知っているもの』『持っているもの』『自分自身（生体）』です。リソースの場所やタグは認証要素ではありません。"},
{"area":B,"sub":"認証機能","type":"single",
 "q":"Microsoft Authenticatorアプリで利用できる認証強化機能として適切なものはどれですか？",
 "options":["プッシュ通知の承認やパスワードレスサインイン","ネットワークの分割","ストレージの冗長化","ログの長期保管"],"correct":["プッシュ通知の承認やパスワードレスサインイン"],
 "explanation":"Microsoft AuthenticatorはMFAのプッシュ承認、ワンタイムコード、パスワードレスサインインなどに使えます。"},
{"area":B,"sub":"認証機能","type":"single",
 "q":"ユーザーが本人確認の追加情報（電話番号・代替メール等）を登録しておく必要があるEntraの機能はどれですか？",
 "options":["SSPR（セルフサービスパスワードリセット）","ネットワークセキュリティグループ","Azure Firewall","Key Vault"],"correct":["SSPR（セルフサービスパスワードリセット）"],
 "explanation":"SSPRでは事前に認証方法（電話・メール・セキュリティの質問など）を登録し、本人確認のうえ自分でリセットします。"},
{"area":B,"sub":"認証機能","type":"single",
 "q":"認証方法のうち、一般にセキュリティが最も強いとされるものはどれですか？",
 "options":["FIDO2セキュリティキーなどのパスワードレス","SMSのワンタイムコード","パスワードのみ","セキュリティの質問のみ"],"correct":["FIDO2セキュリティキーなどのパスワードレス"],
 "explanation":"FIDO2などのパスワードレスはフィッシング耐性が高く、最も強い認証とされます。パスワードのみやSMSは相対的に弱くなります。"},

# ---- アクセス管理機能 (8) ----
{"area":B,"sub":"アクセス管理機能","type":"single",
 "q":"場所・デバイス・リスク・アプリなどの条件（シグナル）に基づいてアクセス可否やMFA要求を制御するEntraの機能はどれですか？",
 "options":["条件付きアクセス","RBAC","PIM","アクセスレビュー"],"correct":["条件付きアクセス"],
 "explanation":"条件付きアクセスはシグナルに応じてアクセスを許可/ブロックしたりMFAを要求します。ゼロトラストの中核機能です。"},
{"area":B,"sub":"アクセス管理機能","type":"single",
 "q":"条件付きアクセスポリシーの構成要素として正しい組み合わせはどれですか？",
 "options":["割り当て（シグナル）と、アクセス制御（許可/ブロック/MFA要求）","暗号化キーとハッシュ","NSGルールとサブネット","保持ラベルとDLP"],"correct":["割り当て（シグナル）と、アクセス制御（許可/ブロック/MFA要求）"],
 "explanation":"条件付きアクセスは『誰が・どこから・どのデバイス/アプリで（シグナル）』に対し、許可・ブロック・MFA要求などのアクセス制御を適用します。"},
{"area":B,"sub":"アクセス管理機能","type":"single",
 "q":"ユーザーやグループに『誰が・何に・何をできるか』を最小権限で割り当てるアクセス制御の仕組みはどれですか？",
 "options":["ロールベースアクセス制御（RBAC）","多要素認証","条件付きアクセス","SSPR"],"correct":["ロールベースアクセス制御（RBAC）"],
 "explanation":"RBACは組み込み/カスタムのロールで最小権限を割り当てます。条件付きアクセスはアクセス条件、MFAは認証強化で目的が異なります。"},
{"area":B,"sub":"アクセス管理機能","type":"single",
 "q":"Microsoft Entraのロール（例: グローバル管理者、ユーザー管理者）が制御する主な対象はどれですか？",
 "options":["Entra IDのディレクトリ/テナントの管理操作","Azureリソース（VMやストレージ）への操作のみ","ネットワークのルーティングのみ","Blobの保存階層のみ"],"correct":["Entra IDのディレクトリ/テナントの管理操作"],
 "explanation":"Entraロールはディレクトリ/テナントの管理権限を制御します。AzureリソースへのアクセスはAzure RBAC（リソースロール）で制御します。"},
{"area":B,"sub":"アクセス管理機能","type":"single",
 "q":"『海外からのサインイン試行に対してMFAを必須にする』要件を満たすのに最適なEntraの機能はどれですか？",
 "options":["条件付きアクセス","RBACロールの割り当て","アクセスレビュー","パスワード保護"],"correct":["条件付きアクセス"],
 "explanation":"場所などのシグナルに応じてMFAを要求するのは条件付きアクセスの代表的なユースケースです。"},
{"area":B,"sub":"アクセス管理機能","type":"single",
 "q":"Entraロール（ディレクトリロール）とAzure RBAC（リソースロール）の違いとして正しいものはどれですか？",
 "options":["EntraロールはID/ディレクトリ、Azure RBACはAzureリソースを対象とする","両者は同じ","Azure RBACはメールのみ対象","Entraロールはネットワークのみ対象"],"correct":["EntraロールはID/ディレクトリ、Azure RBACはAzureリソースを対象とする"],
 "explanation":"Entraロールはテナント/ディレクトリ管理、Azure RBACはサブスクリプション配下のリソース操作を制御し、対象が異なります。"},
{"area":B,"sub":"アクセス管理機能","type":"single",
 "q":"条件付きアクセスがゼロトラストを支える理由として最も適切なものはどれですか？",
 "options":["アクセスのたびにシグナルを評価して明示的に検証できる","ネットワーク内を常に信頼できる","パスワードを廃止できる","ログを長期保管できる"],"correct":["アクセスのたびにシグナルを評価して明示的に検証できる"],
 "explanation":"条件付きアクセスはアクセスごとにシグナルを評価して許可/制御するため、ゼロトラストの『明示的に検証』を実現します。"},
{"area":B,"sub":"アクセス管理機能","type":"single",
 "q":"条件付きアクセスで設定できる『アクセス制御』の例として適切でないものはどれですか？",
 "options":["ストレージの冗長化方式の変更","アクセスのブロック","MFAの要求","準拠デバイスの要求"],"correct":["ストレージの冗長化方式の変更"],
 "explanation":"条件付きアクセスのアクセス制御はブロック・MFA要求・準拠デバイス要求などです。ストレージ冗長化はアクセス制御ではありません。"},

# ---- ID保護とガバナンス (8) ----
{"area":B,"sub":"ID保護とガバナンス","type":"single",
 "q":"特権ロールを必要なときだけ時間制限付きで有効化（Just-In-Time）し、特権アクセスを管理するEntraの機能はどれですか？",
 "options":["Privileged Identity Management（PIM）","条件付きアクセス","SSPR","Microsoft Sentinel"],"correct":["Privileged Identity Management（PIM）"],
 "explanation":"PIMは特権ロールをJIT/期間限定で有効化し、承認や監査を伴う特権アクセス管理を提供します。"},
{"area":B,"sub":"ID保護とガバナンス","type":"single",
 "q":"ユーザーやゲストのアクセス権が今も必要か定期的に確認・棚卸しするEntraの機能はどれですか？",
 "options":["アクセスレビュー","PIM","条件付きアクセス","パスワード保護"],"correct":["アクセスレビュー"],
 "explanation":"アクセスレビューは、グループ/アプリ/ロールへのアクセスが妥当かを定期的に確認し、不要な権限を除去します。"},
{"area":B,"sub":"ID保護とガバナンス","type":"single",
 "q":"漏えいした資格情報や不審なサインインなどのリスクを検出し、リスクに応じて自動対応するEntraの機能はどれですか？",
 "options":["Microsoft Entra ID Protection","Microsoft Sentinel","Azure Firewall","Key Vault"],"correct":["Microsoft Entra ID Protection"],
 "explanation":"ID Protectionはサインインリスク/ユーザーリスクを検出し、リスクベースの条件付きアクセスで自動対応（ブロック/MFA要求）します。"},
{"area":B,"sub":"ID保護とガバナンス","type":"single",
 "q":"IDのライフサイクル（参加・異動・退職）に応じてアクセス権を自動付与/失効し、ガバナンスを高める機能群はどれですか？",
 "options":["Microsoft Entra ID Governance","Azure Bastion","Microsoft Defender for Endpoint","WAF"],"correct":["Microsoft Entra ID Governance"],
 "explanation":"Entra ID Governanceは、エンタイトルメント管理・アクセスレビュー・PIM・ライフサイクルワークフローなどでIDとアクセスを統制します。"},
{"area":B,"sub":"ID保護とガバナンス","type":"single",
 "q":"PIMの主な利点として最も適切なものはどれですか？",
 "options":["特権を常時付与せず、必要時のみ昇格させて攻撃面を減らせる","パスワードを廃止できる","ネットワークを分割できる","ログを暗号化できる"],"correct":["特権を常時付与せず、必要時のみ昇格させて攻撃面を減らせる"],
 "explanation":"PIMは常時特権（standing access）を避け、必要時のみJITで昇格させることで、特権の悪用リスクと攻撃面を低減します。"},
{"area":B,"sub":"ID保護とガバナンス","type":"single",
 "q":"ID Protectionが分類する『リスク』の種類として正しい組み合わせはどれですか？",
 "options":["サインインリスクとユーザーリスク","保持リスクと分類リスク","帯域リスクと容量リスク","暗号化リスクとハッシュリスク"],"correct":["サインインリスクとユーザーリスク"],
 "explanation":"ID Protectionはサインインリスク（その認証が不正か）とユーザーリスク（そのアカウントが侵害された可能性）を評価します。"},
{"area":B,"sub":"ID保護とガバナンス","type":"single",
 "q":"外部パートナーへのアクセス権を、申請・承認・期限付きでパッケージとして提供するEntra ID Governanceの機能はどれですか？",
 "options":["エンタイトルメント管理（アクセスパッケージ）","条件付きアクセス","NSG","DLP"],"correct":["エンタイトルメント管理（アクセスパッケージ）"],
 "explanation":"エンタイトルメント管理はアクセスパッケージとして、リソース群へのアクセスを申請・承認・期限付きで提供・管理します。"},
{"area":B,"sub":"ID保護とガバナンス","type":"single",
 "q":"四半期ごとに『管理者ロールを持つ人が今も妥当か』を見直したい。最適なEntraの機能はどれですか？",
 "options":["アクセスレビュー","Azure Firewall","Microsoft Sentinel","Key Vault"],"correct":["アクセスレビュー"],
 "explanation":"ロールやグループのメンバーが妥当かを定期的に確認・棚卸しするのはアクセスレビューの用途です。"},
]
