# -*- coding: utf-8 -*-
# Microsoftセキュリティソリューション (45問)
C = "Microsoftセキュリティソリューション"
SC = [
# ---- Azureの中核インフラセキュリティ (14) ----
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"大量のトラフィックでサービスを停止させようとする攻撃から保護するAzureのサービスはどれですか？",
 "options":["Azure DDoS Protection","Azure Firewall","Web Application Firewall","Azure Bastion"],"correct":["Azure DDoS Protection"],
 "explanation":"Azure DDoS Protectionは分散型サービス拒否（DDoS）攻撃を検出・緩和し、可用性を守ります。FirewallやWAFは別の役割です。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"仮想ネットワークの境界で、ステートフルにトラフィックをフィルタリングするマネージドなネットワークファイアウォールはどれですか？",
 "options":["Azure Firewall","ネットワークセキュリティグループ（NSG）","Azure Bastion","Azure DDoS Protection"],"correct":["Azure Firewall"],
 "explanation":"Azure Firewallはマネージドなステートフルファイアウォールで、VNet全体の集中的なトラフィック制御を行います。NSGはサブネット/NIC単位の基本的なフィルタです。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"SQLインジェクションやクロスサイトスクリプティングなど、Webアプリ層の攻撃から保護する機能はどれですか？",
 "options":["Web Application Firewall（WAF）","ネットワークセキュリティグループ","Azure Bastion","Key Vault"],"correct":["Web Application Firewall（WAF）"],
 "explanation":"WAFはOWASP Top10などのWebアプリ層の攻撃（SQLi/XSS等）から保護します。Application GatewayやFront Doorと併用されます。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"サブネットやネットワークインターフェイス単位で、送受信トラフィックを許可/拒否する基本的なフィルタはどれですか？",
 "options":["ネットワークセキュリティグループ（NSG）","Azure Firewall","WAF","DDoS Protection"],"correct":["ネットワークセキュリティグループ（NSG）"],
 "explanation":"NSGはサブネット/NIC単位で送受信規則を適用する基本的なフィルタです。中央集権的な高度制御はAzure Firewallが担います。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"VMにパブリックIPを公開せず、ブラウザからAzureポータル経由で安全にRDP/SSH接続できるサービスはどれですか？",
 "options":["Azure Bastion","Azure Firewall","WAF","DDoS Protection"],"correct":["Azure Bastion"],
 "explanation":"Azure BastionはVMにパブリックIPを割り当てずに、ポータルからTLS経由でRDP/SSH接続でき、攻撃面を減らします。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"キー・シークレット・証明書を安全に一元管理するAzureのサービスはどれですか？",
 "options":["Azure Key Vault","Azure Bastion","Microsoft Sentinel","Azure Firewall"],"correct":["Azure Key Vault"],
 "explanation":"Azure Key Vaultは暗号化キー・シークレット（パスワード等）・証明書を安全に保管・管理します。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"仮想ネットワークをサブネットに分割し、用途ごとにトラフィックを制御する考え方を何と呼びますか？",
 "options":["ネットワークセグメンテーション","フェデレーション","ハッシュ化","レプリケーション"],"correct":["ネットワークセグメンテーション"],
 "explanation":"ネットワークセグメンテーションはVNet/サブネットで領域を分割し、横移動を抑え多層防御を強化します。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"開発者がアプリのコードにパスワードや接続文字列を直接書かずに済むようにするのに最適なサービスはどれですか？",
 "options":["Azure Key Vault","Azure Bastion","Azure DDoS Protection","Microsoft Sentinel"],"correct":["Azure Key Vault"],
 "explanation":"Key Vaultにシークレットを保管しアプリから参照すれば、コードへの直書きを避けられます（マネージドIDと組み合わせると安全）。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"Azure FirewallとNSGの違いとして正しいものはどれですか？",
 "options":["Firewallは集中型の高度な制御、NSGはサブネット/NIC単位の基本フィルタ","両者は同じ","NSGはDDoS対策専用","FirewallはWebアプリ層専用"],"correct":["Firewallは集中型の高度な制御、NSGはサブネット/NIC単位の基本フィルタ"],
 "explanation":"Azure Firewallは中央集権的なステートフル制御や脅威インテリジェンス連携を提供し、NSGはサブネット/NIC単位の基本的な許可/拒否を行います。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"WAFを配置できるAzureサービスの組み合わせとして適切なものはどれですか？",
 "options":["Application Gateway / Azure Front Door","Azure Bastion / Key Vault","NSG / DDoS Protection","Sentinel / Defender for Cloud"],"correct":["Application Gateway / Azure Front Door"],
 "explanation":"WAFはApplication GatewayやAzure Front Door、CDNと統合して、Webアプリ層の攻撃から保護します。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"VMへの管理接続でパブリックIPを露出させないことの主な利点はどれですか？",
 "options":["インターネットからの攻撃面（公開ポート）を減らせる","ストレージ料金が下がる","SLAが自動的に上がる","ログが不要になる"],"correct":["インターネットからの攻撃面（公開ポート）を減らせる"],
 "explanation":"Bastion等でパブリックIP/公開RDP/SSHポートをなくすと、ブルートフォースなどの攻撃面を大幅に減らせます。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"DDoS Protectionが守る主なセキュリティ特性はどれですか？",
 "options":["可用性（サービスを止めない）","機密性のみ","完全性のみ","否認防止のみ"],"correct":["可用性（サービスを止めない）"],
 "explanation":"DDoS攻撃は可用性を狙うため、DDoS Protectionは主に可用性を守ります（CIAの『可用性』）。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"Key Vaultに保管できないものはどれですか？",
 "options":["仮想マシンのOSディスクイメージ","暗号化キー","シークレット（パスワード等）","証明書"],"correct":["仮想マシンのOSディスクイメージ"],
 "explanation":"Key Vaultはキー・シークレット・証明書を保管します。OSディスクイメージはストレージ/コンピューティング側で扱うもので対象外です。"},
{"area":C,"sub":"Azureの中核インフラセキュリティ","type":"single",
 "q":"『Webアプリ層の保護』『境界の集中ファイアウォール』『サブネット単位の基本フィルタ』の正しい対応はどれですか？",
 "options":["WAF / Azure Firewall / NSG","NSG / WAF / Bastion","Bastion / NSG / WAF","Key Vault / WAF / NSG"],"correct":["WAF / Azure Firewall / NSG"],
 "explanation":"Webアプリ層=WAF、境界の集中ファイアウォール=Azure Firewall、サブネット/NIC単位の基本フィルタ=NSG、と役割が分かれます。"},

# ---- Azureのセキュリティ管理 (10) ----
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"クラウドリソースのセキュリティ態勢を評価し、脅威からの保護を強化する、Azureの統合セキュリティ管理サービスはどれですか？",
 "options":["Microsoft Defender for Cloud","Microsoft Sentinel","Azure Firewall","Microsoft Purview"],"correct":["Microsoft Defender for Cloud"],
 "explanation":"Defender for Cloudはセキュリティ態勢管理（CSPM）とワークロード保護（CWPP）を提供します。SentinelはSIEM/SOARで役割が異なります。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"Defender for Cloudが示す、組織のセキュリティ態勢を数値で表す指標はどれですか？",
 "options":["セキュアスコア","コンプライアンススコア","稼働率SLA","RPO"],"correct":["セキュアスコア"],
 "explanation":"セキュアスコアは推奨事項の達成度をもとにセキュリティ態勢を数値化し、改善の優先度付けに役立ちます。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"クラウド資源の設定ミスや脆弱な構成を継続的に評価・是正する考え方（機能領域）を何と呼びますか？",
 "options":["クラウドセキュリティ態勢管理（CSPM）","SIEM","SOAR","DLP"],"correct":["クラウドセキュリティ態勢管理（CSPM）"],
 "explanation":"CSPMは構成ミスやコンプライアンス逸脱を継続評価し、推奨事項で是正します。Defender for Cloudが提供します。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"VM・コンテナー・SQL・ストレージなどのワークロードを脅威から保護する、Defender for Cloudの強化機能を何と呼びますか？",
 "options":["クラウドワークロード保護（CWP/Defenderプラン）","セキュアスコアのみ","SIEM","保持ポリシー"],"correct":["クラウドワークロード保護（CWP/Defenderプラン）"],
 "explanation":"Defender for Cloudの各Defenderプラン（CWP）は、サーバー・コンテナー・SQL・ストレージなどに高度な脅威保護を追加します。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"Defender for Cloudが組織のコンプライアンス準拠状況を評価する際に使える基準（標準）の例はどれですか？",
 "options":["Microsoft Cloud Security Benchmarkや各種規制標準","保持ラベル","NSGルール","DNSゾーン"],"correct":["Microsoft Cloud Security Benchmarkや各種規制標準"],
 "explanation":"Defender for Cloudの規制コンプライアンスダッシュボードは、Microsoft Cloud Security BenchmarkやISO/PCIなどの標準への準拠を可視化します。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"セキュアスコアを上げるために最も直接的に行うべきことはどれですか？",
 "options":["Defender for Cloudのセキュリティ推奨事項を修復する","VMのサイズを大きくする","ストレージを増やす","タグを追加する"],"correct":["Defender for Cloudのセキュリティ推奨事項を修復する"],
 "explanation":"セキュアスコアは推奨事項の達成度に基づくため、推奨事項を修復（remediate）することでスコアが上がります。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"Defender for CloudとMicrosoft Sentinelの役割の違いとして正しいものはどれですか？",
 "options":["前者は態勢管理/ワークロード保護、後者はSIEM/SOARによる横断的な検知・対応","両者は同じ","Sentinelは態勢評価専用","Defender for CloudはログSIEM専用"],"correct":["前者は態勢管理/ワークロード保護、後者はSIEM/SOARによる横断的な検知・対応"],
 "explanation":"Defender for Cloudは態勢管理(CSPM)とワークロード保護、Sentinelは全社ログを集約するSIEM/SOARで、補完関係にあります。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"組織全体に統一のセキュリティ構成ルールを適用し、逸脱を検出して態勢を高めるのに役立つものはどれですか？",
 "options":["セキュリティポリシー/標準と推奨事項","NSGのみ","Bastionのみ","保持ラベルのみ"],"correct":["セキュリティポリシー/標準と推奨事項"],
 "explanation":"Defender for Cloudのセキュリティポリシー/標準と推奨事項により、統一基準を適用し逸脱を可視化・是正できます。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"オンプレミスや他クラウド（AWS/GCP）のリソースもDefender for Cloudで保護できる理由は何ですか？",
 "options":["マルチクラウド/ハイブリッド対応で、接続すれば態勢評価・保護が可能","Azure専用で他クラウドは不可","オンプレミスのみ対応","SaaSのみ対応"],"correct":["マルチクラウド/ハイブリッド対応で、接続すれば態勢評価・保護が可能"],
 "explanation":"Defender for CloudはマルチクラウドとハイブリッドをサポートＬし、AWS/GCPやオンプレ（Arc経由）も態勢評価・保護できます。"},
{"area":C,"sub":"Azureのセキュリティ管理","type":"single",
 "q":"『構成ミスの是正（態勢管理）』と『実行中のワークロードの脅威検知』を表す用語の正しい対応はどれですか？",
 "options":["CSPM と CWP","SIEM と SOAR","DLP と eDiscovery","MFA と SSO"],"correct":["CSPM と CWP"],
 "explanation":"CSPM（態勢管理）は構成ミスの是正、CWP（ワークロード保護）は実行中のワークロードの脅威検知を担います。"},

# ---- Microsoft Sentinel (9) ----
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"全社のログを集約し、相関分析で脅威を検知・調査するクラウドネイティブなSIEM/SOARはどれですか？",
 "options":["Microsoft Sentinel","Microsoft Defender for Cloud","Azure Firewall","Microsoft Purview"],"correct":["Microsoft Sentinel"],
 "explanation":"Microsoft SentinelはクラウドネイティブなSIEM/SOARで、ログ集約・相関分析・脅威検知・自動対応を行います。"},
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"SIEM（Security Information and Event Management）の主な役割はどれですか？",
 "options":["多様なソースのログを集約・相関分析して脅威を検知する","ファイルを暗号化する","ネットワークを分割する","VMを自動スケールする"],"correct":["多様なソースのログを集約・相関分析して脅威を検知する"],
 "explanation":"SIEMはログ/イベントを集約し相関分析してセキュリティインシデントを検知・可視化します。"},
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"SOAR（Security Orchestration, Automation and Response）の主な役割はどれですか？",
 "options":["プレイブックでインシデント対応を自動化・オーケストレーションする","ログを暗号化する","ストレージを冗長化する","DNSを解決する"],"correct":["プレイブックでインシデント対応を自動化・オーケストレーションする"],
 "explanation":"SOARはプレイブック（自動化手順）でインシデント対応を自動化・オーケストレーションし、対応を高速化します。"},
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"Sentinelで各種データソース（Azure・M365・他社製品等）からログを取り込むために使う仕組みはどれですか？",
 "options":["データコネクタ","保持ラベル","NSGルール","DLPポリシー"],"correct":["データコネクタ"],
 "explanation":"Sentinelのデータコネクタは、Azure・Microsoft 365・サードパーティなど多様なソースからログを取り込みます。"},
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"Sentinelで自動的なインシデント対応手順を定義・実行する仕組みを何と呼びますか？",
 "options":["プレイブック（Logic Appsベース）","ブック（ワークブック）のみ","NSG","保持ポリシー"],"correct":["プレイブック（Logic Appsベース）"],
 "explanation":"プレイブックはAzure Logic Appsベースの自動化で、アラート/インシデントに応じて対応（通知・隔離等）を自動実行します。"},
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"Sentinelでデータを可視化し、ダッシュボードとして表示する機能はどれですか？",
 "options":["ワークブック","プレイブック","データコネクタ","ハンティングクエリのみ"],"correct":["ワークブック"],
 "explanation":"ワークブックは取り込んだデータを可視化・ダッシュボード化します。プレイブックは自動対応、コネクタはデータ取り込みです。"},
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"Sentinelで、まだアラート化されていない脅威を能動的に探索する活動を何と呼びますか？",
 "options":["脅威ハンティング","保持","分類","フェデレーション"],"correct":["脅威ハンティング"],
 "explanation":"脅威ハンティングはKQLクエリ等で潜在的な脅威を能動的に探索する活動で、Sentinelが支援します。"},
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"Sentinelがログのクエリやハンティングでよく使う言語はどれですか？",
 "options":["Kusto照会言語（KQL）","DAX","Power Fx","T-SQLのみ"],"correct":["Kusto照会言語（KQL）"],
 "explanation":"SentinelはLog Analyticsを基盤とし、KQL（Kusto照会言語）でログのクエリ・分析・ハンティングを行います。"},
{"area":C,"sub":"Microsoft Sentinel","type":"single",
 "q":"SIEMとSOARの違いとして正しいものはどれですか？",
 "options":["SIEMは検知/可視化、SOARは対応の自動化","両者は同じ","SOARはログ収集専用","SIEMは自動対応専用"],"correct":["SIEMは検知/可視化、SOARは対応の自動化"],
 "explanation":"SIEMはログ集約と検知・可視化、SOARはインシデント対応の自動化を担います。Sentinelは両方を提供します。"},

# ---- Microsoft Defender XDR (12) ----
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"エンドポイント・メール・ID・クラウドアプリ等のシグナルを横断的に相関し、検知・調査・対応を統合する製品群はどれですか？",
 "options":["Microsoft Defender XDR","Microsoft Sentinel","Azure Firewall","Microsoft Purview"],"correct":["Microsoft Defender XDR"],
 "explanation":"Defender XDRは複数のDefender製品のシグナルを横断的に相関（XDR）し、統合的に検知・調査・対応します。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"PCやサーバーなどのエンドポイントをマルウェアや高度な脅威から保護・検知（EDR）するサービスはどれですか？",
 "options":["Microsoft Defender for Endpoint","Microsoft Defender for Office 365","Microsoft Defender for Identity","Microsoft Defender for Cloud Apps"],"correct":["Microsoft Defender for Endpoint"],
 "explanation":"Defender for Endpointはエンドポイントの脅威保護・EDR・脆弱性管理を提供します。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"メールやTeams、SharePointへのフィッシングやマルウェア添付から保護するサービスはどれですか？",
 "options":["Microsoft Defender for Office 365","Microsoft Defender for Endpoint","Microsoft Defender for Identity","Microsoft Sentinel"],"correct":["Microsoft Defender for Office 365"],
 "explanation":"Defender for Office 365はメール/コラボレーション（Teams・SharePoint等）のフィッシング・マルウェア・なりすましから保護します。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"オンプレミスのActive Directoryのシグナルを用いて、IDベースの高度な攻撃や横移動を検知するサービスはどれですか？",
 "options":["Microsoft Defender for Identity","Microsoft Defender for Endpoint","Microsoft Defender for Office 365","Microsoft Purview"],"correct":["Microsoft Defender for Identity"],
 "explanation":"Defender for IdentityはオンプレADのシグナルから、認証情報の窃取や横移動などIDベースの脅威を検知します。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"クラウドアプリ（SaaS）の利用状況の可視化と制御（CASB）を提供するサービスはどれですか？",
 "options":["Microsoft Defender for Cloud Apps","Microsoft Defender for Endpoint","Microsoft Defender for Office 365","Azure Firewall"],"correct":["Microsoft Defender for Cloud Apps"],
 "explanation":"Defender for Cloud AppsはCASBとして、SaaSアプリの可視化・シャドーIT検出・データ制御・脅威検知を提供します。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"デバイスやソフトウェアの脆弱性を継続的に検出・優先順位付けし、是正を支援する機能はどれですか？",
 "options":["Microsoft Defender 脆弱性管理","Microsoft Sentinel","Azure Bastion","DLP"],"correct":["Microsoft Defender 脆弱性管理"],
 "explanation":"Defender 脆弱性管理は資産の脆弱性を継続評価し、リスクに基づいて是正の優先順位付けを支援します。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"攻撃者のインフラや脅威アクターに関する外部情報を提供し、調査を支援するサービスはどれですか？",
 "options":["Microsoft Defender Threat Intelligence（Defender TI）","Microsoft Defender for Endpoint","Azure Firewall","Key Vault"],"correct":["Microsoft Defender Threat Intelligence（Defender TI）"],
 "explanation":"Defender TIは脅威アクターや攻撃インフラに関する脅威インテリジェンスを提供し、調査・ハンティングを支援します。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"Defender XDRの各サービスのインシデントやアラートを一元的に表示・調査・対応するポータルはどれですか？",
 "options":["Microsoft Defenderポータル","Azure Portal","Microsoft Purviewポータル","Entra管理センター"],"correct":["Microsoft Defenderポータル"],
 "explanation":"Microsoft Defenderポータル（security.microsoft.com）はXDR各サービスのインシデント・アラートを一元管理する統合コンソールです。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"『従業員のPCがランサムウェアに感染した疑い』を検知・隔離・調査するのに最適なサービスはどれですか？",
 "options":["Microsoft Defender for Endpoint","Microsoft Defender for Office 365","Microsoft Defender for Cloud Apps","Microsoft Purview"],"correct":["Microsoft Defender for Endpoint"],
 "explanation":"エンドポイント（PC）のマルウェア検知・隔離・調査（EDR）はDefender for Endpointの役割です。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"『役員宛のフィッシングメールに悪意あるリンクが含まれていた』ケースに最も関係するサービスはどれですか？",
 "options":["Microsoft Defender for Office 365","Microsoft Defender for Identity","Microsoft Defender for Cloud Apps","Azure Firewall"],"correct":["Microsoft Defender for Office 365"],
 "explanation":"メールのフィッシング/悪意あるリンク（Safe Links等）からの保護はDefender for Office 365の役割です。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"multi",
 "q":"Microsoft Defender XDRに含まれるサービスを2つ選んでください。",
 "options":["Microsoft Defender for Endpoint","Microsoft Defender for Office 365","Azure Bastion","Azure Key Vault"],"correct":["Microsoft Defender for Endpoint","Microsoft Defender for Office 365"],
 "explanation":"Defender XDRにはEndpoint・Office 365・Identity・Cloud Appsなどが含まれます。BastionやKey VaultはAzureインフラのセキュリティサービスでXDRの構成要素ではありません。"},
{"area":C,"sub":"Microsoft Defender XDR","type":"single",
 "q":"Defender XDRが『XDR（Extended Detection and Response）』と呼ばれる理由として最も適切なものはどれですか？",
 "options":["複数のドメイン（ID・メール・端末・クラウド）を横断して検知・対応を相関するため","単一の端末だけを保護するため","ネットワークだけを保護するため","ログを保存するだけのため"],"correct":["複数のドメイン（ID・メール・端末・クラウド）を横断して検知・対応を相関するため"],
 "explanation":"XDRは単一ドメインのEDR等を超え、ID・メール・端末・クラウドなど複数ドメインのシグナルを横断的に相関して検知・対応します。"},
]
