# -*- coding: utf-8 -*-
# リレーショナルデータ (28問) — 本番難度版
B = "リレーショナルデータ"
DB = [
# ---- リレーショナルの概念 (16) ----
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"テーブル内の各行を一意に識別する列（または列の組）を何と呼びますか？",
 "options":["主キー（プライマリキー）","外部キー","インデックス","ビュー"],"correct":["主キー（プライマリキー）"],
 "explanation":"主キーは各行を一意に識別する列で、重複やNULLを許しません。他テーブルを参照するのは外部キーです。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"あるテーブルの列が別テーブルの主キーを参照して関連付ける仕組みを何と呼びますか？",
 "options":["外部キー（フォーリンキー）","主キー","インデックス","制約のないカラム"],"correct":["外部キー（フォーリンキー）"],
 "explanation":"外部キーは他テーブルの主キーを参照し、テーブル間のリレーションシップ（参照整合性）を表します。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"データの重複を減らし整合性を高めるためにテーブルを適切に分割する設計手法を何と呼びますか？",
 "options":["正規化","非正規化","シャーディング","パーティション分割"],"correct":["正規化"],
 "explanation":"正規化は重複を排除し更新異常を防ぐためにデータを複数テーブルに分割しキーで関連付ける設計手法です。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"正規化を行う主な目的として最も適切なものはどれですか？",
 "options":["データの重複を減らし整合性を保つ","クエリを必ず高速化する","画像を保存できるようにする","ネットワークを暗号化する"],"correct":["データの重複を減らし整合性を保つ"],
 "explanation":"正規化の主目的は重複削減と整合性維持です。分析向けには意図的に非正規化することもあります。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"テーブルからデータを取得（問い合わせ）するSQL文はどれですか？",
 "options":["SELECT","INSERT","UPDATE","CREATE"],"correct":["SELECT"],
 "explanation":"SELECTはデータの取得に使います。追加はINSERT、変更はUPDATE、構造定義はCREATEです。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"テーブルに新しい行を追加するSQL文はどれですか？",
 "options":["INSERT","SELECT","UPDATE","DROP"],"correct":["INSERT"],
 "explanation":"INSERTは新しい行を追加します。既存行の変更はUPDATE、削除はDELETE、テーブル削除はDROPです。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"既存の行の値を変更するSQL文はどれですか？",
 "options":["UPDATE","INSERT","SELECT","ALTER"],"correct":["UPDATE"],
 "explanation":"UPDATEは既存行の列値を変更します。対象行はWHERE句で指定します。ALTERはテーブル構造の変更です。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"テーブルなどの構造を定義・変更するSQLの分類（CREATE/ALTER/DROP）はどれですか？",
 "options":["DDL（データ定義言語）","DML（データ操作言語）","DCL（データ制御言語）","TCL（トランザクション制御）"],"correct":["DDL（データ定義言語）"],
 "explanation":"DDLは構造を定義・変更します。データの追加・更新・削除はDML、権限制御はDCLです。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"INSERT・UPDATE・DELETEなど、データそのものを操作するSQLの分類はどれですか？",
 "options":["DML（データ操作言語）","DDL（データ定義言語）","DCL（データ制御言語）","DQL"],"correct":["DML（データ操作言語）"],
 "explanation":"DMLはINSERT/UPDATE/DELETEなどデータの操作を行います。構造の定義はDDLです。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"GRANTやREVOKEのように権限を付与・取り消しするSQLの分類はどれですか？",
 "options":["DCL（データ制御言語）","DDL（データ定義言語）","DML（データ操作言語）","TCL"],"correct":["DCL（データ制御言語）"],
 "explanation":"DCLはGRANT/REVOKEなどで権限を制御します。コミット/ロールバックはTCLです。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"特定の列に対する検索や並べ替えを高速化するために作成するデータベースオブジェクトはどれですか？",
 "options":["インデックス","ビュー","トリガー","主キー制約"],"correct":["インデックス"],
 "explanation":"インデックスは検索や並べ替えを高速化します。ただし書き込みコストや容量は増えます。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"1つ以上のテーブルから定義した『仮想的なテーブル』として参照できるオブジェクトはどれですか？",
 "options":["ビュー","インデックス","主キー","スキーマ"],"correct":["ビュー"],
 "explanation":"ビューはクエリ結果を仮想テーブルとして扱えるオブジェクトで、複雑なクエリの再利用やアクセス制御に役立ちます。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"あらかじめ保存しておき、呼び出して実行できる一連のSQL処理を何と呼びますか？",
 "options":["ストアドプロシージャ","インデックス","ビュー","シーケンス"],"correct":["ストアドプロシージャ"],
 "explanation":"ストアドプロシージャはDBに保存された一連のSQL処理で、引数を取り再利用できます。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"リレーショナルデータの特徴として最も適切なものはどれですか？",
 "options":["事前定義のスキーマを持ち、テーブル間をキーで関連付ける","スキーマが一切ない","画像専用である","必ず1テーブルのみで構成される"],"correct":["事前定義のスキーマを持ち、テーブル間をキーで関連付ける"],
 "explanation":"リレーショナルデータは列の型や制約を持つスキーマに従い、主キー・外部キーでテーブル同士を関連付けます。"},
{"area":B,"sub":"リレーショナルの概念","type":"single",
 "q":"SELECTやUPDATE/DELETEで対象行を条件によって絞り込むために使う句はどれですか？",
 "options":["WHERE","ORDER BY","GROUP BY","CREATE"],"correct":["WHERE"],
 "explanation":"WHERE句は対象行を条件で絞り込みます。ORDER BYは並べ替え、GROUP BYは集計のグループ化です。"},
{"area":B,"sub":"リレーショナルの概念","type":"multi",
 "q":"次のうちリレーショナルデータベースのオブジェクトを2つ選んでください。",
 "options":["ビュー","インデックス","Blobコンテナー","コネクタ"],"correct":["ビュー","インデックス"],
 "explanation":"ビューやインデックス、テーブル、ストアドプロシージャはリレーショナルDBのオブジェクトです。Blobコンテナーやコネクタは別概念です。"},

# ---- リレーショナル系Azureサービス (12) ----
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"フルマネージドなPaaSのリレーショナルデータベースで、SQL Serverエンジンを基盤とするサービスはどれですか？",
 "options":["Azure SQL Database","Azure Cosmos DB","Azure Blob Storage","Azure Table Storage"],"correct":["Azure SQL Database"],
 "explanation":"Azure SQL DatabaseはSQL ServerベースのフルマネージドなリレーショナルDB（PaaS）で、パッチやバックアップを自動化します。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"オンプレミスのSQL Serverとの高い互換性を保ちつつ、ほぼフルマネージドで運用できるサービスはどれですか？",
 "options":["Azure SQL Managed Instance","Azure SQL Database（単一DB）","SQL Server on Azure VM","Azure Database for MySQL"],"correct":["Azure SQL Managed Instance"],
 "explanation":"Managed Instanceはインスタンスレベルの互換性が高く、オンプレSQL Serverの移行に適したマネージドサービスです。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"OSやSQL Serverの構成を完全に制御したい場合に選ぶ、最もIaaS寄りの選択肢はどれですか？",
 "options":["SQL Server on Azure Virtual Machines","Azure SQL Database","Azure SQL Managed Instance","Azure Database for PostgreSQL"],"correct":["SQL Server on Azure Virtual Machines"],
 "explanation":"SQL Server on Azure VMはIaaSで、OSとSQL Serverを完全に制御できます。その分、運用管理の責任も大きくなります。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"管理負担を最小にしたい場合、Azure SQLファミリーの中で最もマネージド度が高いのはどれですか？",
 "options":["Azure SQL Database","SQL Server on Azure VM","Azure SQL Managed Instance","オンプレミスSQL Server"],"correct":["Azure SQL Database"],
 "explanation":"Azure SQL Database（PaaS）は最もマネージド度が高く、インフラやOSの管理が不要です。VMはIaaSで管理範囲が広くなります。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"Azureが提供するオープンソース系リレーショナルDBのマネージドサービスに含まれるものはどれですか？",
 "options":["Azure Database for PostgreSQL","Azure Cosmos DB","Azure Table Storage","Azure Cache for Redis"],"correct":["Azure Database for PostgreSQL"],
 "explanation":"AzureはAzure Database for PostgreSQL / MySQL / MariaDB といったOSS DBのマネージドサービスを提供します。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"次のうちAzureのオープンソースDBマネージドサービスとして提供されていないものはどれですか？",
 "options":["Azure Database for Oracle","Azure Database for MySQL","Azure Database for PostgreSQL","Azure Database for MariaDB"],"correct":["Azure Database for Oracle"],
 "explanation":"マネージドOSS DBはMySQL・PostgreSQL・MariaDBです。Oracleはこのマネージドサービスとしては提供されていません。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"Azure SQL DatabaseとSQL Server on VMを比較した説明として正しいものはどれですか？",
 "options":["SQL DatabaseはPaaSで運用が自動化、VMはIaaSで自分で管理","両方ともIaaS","両方ともPaaS","SQL DatabaseはIaaS、VMはPaaS"],"correct":["SQL DatabaseはPaaSで運用が自動化、VMはIaaSで自分で管理"],
 "explanation":"Azure SQL DatabaseはPaaSでパッチ・バックアップ等が自動化、SQL Server on VMはIaaSでOS・SQLの管理を利用者が担います。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"既存のオンプレミスSQL Serverを、最小限の変更でAzureのマネージド環境へ移行したい。最適なのはどれですか？",
 "options":["Azure SQL Managed Instance","Azure Cosmos DB","Azure Blob Storage","Azure Table Storage"],"correct":["Azure SQL Managed Instance"],
 "explanation":"Managed Instanceはインスタンスレベルの互換性が高く、オンプレSQL Serverのリフト＆シフト移行に適します。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"Azure SQL Database（PaaS）で自動的に提供される運用上の利点として最も適切なものはどれですか？",
 "options":["自動バックアップとパッチ適用、高可用性","物理サーバーの手動増設","OSの手動アップデート","電源の手動管理"],"correct":["自動バックアップとパッチ適用、高可用性"],
 "explanation":"PaaSのAzure SQL Databaseはバックアップ・パッチ・高可用性などが自動化され、運用負担を大幅に軽減します。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"Web開発で広く使われるMySQLをAzure上でマネージドに利用したい。選ぶサービスはどれですか？",
 "options":["Azure Database for MySQL","Azure SQL Database","Azure Cosmos DB","Azure Synapse Analytics"],"correct":["Azure Database for MySQL"],
 "explanation":"Azure Database for MySQLはMySQLをフルマネージドで提供し、バックアップやスケールを自動化します。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"利用が変動する多数のデータベースで、リソースを共有してコスト最適化できるAzure SQL Databaseの仕組みはどれですか？",
 "options":["エラスティックプール","読み取りレプリカ","ジオレプリケーション","フェールオーバーグループ"],"correct":["エラスティックプール"],
 "explanation":"エラスティックプールは複数DBでコンピューティングを共有し、利用が変動する多数DBのコストを最適化します。"},
{"area":B,"sub":"リレーショナル系Azureサービス","type":"single",
 "q":"Azure SQL Databaseが内部的に基盤とするデータベースエンジンはどれですか？",
 "options":["Microsoft SQL Server","MySQL","PostgreSQL","MongoDB"],"correct":["Microsoft SQL Server"],
 "explanation":"Azure SQL DatabaseはMicrosoft SQL Serverのエンジンを基盤としたPaaSで、T-SQLで操作できます。"},
]
