# -*- coding: utf-8 -*-
# 非リレーショナルデータ (22問) — 本番難度版
C = "非リレーショナルデータ"
DC = [
# ---- Azureストレージ (12) ----
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"画像・動画・バックアップなどの非構造化オブジェクトを格納するストレージはどれですか？",
 "options":["Azure Blob Storage","Azure SQL Database","Azure Table Storage","Azure Cosmos DB"],"correct":["Azure Blob Storage"],
 "explanation":"Blob Storageは非構造化データ（オブジェクト）の格納に最適化されています。SQL DatabaseやTable/Cosmosは構造化・半構造化向けです。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"SMB/NFSでマウントして共有フォルダーのように使えるストレージはどれですか？",
 "options":["Azure File Storage","Azure Blob Storage","Azure Table Storage","Azure Queue Storage"],"correct":["Azure File Storage"],
 "explanation":"Azure Files（File Storage）はSMB/NFSでマウントできるマネージドファイル共有で、オンプレミスのファイルサーバー置き換えにも使えます。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"キーと属性によるスキーマレスな表形式データを安価に大量保存できるストレージはどれですか？",
 "options":["Azure Table Storage","Azure Blob Storage","Azure File Storage","Azure SQL Database"],"correct":["Azure Table Storage"],
 "explanation":"Azure Table Storageはキー/属性ストアとして半構造化データを大量・安価に保存できるNoSQLストレージです。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"アクセス頻度が非常に低い長期保管データに最適で、保存単価が最も安いBlobのアクセス層はどれですか？",
 "options":["アーカイブ層","ホット層","クール層","プレミアム層"],"correct":["アーカイブ層"],
 "explanation":"アーカイブ層は保存単価が最も安い一方、取り出しに時間がかかります。頻繁にアクセスするならホット層が適します。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"頻繁にアクセスするデータに最適なBlobのアクセス層はどれですか？",
 "options":["ホット層","クール層","アーカイブ層","コールド層"],"correct":["ホット層"],
 "explanation":"ホット層はアクセス頻度の高いデータ向けで、アクセスコストは低く保存コストは高めです。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"アプリやサービス間で処理待ちのメッセージを非同期にやり取りするためのストレージはどれですか？",
 "options":["Azure Queue Storage","Azure Blob Storage","Azure File Storage","Azure Table Storage"],"correct":["Azure Queue Storage"],
 "explanation":"Queue Storageはコンポーネント間でメッセージを非同期にやり取りするためのキューを提供します。Blobはオブジェクト、Filesは共有、Tableはキー値です。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"ストレージアカウントのデータを単一データセンター内で3重に複製する、最も安価な冗長オプションはどれですか？",
 "options":["ローカル冗長ストレージ（LRS）","geo冗長ストレージ（GRS）","読み取りアクセスgeo冗長（RA-GRS）","ゾーン冗長（ZRS）"],"correct":["ローカル冗長ストレージ（LRS）"],
 "explanation":"LRSは同一データセンター内で3コピーを保持する最も安価な方式ですが、リージョン障害には対応できません。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"別リージョンにもデータを複製してリージョン障害に備える冗長オプションはどれですか？",
 "options":["geo冗長ストレージ（GRS）","ローカル冗長（LRS）","ゾーン冗長（ZRS）","プレミアムSSD"],"correct":["geo冗長ストレージ（GRS）"],
 "explanation":"GRSはプライマリとは別リージョンにもデータを複製し、リージョン規模の障害から保護します。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"ビッグデータ分析向けに階層型名前空間を備え、Blob上に構築される大容量データレイク用ストレージはどれですか？",
 "options":["Azure Data Lake Storage Gen2","Azure Table Storage","Azure Queue Storage","Azure Cache for Redis"],"correct":["Azure Data Lake Storage Gen2"],
 "explanation":"Azure Data Lake Storage Gen2はBlob Storage上に階層型名前空間を加えたもので、大規模分析（データレイク）に適します。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"オンプレミスとAzure Files間でファイルを同期し、よく使うファイルをローカルにキャッシュする機能はどれですか？",
 "options":["Azure File Sync","AzCopy","Azure Migrate","Azure Backup"],"correct":["Azure File Sync"],
 "explanation":"Azure File SyncはオンプレミスのファイルサーバーとAzure Filesを同期し、クラウド階層化でローカル容量を節約できます。"},
{"area":C,"sub":"Azureストレージ","type":"multi",
 "q":"Azure Storageアカウントが提供するサービスを2つ選んでください。",
 "options":["Blob Storage","Queue Storage","Azure SQL Database","Azure Cosmos DB"],"correct":["Blob Storage","Queue Storage"],
 "explanation":"Storageアカウントが提供するのはBlob・File・Queue・Tableです。SQL DatabaseやCosmos DBはマネージドDBで別サービスです。"},
{"area":C,"sub":"Azureストレージ","type":"single",
 "q":"非リレーショナル（NoSQL）データを扱う主な理由として最も適切なものはどれですか？",
 "options":["柔軟なスキーマと大規模・高速なスケールが必要な場合に適する","必ず多テーブル結合が必要な場合に最適","常に厳密なトランザクション整合性が最優先の場合のみ","構造化データにしか使えない"],"correct":["柔軟なスキーマと大規模・高速なスケールが必要な場合に適する"],
 "explanation":"NoSQLは柔軟なスキーマ、大規模分散、高速な読み書き・スケールが求められる用途に適します。"},

# ---- Azure Cosmos DB (10) ----
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"グローバル分散と低遅延を特長とする、Azureのフルマネージドな非リレーショナル（NoSQL）DBはどれですか？",
 "options":["Azure Cosmos DB","Azure SQL Database","Azure Blob Storage","Azure Synapse Analytics"],"correct":["Azure Cosmos DB"],
 "explanation":"Cosmos DBは複数リージョンに分散でき、世界規模で低遅延・高可用性を実現するマネージドNoSQLです。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"Azure Cosmos DBのユースケースとして最も適切なものはどれですか？",
 "options":["世界中のユーザーに低遅延で応答する必要があるアプリ","厳密な多テーブル結合の会計バッチのみ","単一サーバーの小規模社内集計のみ","画像のアーカイブ保管のみ"],"correct":["世界中のユーザーに低遅延で応答する必要があるアプリ"],
 "explanation":"Cosmos DBはグローバル分散ユーザーへ低遅延で応答する必要があるWeb/モバイル/IoTアプリなどに適します。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"Azure Cosmos DBでJSONドキュメントを扱う、既定のネイティブAPIはどれですか？",
 "options":["NoSQL（Core/SQL）API","Cassandra API","Gremlin API","Table API"],"correct":["NoSQL（Core/SQL）API"],
 "explanation":"NoSQL（旧Core/SQL）APIはJSONドキュメントを格納し、SQLライクな構文でクエリできるネイティブAPIです。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"既存のMongoDBアプリをほぼ変更せずにCosmos DBへ移行したい。使うAPIはどれですか？",
 "options":["MongoDB用API","Gremlin API","Table API","Cassandra API"],"correct":["MongoDB用API"],
 "explanation":"MongoDB用APIはMongoDBのワイヤプロトコルと互換性があり、既存のMongoDBアプリやツールをほぼそのまま利用できます。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"ノードとエッジで関係性を表すグラフデータを扱うCosmos DBのAPIはどれですか？",
 "options":["Gremlin API","NoSQL API","Table API","Cassandra API"],"correct":["Gremlin API"],
 "explanation":"Gremlin APIはグラフ（頂点と辺）を扱うAPIで、ソーシャルネットワークや推薦などの関係探索に適します。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"列指向のワイドカラムデータを扱い、Apache Cassandra互換で利用できるCosmos DBのAPIはどれですか？",
 "options":["Cassandra API","NoSQL API","Gremlin API","MongoDB用API"],"correct":["Cassandra API"],
 "explanation":"Cassandra APIはApache Cassandra互換のワイドカラムデータを扱え、既存のCassandraアプリを移行できます。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"Azure Table Storageに似たキー/値テーブルを、グローバル分散などの利点付きで扱えるCosmos DBのAPIはどれですか？",
 "options":["Table API","Gremlin API","Cassandra API","NoSQL API"],"correct":["Table API"],
 "explanation":"Cosmos DBのTable APIはTable Storage互換のキー/値テーブルを、グローバル分散や低遅延の利点付きで利用できます。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"Azure Cosmos DBの主な利点として最も適切なものはどれですか？",
 "options":["1桁ミリ秒の低遅延とグローバル分散、自動スケール","厳密な正規化を強制する","画像専用の保存に最適","常に単一リージョンに固定される"],"correct":["1桁ミリ秒の低遅延とグローバル分散、自動スケール"],
 "explanation":"Cosmos DBは複数リージョン分散・1桁ミリ秒級の低遅延・自動スケール・複数の整合性レベルなどを特長とします。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"Cosmos DBが複数の整合性レベル（強整合〜結果整合）を選べる主な目的はどれですか？",
 "options":["遅延・可用性と整合性のトレードオフを用途に応じて調整するため","データを暗号化するため","SQLを無効化するため","必ず最強整合のみにするため"],"correct":["遅延・可用性と整合性のトレードオフを用途に応じて調整するため"],
 "explanation":"Cosmos DBは強整合から結果整合まで複数の整合性レベルを提供し、遅延・可用性・整合性のバランスを用途に合わせて選べます。"},
{"area":C,"sub":"Azure Cosmos DB","type":"single",
 "q":"IoTデバイスから世界中で大量に届くテレメトリを低遅延で取り込み・参照したい。最適なのはどれですか？",
 "options":["Azure Cosmos DB","Azure SQL Managed Instance","Azure Files","オンプレミスの単一SQL Server"],"correct":["Azure Cosmos DB"],
 "explanation":"グローバル分散・高スループット・低遅延のCosmos DBは、IoTテレメトリのような大量・分散データの取り込みと参照に適します。"},
]
