# -*- coding: utf-8 -*-
# 分析ワークロード (36問) — 本番難度版
D = "分析ワークロード"
DD = [
# ---- 大規模分析の要素 (16) ----
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"複数のソースからデータを抽出・変換・読み込みする処理を一般に何と呼びますか？",
 "options":["ETL / ELT","OLTP","ACID","RBAC"],"correct":["ETL / ELT"],
 "explanation":"ETL（抽出・変換・読み込み）やELT（抽出・読み込み・変換）は、分析基盤へデータを取り込み整える代表的なプロセスです。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"ノーコード/ローコードでデータ取り込みや変換のパイプラインを構築できるAzureのデータ統合サービスはどれですか？",
 "options":["Azure Data Factory","Azure Blob Storage","Power BI Desktop","Azure Monitor"],"correct":["Azure Data Factory"],
 "explanation":"Azure Data Factoryはデータの取り込み・変換・移動を行うパイプラインを構築するクラウドのデータ統合（ETL/ELT）サービスです。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"分析向けに整形・集約した構造化データを大量に蓄積する分析データストアを何と呼びますか？",
 "options":["データウェアハウス","メッセージキュー","キャッシュ","ファイル共有"],"correct":["データウェアハウス"],
 "explanation":"データウェアハウスは分析用に整形・統合した構造化データを蓄積し、集計・レポートに最適化されたデータストアです。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"あらゆる形式（構造化・半構造化・非構造化）の生データを大規模に保管できるストアを何と呼びますか？",
 "options":["データレイク","データウェアハウスのみ","リレーショナルDBのみ","メッセージキュー"],"correct":["データレイク"],
 "explanation":"データレイクは構造化・半構造化・非構造化を問わず生データを大規模・低コストに保管でき、後続の分析や加工に使われます。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"データウェアハウスとビッグデータ分析を統合したAzureのエンタープライズ分析サービスはどれですか？",
 "options":["Azure Synapse Analytics","Azure Blob Storage","Azure Cache for Redis","Azure Cosmos DB"],"correct":["Azure Synapse Analytics"],
 "explanation":"Azure Synapse Analyticsはデータウェアハウスとビッグデータ分析（Spark/SQL）を統合した分析プラットフォームです。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"Apache Sparkベースで大規模データ処理や機械学習を行えるAzureの分析サービスはどれですか？",
 "options":["Azure Databricks","Azure Files","Azure Queue Storage","Azure Data Factory"],"correct":["Azure Databricks"],
 "explanation":"Azure DatabricksはApache Sparkベースの分析プラットフォームで、大規模データ処理・データエンジニアリング・機械学習に使われます。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"データ統合・データウェアハウス・分析・BIをSaaSとして一体提供するMicrosoftの統合分析プラットフォームはどれですか？",
 "options":["Microsoft Fabric","Azure Data Factory","Azure Databricks","Azure Synapse Analytics"],"correct":["Microsoft Fabric"],
 "explanation":"Microsoft Fabricはデータ統合・エンジニアリング・データウェアハウス・リアルタイム分析・Power BIを統合したSaaS型分析基盤です。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"Microsoft Fabricで全コンポーネントが共有する単一の統合データレイク基盤を何と呼びますか？",
 "options":["OneLake","Blob Storage","Cosmos DB","Log Analytics"],"correct":["OneLake"],
 "explanation":"OneLakeはMicrosoft Fabricの統合データレイクで、組織全体のデータを一元的に格納し各ワークロードで共有します。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"ELT（抽出・読み込み・変換）がETLと異なる主な点はどれですか？",
 "options":["先に格納してから変換する（変換を後段で行う）","変換を一切行わない","データを削除する処理である","可視化の手法である"],"correct":["先に格納してから変換する（変換を後段で行う）"],
 "explanation":"ELTはまずデータを取り込んで格納し、後でターゲット側の計算資源を使って変換します。大規模データやデータレイクで有効です。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"分析基盤における『データ取り込み（インジェスト）』の説明として正しいものはどれですか？",
 "options":["各種ソースからデータを収集して取り込むこと","データを可視化すること","権限を付与すること","SQLのインデックスを作ること"],"correct":["各種ソースからデータを収集して取り込むこと"],
 "explanation":"データインジェストは、ファイル・DB・ストリームなど各種ソースからデータを収集し分析基盤へ取り込むプロセスです。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"データウェアハウスとデータレイクの違いとして正しいものはどれですか？",
 "options":["DWは整形済み構造化データ中心、レイクは生データを多様な形式で保管","両者は完全に同じ","レイクは構造化データ専用","DWは画像専用"],"correct":["DWは整形済み構造化データ中心、レイクは生データを多様な形式で保管"],
 "explanation":"データウェアハウスは整形済みの構造化データを分析向けに蓄積し、データレイクは生データを多様な形式のまま大規模に保管します。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"大規模分析パイプラインの一般的な流れとして正しい順序はどれですか？",
 "options":["取り込み → 処理/変換 → 格納 → 分析・可視化","可視化 → 取り込み → 削除","分析 → 取り込み → 破棄","格納 → 可視化 → 取り込み"],"correct":["取り込み → 処理/変換 → 格納 → 分析・可視化"],
 "explanation":"一般にデータを取り込み、処理・変換し、分析ストアに格納し、最後に分析・可視化する流れになります。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"Azure Synapseで、データレイクのファイルを事前プロビジョニングなしにSQLで分析できる機能はどれですか？",
 "options":["サーバーレスSQLプール","専用SQLプール（旧SQL DW）のみ","Power BIのみ","Blobのアクセス層"],"correct":["サーバーレスSQLプール"],
 "explanation":"Synapseのサーバーレス SQLプールはデータレイク上のファイルにSQLでアドホックに分析でき、事前のプロビジョニングが不要です。"},
{"area":D,"sub":"大規模分析の要素","type":"multi",
 "q":"Azureの大規模分析向けサービスを2つ選んでください。",
 "options":["Azure Synapse Analytics","Azure Databricks","Azure Cache for Redis","Azure Bastion"],"correct":["Azure Synapse Analytics","Azure Databricks"],
 "explanation":"SynapseとDatabricksは大規模分析向けです。Cache for Redisはキャッシュ、Bastionは安全なVM接続用で分析サービスではありません。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"大規模な構造化データに対し、MPP（並列処理）で高性能なデータウェアハウス分析を行うのに適すのはどれですか？",
 "options":["Synapseの専用SQLプール","Azure Cache for Redis","Azure Queue Storage","Azure Files"],"correct":["Synapseの専用SQLプール"],
 "explanation":"Synapseの専用SQLプールはMPPにより大規模な構造化データのデータウェアハウス分析を高性能に行えます。"},
{"area":D,"sub":"大規模分析の要素","type":"single",
 "q":"データレイクに最適な、列指向で圧縮効率の高い分析向けファイル形式はどれですか？",
 "options":["Parquet","CSV","JSON","XML"],"correct":["Parquet"],
 "explanation":"Parquetは列指向で圧縮・スキャン効率が高く、データレイクや大規模分析で標準的に使われる形式です。"},

# ---- リアルタイム分析 (8) ----
{"area":D,"sub":"リアルタイム分析","type":"single",
 "q":"一定量のデータをまとめて定期的に処理する方式を何と呼びますか？",
 "options":["バッチ処理","ストリーミング処理","トランザクション処理","正規化"],"correct":["バッチ処理"],
 "explanation":"バッチ処理はデータを一定量・一定期間ためてからまとめて処理する方式で、日次集計などに用いられます。"},
{"area":D,"sub":"リアルタイム分析","type":"single",
 "q":"データが生成されるそばから連続的に処理する方式を何と呼びますか？",
 "options":["ストリーミング処理","バッチ処理","正規化","インデックス作成"],"correct":["ストリーミング処理"],
 "explanation":"ストリーミング処理はデータが到着するそばから連続的に処理する方式で、リアルタイム分析に用いられます。"},
{"area":D,"sub":"リアルタイム分析","type":"single",
 "q":"バッチ処理とストリーミング処理の主な違いはどれですか？",
 "options":["バッチはまとめて、ストリーミングは到着次第逐次処理する","両者は同じ","ストリーミングは月次のみ","バッチはリアルタイム専用"],"correct":["バッチはまとめて、ストリーミングは到着次第逐次処理する"],
 "explanation":"バッチは一定量をためてまとめて処理し、ストリーミングはデータ到着のたびに低遅延で逐次処理します。"},
{"area":D,"sub":"リアルタイム分析","type":"single",
 "q":"流れてくるストリームデータをSQLライクなクエリでリアルタイムに分析するAzureサービスはどれですか？",
 "options":["Azure Stream Analytics","Azure Blob Storage","Azure SQL Database","Azure Data Factory"],"correct":["Azure Stream Analytics"],
 "explanation":"Azure Stream AnalyticsはIoTやイベントのストリームをSQLライクなクエリでリアルタイムに処理・集計するサービスです。"},
{"area":D,"sub":"リアルタイム分析","type":"single",
 "q":"大量のイベント/テレメトリを高スループットで取り込む、リアルタイム分析の入口となるAzureサービスはどれですか？",
 "options":["Azure Event Hubs","Azure Files","Azure Table Storage","Azure Backup"],"correct":["Azure Event Hubs"],
 "explanation":"Azure Event Hubsは毎秒大量のイベントを取り込めるストリーム取り込みサービスで、リアルタイム分析の入口になります。"},
{"area":D,"sub":"リアルタイム分析","type":"single",
 "q":"IoTデバイスとの双方向通信やデバイス管理に特化した、リアルタイムデータ取り込み向けサービスはどれですか？",
 "options":["Azure IoT Hub","Azure Blob Storage","Azure SQL Database","Azure Synapse"],"correct":["Azure IoT Hub"],
 "explanation":"Azure IoT Hubは多数のIoTデバイスとの安全な双方向通信・管理・テレメトリ取り込みを担い、リアルタイム分析に接続できます。"},
{"area":D,"sub":"リアルタイム分析","type":"single",
 "q":"リアルタイム分析が適するシナリオとして最も適切なものはどれですか？",
 "options":["センサーデータを即座に監視し異常を検知する","年に一度の決算集計のみ","静的な画像の長期保管","紙書類のスキャン保存のみ"],"correct":["センサーデータを即座に監視し異常を検知する"],
 "explanation":"リアルタイム分析はセンサーやログを即時に処理して異常検知・ダッシュボード更新・アラートを行う用途に適します。"},
{"area":D,"sub":"リアルタイム分析","type":"single",
 "q":"Microsoft Fabricでストリーミングデータの取り込み・分析をリアルタイムに扱うワークロードはどれですか？",
 "options":["リアルタイムインテリジェンス（Real-Time Intelligence）","データウェアハウスのみ","Power BIのみ","Blobの階層化のみ"],"correct":["リアルタイムインテリジェンス（Real-Time Intelligence）"],
 "explanation":"Fabricのリアルタイムインテリジェンスは、ストリーミングデータの取り込み・分析・可視化をリアルタイムに行うワークロードです。"},

# ---- Power BIによる可視化 (12) ----
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"データを集計・可視化してレポートやダッシュボードを作成するMicrosoftのBIツールはどれですか？",
 "options":["Power BI","Power Automate","Azure Data Factory","Azure Synapse"],"correct":["Power BI"],
 "explanation":"Power BIはデータに接続して可視化（グラフ・表・ダッシュボード）し、洞察を共有するBIツールです。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"レポートを作成・編集するためにPCにインストールして使うPower BIのアプリはどれですか？",
 "options":["Power BI Desktop","Power BI サービス（クラウド）","Power BI モバイル","オンプレミスデータゲートウェイ"],"correct":["Power BI Desktop"],
 "explanation":"Power BI Desktopはデータ接続・モデリング・レポート作成を行うWindows向け開発ツールです。共有はPower BIサービスで行います。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"作成したレポートを公開・共有し、ブラウザで閲覧・ダッシュボード化するPower BIの提供形態はどれですか？",
 "options":["Power BI サービス（クラウド）","Power BI Desktop のみ","Power Query のみ","DAX のみ"],"correct":["Power BI サービス（クラウド）"],
 "explanation":"Power BIサービスはレポートの公開・共有・ダッシュボード作成・コラボレーションを行うクラウドサービスです。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"時間の経過に伴う売上の推移など、連続的な傾向を示すのに最も適した可視化はどれですか？",
 "options":["折れ線グラフ","円グラフ","単一の数値カード","スライサー"],"correct":["折れ線グラフ"],
 "explanation":"折れ線グラフは時間など連続軸に沿った傾向・推移の表現に適します。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"カテゴリ間の値の大小を比較するのに最も適した可視化はどれですか？",
 "options":["棒グラフ（縦棒/横棒）","折れ線グラフ","マップ","単一の数値カード"],"correct":["棒グラフ（縦棒/横棒）"],
 "explanation":"棒グラフはカテゴリごとの数量の比較に適します。推移は折れ線、地理は地図が適します。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"全体に対する各部分の構成比（割合）を示すのに適した可視化はどれですか？",
 "options":["円グラフ／ドーナツグラフ","折れ線グラフ","散布図","ゲージ"],"correct":["円グラフ／ドーナツグラフ"],
 "explanation":"円・ドーナツグラフは全体に占める各カテゴリの割合（構成比）を示すのに適します（項目数が多いと見づらくなります）。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"地域ごとの売上を地図上に表現したい。適したPower BIの可視化はどれですか？",
 "options":["マップ（地図）ビジュアル","折れ線グラフ","テーブル","カード"],"correct":["マップ（地図）ビジュアル"],
 "explanation":"地理的な分布を示すにはマップ（地図）ビジュアルが適し、地域別の値を視覚的に把握できます。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"単一の重要指標（合計売上などのKPI実数値）を大きく1つだけ表示するのに適した可視化はどれですか？",
 "options":["カード","散布図","折れ線グラフ","ツリーマップ"],"correct":["カード"],
 "explanation":"カードビジュアルは合計売上などの単一の重要な数値を大きく表示するのに適します。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"Power BIのデータモデルで、複数テーブルを関連付ける仕組みを何と呼びますか？",
 "options":["リレーションシップ","ビジュアル","スライサー","テーマ"],"correct":["リレーションシップ"],
 "explanation":"Power BIのデータモデルではテーブル間にリレーションシップを定義して関連付け、横断的に集計・分析できます。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"Power BIのデータモデルで集計列やメジャーを定義するために使う数式言語はどれですか？",
 "options":["DAX","T-SQL","Power Fx","KQL"],"correct":["DAX"],
 "explanation":"DAX（Data Analysis Expressions）はPower BIのメジャーや計算列を定義するための数式言語です。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"レポート閲覧者が値を選んで全ビジュアルを対話的に絞り込めるフィルター用コントロールはどれですか？",
 "options":["スライサー","カード","テーマ","データゲートウェイ"],"correct":["スライサー"],
 "explanation":"スライサーは期間やカテゴリなどを選んでビジュアル全体を対話的に絞り込めるフィルターコントロールです。"},
{"area":D,"sub":"Power BIによる可視化","type":"single",
 "q":"Power BIでデータの取り込み時に整形・クレンジング（前処理）を行うために使うツールはどれですか？",
 "options":["Power Query","DAX","スライサー","データゲートウェイ"],"correct":["Power Query"],
 "explanation":"Power Queryはデータの接続・整形・クレンジング（ETL的な前処理）を行うツールで、Power BIに組み込まれています。DAXは集計式の言語です。"},
]
