# -*- coding: utf-8 -*-
"""AI-900 — コンピュータービジョン (22問)
出題範囲: CVソリューションの種別 / コンピュータービジョンのAzureサービス
名称: Azure AI Vision(Image Analysis/OCR=Read/キャプション), Azure AI Face,
      Azure AI Custom Vision, Azure AI Document Intelligence 等に統一。本番難度・詳細解説。
"""
AREA = "コンピュータービジョン"

QUESTIONS = [
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "画像全体が『何の画像か(例: 猫の写真)』を1つのラベルで判定するのは、どのCVソリューションですか？",
        "options": ["画像分類(image classification)", "物体検出(object detection)", "セマンティックセグメンテーション", "OCR(光学式文字認識)"],
        "correct": ["画像分類(image classification)"],
        "explanation": "画像“全体”に1つのカテゴリラベルを付けるのが『画像分類』。物体検出は対象の種類と“位置(枠)”を出す、セグメンテーションは画素単位の領域分け、OCRは文字の読み取りで、いずれも『全体に1ラベル』ではない。出力が『枠か/ラベルか/画素マスクか/文字か』で見分ける。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "1枚の画像内にある複数の対象について『種類』と『位置(枠)』を同時に求めるのは、どのソリューションですか？",
        "options": ["物体検出(object detection)", "画像分類(image classification)", "OCR(読み取り)", "画像キャプション生成"],
        "correct": ["物体検出(object detection)"],
        "explanation": "複数対象を『種類＋位置(バウンディングボックス)』で特定するのが『物体検出』。画像分類は位置を出さず全体に1ラベル、OCRは文字、キャプション生成は説明文の作成で、位置付きの検出ではない。『枠で位置を出す＝物体検出』が判別ポイント。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "印刷物や手書きの画像から文字を読み取ってテキスト化する技術を何と呼びますか？",
        "options": ["OCR(光学式文字認識)", "画像分類", "物体検出", "顔検出"],
        "correct": ["OCR(光学式文字認識)"],
        "explanation": "画像中の文字をテキストとして抽出するのが『OCR(光学式文字認識)』で、Azureでは Azure AI Vision の Read(読み取り)機能が担う。画像分類は画像全体のラベル付け、物体検出は対象の位置検出、顔検出は顔の有無/位置の特定で、文字の読み取りではない。OCRは『文字をテキスト化』に限定して捉える。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "画像内に人の顔があるか、またその位置(枠)を特定するのは、どのソリューションですか？",
        "options": ["顔検出(face detection)", "顔認識/本人照合(face recognition)", "画像分類", "OCR"],
        "correct": ["顔検出(face detection)"],
        "explanation": "顔の“有無と位置”を見つけるのが『顔検出』。『顔認識(本人照合)』は検出した顔が“誰か”を識別/照合する別工程で、混同に注意(本問は位置の特定なので検出)。画像分類は全体ラベル、OCRは文字で対象が異なる。検出=どこに顔があるか、認識=誰の顔か、と区別する。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "画像分類と物体検出の違いとして正しいものはどれですか？",
        "options": [
            "画像分類は画像全体に1ラベル、物体検出は対象ごとに種類と位置(枠)を返す",
            "画像分類は位置も返すが、物体検出はラベルのみ返す",
            "両者とも文字を読み取るOCRの一種である",
            "画像分類は動画専用、物体検出は静止画専用",
        ],
        "correct": ["画像分類は画像全体に1ラベル、物体検出は対象ごとに種類と位置(枠)を返す"],
        "explanation": "画像分類=画像全体に1つのラベル、物体検出=対象ごとに『種類＋位置(枠)』。残りは役割を逆にした/無関係な誤り。位置情報の有無が最大の違い。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "レシート画像から文字を読み取り、さらに『店名』『合計金額』などの“項目”として構造化したい。最適なのはどれですか？",
        "options": ["Azure AI Document Intelligence", "Azure AI Vision の Read(OCR)", "画像分類", "顔検出"],
        "correct": ["Azure AI Document Intelligence"],
        "explanation": "文字を読むだけでなく『どれが店名/合計か』という項目の意味づけ(構造化)まで行うのは『Azure AI Document Intelligence』。Azure AI VisionのRead(OCR)は文字を“テキストとして”読むが項目の意味づけはしない——この差が頻出ひっかけ。画像分類・顔検出は文字も項目も扱わない。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "顔の画像から年齢の推定や顔の属性などを分析するのは、どのソリューションに該当しますか？",
        "options": ["顔分析(顔の属性検出)", "OCR", "画像キャプション生成", "セマンティックセグメンテーション"],
        "correct": ["顔分析(顔の属性検出)"],
        "explanation": "顔の検出に加え、頭の向きや顔ランドマーク等の属性を分析するのは『顔分析』で、Azure AI Face や Azure AI Vision が提供する(年齢・感情等の一部属性は責任あるAIの観点で提供が制限される場合がある)。OCRは文字、キャプションは説明文、セグメンテーションは領域分けで顔属性の分析ではない。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "工場の製品写真を『良品/不良品』に判定したい。最も適したCVソリューションはどれですか？",
        "options": ["画像分類(必要なら独自学習)", "OCR", "顔検出", "画像キャプション生成"],
        "correct": ["画像分類(必要なら独自学習)"],
        "explanation": "画像全体を良品/不良品の2カテゴリに分けるのは『画像分類』。汎用モデルで足りなければ Azure AI Custom Vision で自社画像から専用の分類モデルを学習する。OCRは文字、顔検出は顔、キャプションは説明文生成で目的が違う。『全体を分類』なら画像分類、と捉える。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "棚の写真から、商品の種類ごとに位置を特定して個数を数えたい。最適なソリューションはどれですか？",
        "options": ["物体検出", "画像分類", "OCR", "画像キャプション生成"],
        "correct": ["物体検出"],
        "explanation": "個々の商品を位置(枠)付きで検出すれば、種類ごとの個数を数えられるため『物体検出』が最適。画像分類は全体に1ラベルしか付けられず個数は数えられない、OCRは文字、キャプションは説明文で不適。『位置を特定して数える=物体検出』。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "ナンバープレートの画像から番号(文字列)を読み取りたい。最適なソリューションはどれですか？",
        "options": ["OCR(Read)", "物体検出のみ", "画像分類", "顔検出"],
        "correct": ["OCR(Read)"],
        "explanation": "プレート上の“文字”を読み取るのは『OCR(Azure AI Vision の Read)』。物体検出はプレートの“位置”は出せても文字内容は読めない(実運用では検出で位置特定→OCRで読み取り、と組合せることもある)。画像分類・顔検出は文字読み取りではない。最終目的が『文字を得る』ならOCR。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "画像の内容を説明する短い文(キャプション)を自動生成する機能は、どのカテゴリに関係しますか？",
        "options": ["画像キャプション生成(image captioning)", "OCR", "セマンティックセグメンテーション", "顔照合"],
        "correct": ["画像キャプション生成(image captioning)"],
        "explanation": "画像を解析して説明文を作るのは『画像キャプション生成』で、Azure AI Vision の Image Analysis が提供する(タグ付けやオブジェクト抽出も同機能群)。OCRは文字、セグメンテーションは領域分け、顔照合は本人確認で、説明文の生成ではない。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "顔検出と顔認識(本人照合)の違いとして正しいものはどれですか？",
        "options": [
            "顔検出は顔の有無と位置を見つける、顔認識は検出した顔が“誰か”を識別/照合する",
            "顔検出は本人を特定し、顔認識は顔の位置だけを返す",
            "どちらも文字を読み取るOCRの一種である",
            "顔検出は動画専用、顔認識は静止画専用",
        ],
        "correct": ["顔検出は顔の有無と位置を見つける、顔認識は検出した顔が“誰か”を識別/照合する"],
        "explanation": "検出=顔の有無・位置の特定、認識(照合)=その顔が“誰か”を判定。役割を逆にしたものやOCRと混同したものは誤り。本人照合(認識)はプライバシー配慮や利用制限が伴う点も押さえておく。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "multi",
        "q": "コンピュータービジョンのソリューションに含まれるものを2つ選んでください。",
        "options": ["物体検出", "光学式文字認識(OCR)", "感情分析(テキスト)", "音声テキスト変換", "テキスト翻訳"],
        "correct": ["物体検出", "光学式文字認識(OCR)"],
        "explanation": "物体検出・OCRはいずれも画像を扱うコンピュータービジョン。テキストの感情分析や翻訳は自然言語処理(NLP=Azure AI Language/Translator)、音声テキスト変換は音声(Azure AI Speech)で、CVではない。入力メディア(画像/テキスト/音声)で分野を切り分ける。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "動画の各フレームから人物が映っている区間を見つけたい。基盤となるのはどのCV技術ですか？",
        "options": ["物体検出(各フレームに適用)", "OCR", "画像キャプション生成", "顔属性分析"],
        "correct": ["物体検出(各フレームに適用)"],
        "explanation": "動画はフレーム(静止画)の連続なので、各フレームに『物体検出(人物の検出)』を適用して人物の映る区間を特定するのが基盤。OCRは文字、キャプションは説明文、顔属性分析は顔の特徴分析で、人物の有無・位置の検出には物体検出が適する。動画解析もCVの静止画技術の応用で考える。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "画像分類・物体検出・OCR(Read)・画像キャプションなど、汎用の画像解析をまとめて提供するAzureサービスはどれですか？",
        "options": ["Azure AI Vision", "Azure AI Face", "Azure AI Document Intelligence", "Azure AI Language"],
        "correct": ["Azure AI Vision"],
        "explanation": "汎用の画像解析(タグ付け・キャプション・物体検出・OCR=Read 等)を提供するのが『Azure AI Vision』(旧 Computer Vision)。Azure AI Faceは顔特化、Azure AI Document Intelligenceは帳票の構造化抽出、Azure AI LanguageはNLPで対象が異なる。『汎用画像解析の入口=Azure AI Vision』。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "顔の検出・属性分析・本人照合(認識)に特化したAzureサービスはどれですか？",
        "options": ["Azure AI Face", "Azure AI Vision", "Azure AI Custom Vision", "Azure AI Document Intelligence"],
        "correct": ["Azure AI Face"],
        "explanation": "顔の検出・照合・属性に特化するのが『Azure AI Face』。Azure AI Visionは汎用画像解析(顔検出も一部可だが照合に特化はFace)、Custom Visionは独自画像モデルの学習、Document Intelligenceは帳票抽出で役割が違う。顔の本人照合のような用途は責任あるAIの観点で利用申請/制限がある点も関連知識。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "自社製品など独自の画像で学習させ、専用の画像分類/物体検出モデルを作れるAzureサービスはどれですか？",
        "options": ["Azure AI Custom Vision", "Azure AI Vision の既製モデル", "Azure AI Face", "Azure AI Document Intelligence"],
        "correct": ["Azure AI Custom Vision"],
        "explanation": "独自画像をアップロードして“自社専用”の分類/物体検出モデルを学習・公開できるのが『Azure AI Custom Vision』。Azure AI Visionの既製モデルは汎用で“自社固有カテゴリ”の学習はしない、Faceは顔特化、Document Intelligenceは帳票で目的が異なる。『独自データで学習＝Custom Vision』。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "領収書や請求書などの帳票から、項目を構造化データとして抽出するのに最適なAzureサービスはどれですか？",
        "options": ["Azure AI Document Intelligence", "Azure AI Vision", "Azure AI Custom Vision", "Azure AI Face"],
        "correct": ["Azure AI Document Intelligence"],
        "explanation": "帳票・フォームから『キーと値』やテーブルを構造化抽出する専用サービスが『Azure AI Document Intelligence』(旧 Form Recognizer)。Azure AI VisionのOCRは文字読み取りまで、Custom Visionは独自画像分類、Faceは顔で、項目の構造化抽出には向かない。『帳票の構造化＝Document Intelligence』。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "汎用の画像から文字を読み取る(OCR/Read)機能は、主にどのAzureサービスで提供されますか？",
        "options": ["Azure AI Vision", "Azure AI Language", "Azure AI Translator", "Azure AI Speech"],
        "correct": ["Azure AI Vision"],
        "explanation": "画像からの文字読み取り(OCR=Read)は『Azure AI Vision』の機能。Azure AI Languageはテキスト解析、Translatorは翻訳、Speechは音声で、画像からの文字抽出は扱わない。帳票の“項目化”が要るならDocument Intelligence、単に“文字を読む”ならVisionのRead、と使い分ける。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "来店者の顔を、登録済みの社員と照合して入退室を許可したい。最適なAzureサービスはどれですか？",
        "options": ["Azure AI Face", "Azure AI Vision", "Azure AI Custom Vision", "Azure AI Document Intelligence"],
        "correct": ["Azure AI Face"],
        "explanation": "登録済みの顔との“本人照合(認識)”を行うのは『Azure AI Face』。Azure AI Visionは汎用解析で本人照合に特化せず、Custom Visionは独自画像分類、Document Intelligenceは帳票で不適。顔照合は機微な用途のため、Microsoftの責任あるAI方針により利用申請・制限がある点も押さえる。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "限られた種類の自社部品を見分けるモデルを、少量の画像から手早く作りたい。最適なのはどれですか？",
        "options": ["Azure AI Custom Vision", "Azure AI Vision の汎用タグ付け", "Azure Machine Learning でゼロから深層学習", "Azure AI Document Intelligence"],
        "correct": ["Azure AI Custom Vision"],
        "explanation": "少量の独自画像から手早く専用の画像分類/検出モデルを作るには『Azure AI Custom Vision』が最適(転移学習で少データでも学習しやすい)。汎用タグ付けは自社固有カテゴリを学べない、Azure MLでゼロから深層学習は手間と専門性・データ量が大きい、Document Intelligenceは帳票用。手軽さと用途特化のバランスでCustom Visionを選ぶ。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "複数のAzure AIサービス(Vision・Language・Speechなど)を1つのキー/エンドポイントでまとめて利用したい。適切なのはどれですか？",
        "options": ["マルチサービスの Azure AI services リソース", "サービスごとに別々の単一サービスリソースのみ", "Azure AI Custom Vision", "Azure Machine Learning ワークスペース"],
        "correct": ["マルチサービスの Azure AI services リソース"],
        "explanation": "複数のAzure AIサービスを1つのリソース(キー/エンドポイント)で利用できるのが『マルチサービスの Azure AI services リソース』で、管理・課金を一元化できる。単一サービスリソースは1サービス専用、Custom Visionは画像特化、Azure MLは独自モデル開発基盤で、複数AIサービスの統合エンドポイントではない。Azure AI Foundry から各サービスを束ねて扱う構成にも通じる。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "multi",
        "q": "Azure AI Vision の画像分析が備える『特殊なドメインモデル(specialized domain models)』として用意されているものを2つ選んでください。",
        "options": ["有名人(celebrities)", "名所・ランドマーク(landmarks)", "動物の品種の血統", "車のナンバープレートの所有者", "植物の毒性"],
        "correct": ["有名人(celebrities)", "名所・ランドマーク(landmarks)"],
        "explanation": "Azure AI Vision には、汎用のタグ付けに加えて『有名人』『名所(ランドマーク)』を認識する特殊ドメインモデルが用意されている。動物の血統・ナンバープレート所有者・植物の毒性といった判定は標準では提供されない(プライバシーや専門性の観点でも非現実的)。Visionの既製機能の範囲を問う細部の問題。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "multi",
        "q": "Azure AI Vision が提供する画像系の機能として適切なものを2つ選んでください。",
        "options": ["光学式文字認識(OCR/Read)", "空間分析(spatial analysis)", "テキストの感情分析", "音声のリアルタイム文字起こし", "テキストの言語間翻訳"],
        "correct": ["光学式文字認識(OCR/Read)", "空間分析(spatial analysis)"],
        "explanation": "Azure AI Vision は画像・映像を対象に、文字読み取り(OCR/Read)や、空間内の人の位置・動き・人数などを解析する『空間分析(spatial analysis)』を提供する。テキストの感情分析・翻訳は Azure AI Language/Translator、音声の文字起こしは Azure AI Speech で、いずれも画像サービスの機能ではない。入力メディアで切り分ける。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "single",
        "q": "Azure AI Vision の画像説明(キャプション)生成で、返される各説明フレーズに付随する追加情報として正しいものはどれですか？",
        "options": ["信頼度スコア(confidence score)", "境界ボックスの座標", "リソースのエンドポイントURL", "サブスクリプションキー"],
        "correct": ["信頼度スコア(confidence score)"],
        "explanation": "画像キャプション生成では、各説明フレーズにモデルの確からしさを示す『信頼度スコア(0〜1)』が付与される。境界ボックスの座標は物体検出で返る情報、エンドポイントURLやキーは接続情報で、説明フレーズの付随情報ではない。多くのVision機能が結果に信頼度スコアを返す点も押さえる。",
    },
    {
        "area": AREA, "sub": "CVのAzureサービス", "type": "single",
        "q": "動画(映像)から人物が登場する場面・話者・キーワードなどを抽出してインデックス化するのに最も適したAzureサービスはどれですか？",
        "options": ["Azure AI Video Indexer", "Azure AI Custom Vision", "Azure AI Document Intelligence", "Azure AI Language"],
        "correct": ["Azure AI Video Indexer"],
        "explanation": "動画から顔・話者・音声テキスト・キーワード・シーン等を抽出してインデックス化(検索可能化)するのは『Azure AI Video Indexer』。Custom Visionは独自画像分類/検出、Document Intelligenceは帳票、Languageはテキスト解析で、動画の総合インデックス化には向かない。動画＝Video Indexer、と結びつける。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "multi",
        "q": "次のうちコンピュータービジョンのタスクを3つ選んでください。",
        "options": ["画像分類", "物体検出", "光学式文字認識(OCR)", "テキストの感情分析", "テキストの言語間翻訳"],
        "correct": ["画像分類", "物体検出", "光学式文字認識(OCR)"],
        "explanation": "画像分類・物体検出・OCRはいずれも画像を扱うコンピュータービジョンのタスク。テキストの感情分析・翻訳はNLP(Azure AI Language/Translator)で、画像を扱わない。入力が画像ならCV、テキストならNLP、と切り分ける。",
    },
    {
        "area": AREA, "sub": "CVソリューションの種別", "type": "multi",
        "q": "顔に関するコンピュータービジョン処理として適切なものを2つ選んでください。",
        "options": ["顔検出(顔の有無と位置)", "顔認識(本人照合)", "テキストの要約", "音声の文字起こし", "数値の異常検知"],
        "correct": ["顔検出(顔の有無と位置)", "顔認識(本人照合)"],
        "explanation": "顔検出(顔の有無・位置の特定)と顔認識(その顔が誰かを照合)はいずれも顔に関するCV処理で、Azure AI Face 等が担う。テキスト要約はNLP、文字起こしは音声、異常検知は数値データで、顔の処理ではない。検出=どこに顔があるか、認識=誰の顔か、の区別もあわせて押さえる。",
    },
]
