# -*- coding: utf-8 -*-
# コンピュータービジョン (22問)
C = "コンピュータービジョン"
AC = [
# ---- CVソリューションの種別 (14) ----
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"画像全体が『何の画像か（例: 猫の写真）』を1つのラベルで判定するのは、どのCVソリューションですか？",
 "options":["画像分類","物体検出","OCR","顔検出"],"correct":["画像分類"],
 "explanation":"画像分類は画像全体にカテゴリラベルを付与します。位置まで特定するのは物体検出です。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"1枚の画像の中にある複数の対象の『種類』と『位置（枠）』を同時に求めるのは、どのソリューションですか？",
 "options":["物体検出","画像分類","OCR","感情分析"],"correct":["物体検出"],
 "explanation":"物体検出は各対象のクラスとバウンディングボックス（位置）を返します。画像分類は全体ラベルのみです。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"印刷物や手書きの画像から文字を読み取ってテキスト化する技術を何と呼びますか？",
 "options":["光学文字認識（OCR）","物体検出","画像分類","クラスタリング"],"correct":["光学文字認識（OCR）"],
 "explanation":"OCR（Optical Character Recognition）は画像中の文字を抽出してテキスト化します。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"画像内に人の顔があるかどうか、またその位置を特定するのは、どのソリューションですか？",
 "options":["顔検出","画像分類","OCR","異常検知"],"correct":["顔検出"],
 "explanation":"顔検出は画像内の顔の有無と位置を特定します。さらに属性分析や照合を行う顔分析・顔認識もあります。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"画像分類と物体検出の違いとして正しいものはどれですか？",
 "options":["分類は画像全体に1ラベル、検出は複数対象の種類と位置を返す","両者は同じ","物体検出は位置を返さない","画像分類は文字を読み取る"],"correct":["分類は画像全体に1ラベル、検出は複数対象の種類と位置を返す"],
 "explanation":"画像分類は画像全体のカテゴリ、物体検出は対象ごとのクラスと位置（枠）を返します。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"レシートの画像から文字を読み取り、さらに『店名』『合計金額』などの項目として構造化するのは、何と呼ばれる処理ですか？",
 "options":["ドキュメントインテリジェンス（OCR＋項目抽出）","画像分類","顔認識","クラスタリング"],"correct":["ドキュメントインテリジェンス（OCR＋項目抽出）"],
 "explanation":"単に文字を読むOCRに加え、項目を構造化抽出するのはドキュメントインテリジェンス（旧Form Recognizer）です。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"顔の画像から年齢の推定や表情などの属性を分析するのは、どのソリューションに該当しますか？",
 "options":["顔分析（Facial analysis）","OCR","画像分類のみ","物体検出のみ"],"correct":["顔分析（Facial analysis）"],
 "explanation":"顔分析は顔の検出に加えて、属性（年齢推定、眼鏡の有無など）を分析します。本人照合は顔認識です。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"工場の製品写真を『良品/不良品』に判定したい。最も適したCVソリューションはどれですか？",
 "options":["画像分類","OCR","顔検出","音声認識"],"correct":["画像分類"],
 "explanation":"画像全体を良品/不良品の2カテゴリに判定するのは画像分類が適します。位置特定が要るなら物体検出です。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"棚の写真から商品の個数を、種類ごとに位置を特定して数えたい。最適なソリューションはどれですか？",
 "options":["物体検出","画像分類","OCR","感情分析"],"correct":["物体検出"],
 "explanation":"対象ごとに位置を特定して数えるには物体検出が適します。画像全体ラベルの画像分類では個数や位置は分かりません。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"ナンバープレートの画像から番号を読み取りたい。最適なソリューションはどれですか？",
 "options":["OCR","画像分類","顔検出","クラスタリング"],"correct":["OCR"],
 "explanation":"画像中の文字（番号）を読み取るのはOCRが適します。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"画像の内容を説明する短い文（キャプション）を自動生成する機能は、どのカテゴリに関係しますか？",
 "options":["画像キャプション（イメージ分析）","OCR","顔認識","異常検知"],"correct":["画像キャプション（イメージ分析）"],
 "explanation":"画像の内容を説明するキャプション生成は、Azure AI Visionのイメージ分析機能の一つです。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"顔検出と顔認識（本人照合）の違いとして正しいものはどれですか？",
 "options":["検出は顔の有無・位置、認識はそれが誰かを照合する","両者は同じ","顔認識は位置だけを返す","顔検出は名前を返す"],"correct":["検出は顔の有無・位置、認識はそれが誰かを照合する"],
 "explanation":"顔検出は顔の有無と位置を特定し、顔認識（照合）は登録済みの人物と一致するかを判定します。"},
{"area":C,"sub":"CVソリューションの種別","type":"multi",
 "q":"コンピュータービジョンのソリューションに含まれるものを2つ選んでください。",
 "options":["画像分類","物体検出","感情分析","キーフレーズ抽出"],"correct":["画像分類","物体検出"],
 "explanation":"画像分類・物体検出・OCR・顔検出はコンピュータービジョンです。感情分析やキーフレーズ抽出はNLPのワークロードです。"},
{"area":C,"sub":"CVソリューションの種別","type":"single",
 "q":"動画の各フレームから人物が映っている区間を見つけたい。基盤となるのはどのCV技術ですか？",
 "options":["物体検出／顔検出","OCR","画像キャプションのみ","回帰"],"correct":["物体検出／顔検出"],
 "explanation":"映像中の人物の有無や位置を見つけるには物体検出や顔検出が使われます。OCRは文字読み取り用です。"},

# ---- CVのAzureサービス (8) ----
{"area":C,"sub":"CVのAzureサービス","type":"single",
 "q":"画像分類・物体検出・OCR・画像キャプションなどを提供するAzureのサービスはどれですか？",
 "options":["Azure AI Vision","Azure AI Language","Azure AI Speech","Azure Machine Learning デザイナー"],"correct":["Azure AI Vision"],
 "explanation":"Azure AI Vision（旧Computer Vision）は、画像分析・OCR・キャプションなどコンピュータービジョン機能を提供します。"},
{"area":C,"sub":"CVのAzureサービス","type":"single",
 "q":"顔の検出・属性分析・本人照合に特化したAzureのサービスはどれですか？",
 "options":["Azure AI Face","Azure AI Vision のOCRのみ","Azure AI Language","Azure OpenAI"],"correct":["Azure AI Face"],
 "explanation":"Azure AI Face（Face service）は、顔検出・顔属性分析・顔照合（認識）に特化したサービスです。"},
{"area":C,"sub":"CVのAzureサービス","type":"single",
 "q":"独自の画像で学習させて、自社製品専用の画像分類・物体検出モデルを作れる機能はどれですか？",
 "options":["Custom Vision","OCRの既定モデルのみ","感情分析","音声合成"],"correct":["Custom Vision"],
 "explanation":"Custom Visionは、利用者が用意した画像でカスタムの画像分類・物体検出モデルを学習・公開できる機能です。"},
{"area":C,"sub":"CVのAzureサービス","type":"single",
 "q":"領収書や請求書など帳票から構造化データを抽出するのに最適なAzureサービスはどれですか？",
 "options":["Azure AI Document Intelligence","Azure AI Speech","Azure AI Vision のキャプション","Azure OpenAI"],"correct":["Azure AI Document Intelligence"],
 "explanation":"Azure AI Document Intelligence（旧Form Recognizer）は帳票から項目を構造化抽出します。汎用OCRはAI Visionにもあります。"},
{"area":C,"sub":"CVのAzureサービス","type":"single",
 "q":"汎用の画像から文字を読み取る（OCR）機能は、主にどのAzureサービスで提供されますか？",
 "options":["Azure AI Vision","Azure AI Language","Azure AI Speech","Azure Machine Learning"],"correct":["Azure AI Vision"],
 "explanation":"汎用OCR（Readなど）はAzure AI Visionが提供します。帳票特化の抽出はDocument Intelligenceです。"},
{"area":C,"sub":"CVのAzureサービス","type":"single",
 "q":"来店者の顔を登録済みの社員と照合して入退室を許可したい。最適なAzureサービスはどれですか？",
 "options":["Azure AI Face","Azure AI Language","Custom Visionの画像分類","Azure AI Speech"],"correct":["Azure AI Face"],
 "explanation":"顔の本人照合（認識）はAzure AI Faceが適します。画像分類のCustom Visionでは個人の照合はできません。"},
{"area":C,"sub":"CVのAzureサービス","type":"single",
 "q":"自社の限られた種類の部品画像を見分けるモデルを、少量の画像から手早く作りたい。最適なのはどれですか？",
 "options":["Custom Vision","Azure AI Face","Azure AI Language","Azure AI Speech"],"correct":["Custom Vision"],
 "explanation":"独自カテゴリの画像分類・物体検出を少量データで作るにはCustom Visionが適します。"},
{"area":C,"sub":"CVのAzureサービス","type":"single",
 "q":"複数のAzure AIサービス（Vision・Language・Speechなど）を1つのキーとエンドポイントでまとめて利用できるリソースはどれですか？",
 "options":["Azure AI services（マルチサービス）リソース","Azure Storage アカウント","Azure SQL Database","Azure Key Vault のみ"],"correct":["Azure AI services（マルチサービス）リソース"],
 "explanation":"Azure AI services（マルチサービス）リソースは、複数のAIサービスを単一のキー/エンドポイントで利用できるようにします。"},
]
