# -*- coding: utf-8 -*-
# 自然言語処理（NLP） (24問)
D = "自然言語処理（NLP）"
AD = [
# ---- NLPワークロードのシナリオ (16) ----
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"レビュー文が肯定的か否定的かを数値スコアで判定する処理を何と呼びますか？",
 "options":["感情分析（センチメント分析）","キーフレーズ抽出","エンティティ認識","翻訳"],"correct":["感情分析（センチメント分析）"],
 "explanation":"感情分析は文章の肯定的/否定的/中立といった感情の傾向をスコアで判定します。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"長い文章から要点となる重要な語句を自動で抜き出す処理を何と呼びますか？",
 "options":["キーフレーズ抽出","感情分析","翻訳","音声合成"],"correct":["キーフレーズ抽出"],
 "explanation":"キーフレーズ抽出は、文章の中心的な語句を抽出して要点把握を助けます。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"文章中の『人名・地名・組織名・日付』などを識別してタグ付けする処理を何と呼びますか？",
 "options":["エンティティ認識（NER）","感情分析","音声認識","画像分類"],"correct":["エンティティ認識（NER）"],
 "explanation":"エンティティ認識（Named Entity Recognition）は、文中の固有表現（人名・地名・日付など）を識別・分類します。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"日本語の文章を英語に変換する処理は、どのNLPシナリオに該当しますか？",
 "options":["翻訳","感情分析","キーフレーズ抽出","エンティティ認識"],"correct":["翻訳"],
 "explanation":"ある言語から別言語へ変換するのは翻訳です。Azure AI Translatorが該当サービスです。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"音声（話し声）をテキストに変換する処理を何と呼びますか？",
 "options":["音声認識（Speech to Text）","音声合成（Text to Speech）","翻訳","感情分析"],"correct":["音声認識（Speech to Text）"],
 "explanation":"音声をテキスト化するのは音声認識（Speech to Text）です。逆にテキストを読み上げるのは音声合成です。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"テキストを自然な話し声で読み上げる処理を何と呼びますか？",
 "options":["音声合成（Text to Speech）","音声認識","エンティティ認識","翻訳"],"correct":["音声合成（Text to Speech）"],
 "explanation":"テキストを音声に変換して読み上げるのは音声合成（Text to Speech）です。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"問い合わせ文から『ユーザーが何をしたいか（意図）』と『その対象（エンティティ）』を読み取り、適切な処理に振り分けたい。最適なNLP機能はどれですか？",
 "options":["言語理解（意図・エンティティの抽出）","音声合成","キーフレーズ抽出のみ","翻訳"],"correct":["言語理解（意図・エンティティの抽出）"],
 "explanation":"会話文から意図（インテント）とエンティティを抽出するのは言語理解（CLU/会話言語理解）で、ボットなどに使われます。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"感情分析の典型的な用途として最も適切なものはどれですか？",
 "options":["SNS投稿の評判（ポジ/ネガ）を集計してブランド評価を把握する","画像から物体を検出する","音声を文字起こしする","帳票から金額を抽出する"],"correct":["SNS投稿の評判（ポジ/ネガ）を集計してブランド評価を把握する"],
 "explanation":"感情分析は口コミやSNSの評判分析に使われます。画像・音声・帳票は別ワークロードです。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"問い合わせメールから『顧客名』『注文番号』『日付』を自動で取り出したい。最適なNLP機能はどれですか？",
 "options":["エンティティ認識","感情分析","音声合成","翻訳"],"correct":["エンティティ認識"],
 "explanation":"固有表現（人名・番号・日付）の抽出はエンティティ認識が適します。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"次のうち『言語モデリング』に最も関係するものはどれですか？",
 "options":["文脈から次に来る語の確率を学習し文章を扱う","画像の物体を検出する","音声の音量を測る","数値の外れ値を見つける"],"correct":["文脈から次に来る語の確率を学習し文章を扱う"],
 "explanation":"言語モデリングは語の並びの確率を学習し、文章の理解・生成の基盤になります（大規模言語モデルも含む）。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"会議の録音から議事メモを作る場合、まず最初に必要となるNLP処理はどれですか？",
 "options":["音声認識（文字起こし）","音声合成","物体検出","画像分類"],"correct":["音声認識（文字起こし）"],
 "explanation":"録音から文字起こしする音声認識がまず必要です。その後に要約やキーフレーズ抽出を行えます。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"多言語のレビューを、まず英語に統一してから感情分析したい。最初に行う処理はどれですか？",
 "options":["翻訳","音声合成","OCR","クラスタリング"],"correct":["翻訳"],
 "explanation":"言語を統一するにはまず翻訳を行い、その後に感情分析を適用します。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"multi",
 "q":"自然言語処理（NLP）のワークロードに含まれるものを2つ選んでください。",
 "options":["感情分析","キーフレーズ抽出","物体検出","画像分類"],"correct":["感情分析","キーフレーズ抽出"],
 "explanation":"感情分析・キーフレーズ抽出・エンティティ認識・翻訳・音声認識はNLPです。物体検出や画像分類はコンピュータービジョンです。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"音声認識と音声合成の違いとして正しいものはどれですか？",
 "options":["認識は音声→テキスト、合成はテキスト→音声","両者は同じ","合成は音声→テキスト","認識はテキスト→音声"],"correct":["認識は音声→テキスト、合成はテキスト→音声"],
 "explanation":"音声認識（Speech to Text）は音声をテキストに、音声合成（Text to Speech）はテキストを音声に変換します。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"コールセンターの問い合わせを内容カテゴリ（請求・解約・故障など）に自動分類したい。最適なNLP機能はどれですか？",
 "options":["テキスト分類（カスタム）","音声合成","OCR","物体検出"],"correct":["テキスト分類（カスタム）"],
 "explanation":"テキストを定義済みカテゴリに振り分けるのはテキスト分類です。Azure AI Languageのカスタムテキスト分類で実現できます。"},
{"area":D,"sub":"NLPワークロードのシナリオ","type":"single",
 "q":"翻訳ワークロードの典型的な用途として最も適切なものはどれですか？",
 "options":["多言語のWebサイトやチャットをリアルタイムに相互変換する","画像から顔を検出する","数値を回帰で予測する","帳票から金額を抽出する"],"correct":["多言語のWebサイトやチャットをリアルタイムに相互変換する"],
 "explanation":"翻訳は多言語コンテンツや会話の相互変換に使われます。他は別ワークロードです。"},

# ---- NLPのAzureサービス (8) ----
{"area":D,"sub":"NLPのAzureサービス","type":"single",
 "q":"感情分析・キーフレーズ抽出・エンティティ認識・言語検出などをまとめて提供するAzureサービスはどれですか？",
 "options":["Azure AI Language","Azure AI Vision","Azure AI Speech","Azure OpenAI"],"correct":["Azure AI Language"],
 "explanation":"Azure AI Languageは、感情分析・キーフレーズ抽出・エンティティ認識・会話言語理解・質問応答などのテキスト系機能を提供します。"},
{"area":D,"sub":"NLPのAzureサービス","type":"single",
 "q":"音声認識（Speech to Text）・音声合成（Text to Speech）・音声翻訳を提供するAzureサービスはどれですか？",
 "options":["Azure AI Speech","Azure AI Language","Azure AI Vision","Azure AI Document Intelligence"],"correct":["Azure AI Speech"],
 "explanation":"Azure AI Speechは音声認識・音声合成・音声翻訳・話者認識などの音声系機能を提供します。"},
{"area":D,"sub":"NLPのAzureサービス","type":"single",
 "q":"テキストの言語間翻訳に特化したAzureサービスはどれですか？",
 "options":["Azure AI Translator","Azure AI Vision","Azure AI Face","Azure Machine Learning"],"correct":["Azure AI Translator"],
 "explanation":"Azure AI Translatorは多言語のテキスト翻訳に特化したサービスです。音声翻訳はAI Speechと連携します。"},
{"area":D,"sub":"NLPのAzureサービス","type":"single",
 "q":"よくある質問（FAQ）から自然言語の質問に回答するボットを作りたい。Azure AI Languageのどの機能が適しますか？",
 "options":["質問応答（Question Answering）","音声合成","物体検出","回帰"],"correct":["質問応答（Question Answering）"],
 "explanation":"質問応答（Question Answering）は、ナレッジベースから自然言語の質問に答える機能で、FAQボットに使えます。"},
{"area":D,"sub":"NLPのAzureサービス","type":"single",
 "q":"チャットボットでユーザー発話の意図とエンティティを抽出したい。Azure AI Languageのどの機能ですか？",
 "options":["会話言語理解（CLU）","音声合成","OCR","感情分析のみ"],"correct":["会話言語理解（CLU）"],
 "explanation":"会話言語理解（Conversational Language Understanding）は、発話から意図（インテント）とエンティティを抽出します。"},
{"area":D,"sub":"NLPのAzureサービス","type":"single",
 "q":"会議音声をリアルタイムに文字起こししたい。最適なAzureサービスはどれですか？",
 "options":["Azure AI Speech","Azure AI Language","Azure AI Vision","Azure AI Translator"],"correct":["Azure AI Speech"],
 "explanation":"リアルタイム音声認識（文字起こし）はAzure AI Speechが担います。テキスト解析はAI Languageです。"},
{"area":D,"sub":"NLPのAzureサービス","type":"single",
 "q":"顧客レビュー（テキスト）の感情を分析したい。最適なAzureサービスはどれですか？",
 "options":["Azure AI Language","Azure AI Speech","Azure AI Vision","Azure AI Face"],"correct":["Azure AI Language"],
 "explanation":"テキストの感情分析はAzure AI Languageが提供します。音声や画像は別サービスです。"},
{"area":D,"sub":"NLPのAzureサービス","type":"single",
 "q":"Azure AI LanguageとAzure AI Speechの役割の違いとして正しいものはどれですか？",
 "options":["Languageはテキスト解析、Speechは音声の認識・合成","両者は同じ","Speechはテキスト翻訳専用","Languageは画像分析専用"],"correct":["Languageはテキスト解析、Speechは音声の認識・合成"],
 "explanation":"Azure AI Languageはテキスト系、Azure AI Speechは音声系の機能を提供します。"},
]
