# -*- coding: utf-8 -*-
"""AI-900 — 自然言語処理(NLP) (24問)
出題範囲: NLPワークロードのシナリオ / NLPのAzureサービス
名称: Azure AI Language(感情分析/キーフレーズ/エンティティ/言語検出/CLU=会話言語理解/
      カスタム質問応答), Azure AI Speech, Azure AI Translator に統一。本番難度・詳細解説。
"""
AREA = "自然言語処理（NLP）"

QUESTIONS = [
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "レビュー文が肯定的か否定的かを、スコア付きで判定する処理を何と呼びますか？",
        "options": ["感情分析(sentiment analysis)", "キーフレーズ抽出", "エンティティ認識", "言語検出"],
        "correct": ["感情分析(sentiment analysis)"],
        "explanation": "文章の肯定/否定/中立を判定するのが『感情分析』。キーフレーズ抽出は重要語句の抜き出し、エンティティ認識は人名・地名等の識別、言語検出は何語かの判定で、感情の判定ではない。いずれも Azure AI Language の機能なので、機能名と“何を出力するか”を結びつけて覚える。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "長い文章から要点となる重要語句を自動で抜き出す処理を何と呼びますか？",
        "options": ["キーフレーズ抽出", "感情分析", "エンティティ認識", "翻訳"],
        "correct": ["キーフレーズ抽出"],
        "explanation": "文章の主要トピックを表す語句を抽出するのが『キーフレーズ抽出』。感情分析は肯定/否定、エンティティ認識は固有名詞等の識別、翻訳は言語変換で目的が異なる。要約に近い“重要語句の抜き出し”はキーフレーズ抽出と捉える。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "文章中の『人名・地名・組織名・日付』などを識別してタグ付けする処理を何と呼びますか？",
        "options": ["エンティティ認識(NER)", "キーフレーズ抽出", "感情分析", "言語検出"],
        "correct": ["エンティティ認識(NER)"],
        "explanation": "テキスト中の固有表現(人名・地名・組織・日付・数量等)を識別・分類するのが『固有表現認識(NER: named entity recognition)』。キーフレーズ抽出は重要語句、感情分析は肯定/否定、言語検出は言語判定で異なる。NERは“何が”どの種類かをタグ付けする点が特徴。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "日本語の文章を英語に変換する処理は、どのNLPシナリオに該当しますか？",
        "options": ["機械翻訳", "感情分析", "キーフレーズ抽出", "音声合成"],
        "correct": ["機械翻訳"],
        "explanation": "言語間でテキストを変換するのは『機械翻訳』で、Azureでは Azure AI Translator が担う。感情分析・キーフレーズ抽出はテキスト解析、音声合成はテキスト→音声で、言語変換ではない。『言語A→言語B＝翻訳(Translator)』。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "話し声(音声)をテキストに変換する処理を何と呼びますか？",
        "options": ["音声テキスト変換(speech to text)", "テキスト音声変換(text to speech)", "翻訳", "感情分析"],
        "correct": ["音声テキスト変換(speech to text)"],
        "explanation": "音声→テキストは『音声テキスト変換(speech to text)』で Azure AI Speech が提供。逆のテキスト→音声は『テキスト音声変換(text to speech)』。翻訳は言語変換、感情分析はテキスト解析で別物。変換の向き(音声→テキストか/テキスト→音声か)を取り違えない。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "テキストを自然な話し声で読み上げる処理を何と呼びますか？",
        "options": ["テキスト音声変換(text to speech)", "音声テキスト変換(speech to text)", "言語検出", "翻訳"],
        "correct": ["テキスト音声変換(text to speech)"],
        "explanation": "テキスト→音声(読み上げ)は『テキスト音声変換(text to speech)』で Azure AI Speech の機能。音声テキスト変換は逆方向、言語検出は何語かの判定、翻訳は言語変換で異なる。読み上げ＝TTS、書き起こし＝STT、と対で覚える。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "問い合わせ文から『ユーザーが何をしたいか(意図)』と『その対象(エンティティ)』を読み取る処理は、Azure AI Language のどの機能ですか？",
        "options": ["会話言語理解(CLU)", "感情分析", "カスタム質問応答", "翻訳"],
        "correct": ["会話言語理解(CLU)"],
        "explanation": "発話から“意図(intent)”と“エンティティ”を抽出するのは『会話言語理解(CLU: conversational language understanding)』で、旧 LUIS の後継。感情分析は肯定/否定、カスタム質問応答(旧 QnA Maker)はFAQ応答、翻訳は言語変換で目的が異なる。チャットボットの自然言語理解の中核がCLU。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "感情分析の典型的な用途として最も適切なものはどれですか？",
        "options": [
            "SNSや商品レビューの大量の声から肯定的/否定的な傾向を把握する",
            "請求書から金額や日付を項目として抽出する",
            "画像内の物体の位置を枠で検出する",
            "音声をリアルタイムに文字起こしする",
        ],
        "correct": ["SNSや商品レビューの大量の声から肯定的/否定的な傾向を把握する"],
        "explanation": "感情分析は、レビュー・SNS・問い合わせなど大量テキストの肯定/否定傾向を把握する用途に向く(VOC分析等)。請求書の項目抽出はDocument Intelligence、物体の枠検出はコンピュータービジョン、文字起こしはAzure AI Speechで、いずれも感情分析の用途ではない。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "問い合わせメールから『顧客名』『注文番号』『日付』を自動で取り出したい。最適なNLP処理はどれですか？",
        "options": ["エンティティ認識(必要ならカスタムNER)", "感情分析", "翻訳", "音声合成"],
        "correct": ["エンティティ認識(必要ならカスタムNER)"],
        "explanation": "テキストから氏名・番号・日付などの項目を識別・抽出するのは『エンティティ認識(NER)』で、独自項目なら Azure AI Language のカスタムNERを学習する。感情分析は肯定/否定、翻訳は言語変換、音声合成は読み上げで、項目抽出ではない。なお“帳票画像”からの抽出ならDocument Intelligence、“テキスト”からの抽出はNER、という切り分けも重要。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "次のうち『言語モデリング(language modeling)』に最も関係するものはどれですか？",
        "options": [
            "文脈から次に来る語の確率を学習し、文章生成や理解の基盤とする",
            "画像内の物体を枠で検出する",
            "数値データの外れ値を検出する",
            "帳票から金額を構造化抽出する",
        ],
        "correct": ["文脈から次に来る語の確率を学習し、文章生成や理解の基盤とする"],
        "explanation": "言語モデリングは、文脈から次語の確率分布を学習し、文章理解・生成の基盤となる技術で、LLM(大規模言語モデル)もこの延長にある。物体検出はCV、外れ値検出は異常検知、帳票抽出はDocument Intelligenceで、言語モデリングとは無関係。生成AIの土台が言語モデルである点を押さえる。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "会議の録音から議事メモを作る場合、まず最初に必要となるNLP/音声処理はどれですか？",
        "options": ["音声テキスト変換(文字起こし)", "感情分析", "翻訳", "テキスト音声変換"],
        "correct": ["音声テキスト変換(文字起こし)"],
        "explanation": "音声から始まるので、まず『音声テキスト変換(文字起こし)』でテキスト化する必要がある(その後に要約・キーフレーズ抽出等を行う)。感情分析・翻訳はテキスト化後の処理、テキスト音声変換は逆方向。処理の“順序”(音声→テキスト→解析)を問う問題。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "多言語のレビューを、まず英語に統一してから感情分析したい。最初に行う処理はどれですか？",
        "options": ["翻訳", "感情分析", "キーフレーズ抽出", "言語検出のみ"],
        "correct": ["翻訳"],
        "explanation": "『まず英語に統一』なので、最初の処理は『翻訳(Azure AI Translator)』。その後に感情分析を行う。言語検出は“何語か”を判定するだけで英語化はしない。処理の順序(翻訳→感情分析)と各機能の役割を区別する。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "multi",
        "q": "自然言語処理(NLP)のワークロードに含まれるものを2つ選んでください。",
        "options": ["感情分析", "機械翻訳", "物体検出", "画像分類", "異常検知"],
        "correct": ["感情分析", "機械翻訳"],
        "explanation": "感情分析・機械翻訳はテキストを扱うNLP。物体検出・画像分類は画像(コンピュータービジョン)、異常検知は数値データの外れ値検出で、NLPではない。入力が“言語(テキスト)”ならNLP、と切り分ける。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "音声認識(speech to text)と音声合成(text to speech)の違いとして正しいものはどれですか？",
        "options": [
            "音声認識は音声→テキスト、音声合成はテキスト→音声",
            "音声認識はテキスト→音声、音声合成は音声→テキスト",
            "どちらも言語間の翻訳を行う",
            "どちらも画像から文字を読み取る",
        ],
        "correct": ["音声認識は音声→テキスト、音声合成はテキスト→音声"],
        "explanation": "音声認識(STT)=音声→テキスト、音声合成(TTS)=テキスト→音声。向きを逆にしたもの、翻訳やOCRと混同したものは誤り。どちらも Azure AI Speech が提供する。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "コールセンターの問い合わせを『請求・解約・故障』などの内容カテゴリに自動分類したい。最適なNLP処理はどれですか？",
        "options": ["テキスト分類(必要ならカスタムテキスト分類)", "感情分析", "翻訳", "音声合成"],
        "correct": ["テキスト分類(必要ならカスタムテキスト分類)"],
        "explanation": "テキストを所定カテゴリへ振り分けるのは『テキスト分類』で、独自カテゴリなら Azure AI Language のカスタムテキスト分類を学習する。感情分析は肯定/否定の判定であってカテゴリ分類ではない(紛らわしい)、翻訳・音声合成は別目的。『内容で振り分け＝テキスト分類』。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "翻訳ワークロードの典型的な用途として最も適切なものはどれですか？",
        "options": [
            "多言語のWebサイトやドキュメントを別言語へ変換して提供する",
            "レビューの肯定/否定を判定する",
            "音声を文字起こしする",
            "画像から物体を検出する",
        ],
        "correct": ["多言語のWebサイトやドキュメントを別言語へ変換して提供する"],
        "explanation": "翻訳(Azure AI Translator)は、文章やドキュメントを別言語へ変換する用途に用いる。肯定/否定判定は感情分析、文字起こしはAzure AI Speech、物体検出はコンピュータービジョンで、翻訳の用途ではない。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "感情分析・キーフレーズ抽出・エンティティ認識・言語検出などをまとめて提供するAzureサービスはどれですか？",
        "options": ["Azure AI Language", "Azure AI Speech", "Azure AI Translator", "Azure AI Vision"],
        "correct": ["Azure AI Language"],
        "explanation": "テキスト解析(感情分析・キーフレーズ・NER・言語検出・CLU・カスタム質問応答等)を束ねるのが『Azure AI Language』(旧 Text Analytics/LUIS/QnA Maker を統合)。Speechは音声、Translatorは翻訳、Visionは画像で対象が異なる。『テキストの意味解析の入口＝Azure AI Language』。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "音声認識(STT)・音声合成(TTS)・音声翻訳などを提供するAzureサービスはどれですか？",
        "options": ["Azure AI Speech", "Azure AI Language", "Azure AI Translator", "Azure AI Document Intelligence"],
        "correct": ["Azure AI Speech"],
        "explanation": "音声に関する機能(STT・TTS・音声翻訳・話者認識等)を提供するのが『Azure AI Speech』。Languageはテキスト解析、Translatorはテキスト翻訳、Document Intelligenceは帳票で、音声処理は扱わない。『音声＝Speech』。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "テキストの言語間翻訳に特化したAzureサービスはどれですか？",
        "options": ["Azure AI Translator", "Azure AI Language", "Azure AI Speech", "Azure AI Vision"],
        "correct": ["Azure AI Translator"],
        "explanation": "テキスト/ドキュメントの言語間翻訳に特化するのが『Azure AI Translator』。Languageは感情分析等のテキスト解析、Speechは音声、Visionは画像で役割が違う。なお音声を直接翻訳する“音声翻訳”はAzure AI Speechが担う点も区別しておく。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "よくある質問(FAQ)に対し、自然言語の質問へ回答するボットを作りたい。Azure AI Language のどの機能を使いますか？",
        "options": ["カスタム質問応答(custom question answering)", "会話言語理解(CLU)", "感情分析", "キーフレーズ抽出"],
        "correct": ["カスタム質問応答(custom question answering)"],
        "explanation": "FAQやナレッジから質問応答ボットを作るのは『カスタム質問応答』(旧 QnA Maker)。CLUは“意図とエンティティ”の抽出で、応答そのものの生成ではない(両者を組み合わせることもある)。感情分析・キーフレーズ抽出は別機能。『FAQ応答＝カスタム質問応答』『意図抽出＝CLU』を区別する。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "チャットボットで、ユーザー発話の『意図』と『エンティティ』を抽出したい。Azure AI Language のどの機能ですか？",
        "options": ["会話言語理解(CLU)", "カスタム質問応答", "言語検出", "翻訳"],
        "correct": ["会話言語理解(CLU)"],
        "explanation": "発話から意図(intent)とエンティティを抽出するのは『会話言語理解(CLU)』(旧 LUIS の後継)。カスタム質問応答はFAQ応答、言語検出は言語判定、翻訳は言語変換で目的が異なる。CLU＝自然言語理解(意図/エンティティ)、と覚える。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "会議音声をリアルタイムに文字起こししたい。最適なAzureサービスはどれですか？",
        "options": ["Azure AI Speech", "Azure AI Language", "Azure AI Translator", "Azure AI Vision の OCR"],
        "correct": ["Azure AI Speech"],
        "explanation": "音声のリアルタイム文字起こし(STT)は『Azure AI Speech』。Languageはテキスト解析、Translatorは翻訳、VisionのOCRは画像中の文字でいずれも音声は扱わない。入力が音声ならSpeech、画像中の文字ならVisionのOCR、と入力で切り分ける。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "顧客レビュー(テキスト)の感情を分析したい。最適なAzureサービスはどれですか？",
        "options": ["Azure AI Language", "Azure AI Speech", "Azure AI Translator", "Azure AI Document Intelligence"],
        "correct": ["Azure AI Language"],
        "explanation": "テキストの感情分析は『Azure AI Language』の機能。Speechは音声、Translatorは翻訳、Document Intelligenceは帳票で対象が異なる。テキストの意味解析(感情・キーフレーズ・NER等)はLanguageに集約されている。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "Azure AI Language と Azure AI Speech の役割の違いとして正しいものはどれですか？",
        "options": [
            "Languageはテキストの解析・理解、Speechは音声の認識・合成を担う",
            "Languageは音声処理、Speechはテキスト解析を担う",
            "どちらも画像から物体を検出する",
            "どちらも帳票から項目を抽出する",
        ],
        "correct": ["Languageはテキストの解析・理解、Speechは音声の認識・合成を担う"],
        "explanation": "Azure AI Languageは“テキスト”の解析・理解(感情・NER・CLU・質問応答等)、Azure AI Speechは“音声”の認識(STT)・合成(TTS)・音声翻訳。役割を逆にした記述や、画像・帳票と混同した記述は誤り。扱うメディア(テキスト/音声)で区別する。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "multi",
        "q": "Azure AI Language の言語検出(language detection)が各テキストに対して返す値として適切なものを3つ選んでください。",
        "options": ["言語名", "ISO 639-1 言語コード", "信頼度スコア", "境界ボックスの座標", "Wikipedia の URL"],
        "correct": ["言語名", "ISO 639-1 言語コード", "信頼度スコア"],
        "explanation": "言語検出は『言語名(例: English)』『ISO 639-1コード(例: en)』『信頼度スコア(0〜1)』を返す。境界ボックスは物体検出(画像)、Wikipedia URLはエンティティリンク(別機能)の情報で、言語検出の戻り値ではない。3つの戻り値をセットで覚える。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "single",
        "q": "Azure AI Language の言語検出で、対象テキストの言語を判定できない(あいまい/不明な)場合に返される結果として正しいものはどれですか？",
        "options": ["言語名は(Unknown)、信頼度スコアは NaN となる", "エラーで処理が必ず停止する", "自動的に英語(English)とみなされる", "最も近い言語コードが必ず1つ返る"],
        "correct": ["言語名は(Unknown)、信頼度スコアは NaN となる"],
        "explanation": "言語を特定できない場合、言語検出は言語名を『(Unknown)』、スコアを『NaN(非数)』として返す。処理が必ず停止する・英語と決め打つ・必ず1言語を返す、は誤り。不明時の戻り値(Unknown / NaN)を問う細かい論点で、公式練習問題でも出題される。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "multi",
        "q": "Azure AI Language の会話言語理解(CLU)のアプリモデルを構成する主要なスキーマ要素を2つ選んでください。",
        "options": ["意図(intents)", "エンティティ(entities)", "境界ボックス", "信頼度のしきい値設定UI", "音声フォント"],
        "correct": ["意図(intents)", "エンティティ(entities)"],
        "explanation": "CLU(旧LUIS)のモデルは『意図(ユーザーが何をしたいか)』と『エンティティ(その対象の情報)』を主要スキーマとして定義し、発話(utterances)例で学習する。境界ボックスは画像、音声フォントはTTSの概念で無関係。CLU＝意図＋エンティティ、を押さえる。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "multi",
        "q": "Azure AI Speech の音声テキスト変換で使われる『汎用(ユニバーサル)言語モデル』が最適化されている利用シナリオを2つ選んでください。",
        "options": ["対話(conversational)", "ディクテーション(dictation)", "音楽の採譜", "話者の年齢推定", "画像内文字の読み取り"],
        "correct": ["対話(conversational)", "ディクテーション(dictation)"],
        "explanation": "音声テキスト変換の汎用モデルは『対話(会話)』と『ディクテーション(口述筆記)』のシナリオに最適化されている。音楽の採譜・話者の年齢推定・画像内文字読み取りは音声テキスト変換の対象外。必要に応じてカスタム音声モデルで特定領域に適応させることもできる。",
    },
    {
        "area": AREA, "sub": "NLPシナリオ", "type": "single",
        "q": "『飛行機』より『花』と『植物』が互いに近い値になるよう、単語に数値ベクトルを割り当てて意味的な近さを表すNLP手法はどれですか？",
        "options": ["ベクトル化(単語埋め込み)", "頻度分析", "N-グラム", "レンマ化(見出し語化)"],
        "correct": ["ベクトル化(単語埋め込み)"],
        "explanation": "意味の近い単語が近いベクトルになるよう数値表現を与えるのが『ベクトル化(単語埋め込み/embeddings)』。頻度分析は出現回数の集計、N-グラムは連続するn語の組、レンマ化は語を見出し語に正規化する処理で、いずれも“意味的な近さをベクトルで表す”ものではない。埋め込みは検索・分類・RAGの基盤。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "multi",
        "q": "Azure AI Language が提供する機能を3つ選んでください。",
        "options": ["感情分析", "エンティティ認識(NER)", "キーフレーズ抽出", "画像分類", "音声合成(TTS)"],
        "correct": ["感情分析", "エンティティ認識(NER)", "キーフレーズ抽出"],
        "explanation": "感情分析・エンティティ認識・キーフレーズ抽出はテキスト解析で Azure AI Language の機能。画像分類は Azure AI Vision、音声合成は Azure AI Speech で、テキスト解析サービスの機能ではない。Languageはテキスト、と入力メディアで切り分ける。",
    },
    {
        "area": AREA, "sub": "NLPのAzureサービス", "type": "multi",
        "q": "Azure AI Speech が提供する音声の機能を2つ選んでください。",
        "options": ["音声テキスト変換(STT)", "テキスト音声変換(TTS)", "テキストの感情分析", "画像からの文字読み取り(OCR)", "帳票からの項目抽出"],
        "correct": ["音声テキスト変換(STT)", "テキスト音声変換(TTS)"],
        "explanation": "音声を扱う Azure AI Speech の機能は音声テキスト変換(STT)とテキスト音声変換(TTS)(ほかに音声翻訳・話者認識)。感情分析はLanguage、OCRはVision、帳票抽出はDocument Intelligenceで、音声サービスの機能ではない。『音声＝Speech』。",
    },
]
