# -*- coding: utf-8 -*-
# 生成AI (28問)
E = "生成AI"
AE = [
# ---- 生成AIソリューションの特徴 (16) ----
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIの特徴として最も適切なものはどれですか？",
 "options":["学習した内容をもとに新しいコンテンツ（文章・画像等）を生成する","数値の外れ値だけを検出する","データを単に分類する","データを物理的に保存するだけ"],"correct":["学習した内容をもとに新しいコンテンツ（文章・画像等）を生成する"],
 "explanation":"生成AIはプロンプトに応じて新しい文章・画像・コードなどを生成します。分類や異常検知とは目的が異なります。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"自然言語のテキストを生成・理解する大規模なモデルを何と呼びますか？",
 "options":["大規模言語モデル（LLM）","回帰モデル","クラスタリングモデル","決定木"],"correct":["大規模言語モデル（LLM）"],
 "explanation":"LLM（Large Language Model）は大量テキストで学習し、文章生成・要約・翻訳などを行う生成AIの中核です。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIに与える指示文を何と呼びますか？",
 "options":["プロンプト","ラベル","エンティティ","エポック"],"correct":["プロンプト"],
 "explanation":"プロンプトは生成AIへの入力指示です。プロンプトの工夫（プロンプトエンジニアリング）で出力品質が変わります。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIが事実と異なるもっともらしい内容を生成してしまう現象を何と呼びますか？",
 "options":["ハルシネーション（幻覚）","オーバーフィッティング","クラスタリング","正規化"],"correct":["ハルシネーション（幻覚）"],
 "explanation":"ハルシネーションは、生成AIが事実に反するもっともらしい出力を生む現象です。出力の検証が重要です。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"テキストの説明から画像を生成するモデルの例として適切なものはどれですか？",
 "options":["DALL·E（画像生成モデル）","線形回帰","k-meansクラスタリング","OCRエンジン"],"correct":["DALL·E（画像生成モデル）"],
 "explanation":"DALL·Eはテキストから画像を生成する生成AIモデルです。回帰やクラスタリングは生成AIではありません。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIの一般的な活用シナリオとして最も適切なものはどれですか？",
 "options":["メールやレポートのドラフト作成、要約、コード補完","画像から顔の位置を特定する","数値の回帰予測","帳票から項目を抽出する"],"correct":["メールやレポートのドラフト作成、要約、コード補完"],
 "explanation":"生成AIは文章作成・要約・翻訳・コード生成・対話などに広く使われます。他は別ワークロードです。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIに渡す文章を、モデルが扱える小さな単位に分割したものを何と呼びますか？",
 "options":["トークン","ラベル","ピクセル","クラスタ"],"correct":["トークン"],
 "explanation":"トークンは単語や部分文字列などの処理単位で、入力・出力の量や課金の基準にもなります。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIの回答の根拠として、社内文書など独自データを検索して与え、正確性を高める手法を何と呼びますか？",
 "options":["グラウンディング／RAG（検索拡張生成）","クラスタリング","データラベル付け","次元削減"],"correct":["グラウンディング／RAG（検索拡張生成）"],
 "explanation":"RAG（Retrieval-Augmented Generation）は、関連文書を検索してプロンプトに与え、根拠に基づく回答（グラウンディング）を実現します。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIにおける責任あるAIの配慮として最も適切なものはどれですか？",
 "options":["有害な出力の抑制（コンテンツフィルター）や出力の検証を行う","学習を必ず停止する","プロンプトを暗号化することのみ","常に出力を信頼して検証しない"],"correct":["有害な出力の抑制（コンテンツフィルター）や出力の検証を行う"],
 "explanation":"生成AIではコンテンツフィルターによる有害出力の抑制、ハルシネーション対策、出力の人による検証などが重要です。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"既存の基盤モデルを、自社データで追加学習して特定用途に適応させることを何と呼びますか？",
 "options":["ファインチューニング","クラスタリング","OCR","正規化"],"correct":["ファインチューニング"],
 "explanation":"ファインチューニングは、事前学習済みモデルを独自データで追加学習し、特定タスクへ適応させる手法です。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"モデルへの指示で、出力の形式や役割・制約をあらかじめ与える文を何と呼びますか？",
 "options":["システムメッセージ（システムプロンプト）","ラベル","エンティティ","特徴量"],"correct":["システムメッセージ（システムプロンプト）"],
 "explanation":"システムメッセージは、モデルの役割・トーン・制約を設定する指示で、出力の方向付けに使います。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"テキスト・画像・音声など複数種類の入力を扱えるモデルを何と呼びますか？",
 "options":["マルチモーダルモデル","線形回帰モデル","クラスタリングモデル","決定木"],"correct":["マルチモーダルモデル"],
 "explanation":"マルチモーダルモデルは、テキストだけでなく画像や音声など複数のモダリティを入力・処理できます（例: GPT-4o）。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"プロンプトに数例の入力と出力を示して、望む形式の回答を引き出す手法を何と呼びますか？",
 "options":["フューショット（few-shot）プロンプト","クラスタリング","ファインチューニングのみ","正規化"],"correct":["フューショット（few-shot）プロンプト"],
 "explanation":"フューショットは、プロンプト内に少数の例を示してモデルの出力を誘導する手法です。例なしはゼロショットです。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"multi",
 "q":"生成AIの一般的な活用シナリオを2つ選んでください。",
 "options":["文章の要約","コードの生成・補完","数値の外れ値検出","画像内の顔位置の特定"],"correct":["文章の要約","コードの生成・補完"],
 "explanation":"要約やコード生成は生成AIの代表的用途です。外れ値検出は異常検知、顔位置特定はコンピュータービジョンです。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIの出力品質を上げるために、指示を具体的にしたり例や制約を与えたりする取り組みを何と呼びますか？",
 "options":["プロンプトエンジニアリング","データ正規化","クラスタリング","次元削減"],"correct":["プロンプトエンジニアリング"],
 "explanation":"プロンプトエンジニアリングは、指示の具体化・例示・役割設定などで出力品質を高める取り組みです。"},
{"area":E,"sub":"生成AIソリューションの特徴","type":"single",
 "q":"生成AIを業務利用する際の注意点として最も適切なものはどれですか？",
 "options":["出力に誤り（ハルシネーション）がある前提で人が確認する","出力は常に正しいので検証不要","個人情報をそのまま無制限に入力してよい","著作権は一切考慮しなくてよい"],"correct":["出力に誤り（ハルシネーション）がある前提で人が確認する"],
 "explanation":"生成AIは誤りを含み得るため人による確認が必要で、機密情報の扱いや著作権・公平性などの配慮も求められます。"},

# ---- 生成AIのAzureサービスと機能 (12) ----
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"GPTなどのOpenAIモデルを、Azureのセキュリティとガバナンスのもとで利用できるサービスはどれですか？",
 "options":["Azure OpenAI Service","Azure AI Vision","Azure AI Speech","Azure Machine Learning デザイナー"],"correct":["Azure OpenAI Service"],
 "explanation":"Azure OpenAI Serviceは、GPTやDALL·EなどのOpenAIモデルをAzureの企業向けセキュリティ・コンプライアンスのもとで提供します。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"生成AIアプリの開発・評価・デプロイを統合的に行えるMicrosoftのプラットフォームはどれですか？",
 "options":["Azure AI Foundry","Azure AI Vision","Azure AI Speech","Azure SQL Database"],"correct":["Azure AI Foundry"],
 "explanation":"Azure AI Foundry（旧Azure AI Studio）は、モデルの選択・プロンプト設計・評価・デプロイなど生成AI開発を統合する基盤です。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"GPT・Llama・Phiなど多数の基盤モデルを比較・選択してデプロイできる、Azure AI Foundryの機能はどれですか？",
 "options":["モデルカタログ","OCR","顔検出","データラベル付け"],"correct":["モデルカタログ"],
 "explanation":"Azure AI Foundryのモデルカタログは、Microsoft・OpenAI・オープンソースなど多様な基盤モデルを探索・比較・デプロイできます。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"Azure OpenAIで提供される、テキストから画像を生成するモデルはどれですか？",
 "options":["DALL·E","Whisperの文字起こしのみ","Azure AI Faceの照合","回帰モデル"],"correct":["DALL·E"],
 "explanation":"Azure OpenAIではGPT系（テキスト）に加え、DALL·E（画像生成）やWhisper（音声認識）などのモデルも利用できます。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"Azure OpenAI Serviceを使う主な利点として最も適切なものはどれですか？",
 "options":["企業向けのセキュリティ・ネットワーク制御・責任あるAI機能のもとでOpenAIモデルを使える","モデルが必ず無料になる","出力が必ず正確になる","インターネットが不要になる"],"correct":["企業向けのセキュリティ・ネットワーク制御・責任あるAI機能のもとでOpenAIモデルを使える"],
 "explanation":"Azure OpenAIは、企業のセキュリティ・コンプライアンス・コンテンツフィルター等を備えてOpenAIモデルを提供します。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"自社ドキュメントを根拠に回答する社内チャットを、Azure OpenAIで作るときに用いる代表的な構成はどれですか？",
 "options":["独自データ検索＋生成（RAG/オンユアデータ）","画像分類","音声合成のみ","回帰モデル"],"correct":["独自データ検索＋生成（RAG/オンユアデータ）"],
 "explanation":"Azure OpenAIの『データ追加（On Your Data）』やAI Searchと組み合わせたRAGで、社内文書を根拠にした回答を生成できます。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"Azure OpenAIのコンテンツフィルターの役割として正しいものはどれですか？",
 "options":["有害・不適切な入出力を検出して抑制する","モデルの精度を100%にする","学習データを暗号化する","トークン数を無制限にする"],"correct":["有害・不適切な入出力を検出して抑制する"],
 "explanation":"コンテンツフィルターは、暴力・ヘイト・性的・自傷などの有害カテゴリを検出し、入出力を抑制して安全性を高めます。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"Azure AI Foundryが生成AI開発で提供する価値として最も適切なものはどれですか？",
 "options":["モデル選択・プロンプト管理・評価・デプロイを一元化できる","物理サーバーを販売する","SQLのインデックスを作る","顔の本人照合を行う"],"correct":["モデル選択・プロンプト管理・評価・デプロイを一元化できる"],
 "explanation":"Azure AI Foundryは、生成AIアプリのモデル選定からプロンプト設計・評価・デプロイ・監視までを統合的に扱えます。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"Microsoft 365のアプリ内で文書作成やメール下書きを支援する生成AIアシスタントはどれですか？",
 "options":["Microsoft 365 Copilot","Azure AI Face","Custom Vision","Azure AI Translator"],"correct":["Microsoft 365 Copilot"],
 "explanation":"Microsoft 365 Copilotは、Word・Outlook・TeamsなどM365アプリに統合された生成AIアシスタントです。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"音声をテキストに書き起こすOpenAIのモデルで、Azure OpenAIでも利用できるものはどれですか？",
 "options":["Whisper","DALL·E","GPT-4の画像生成","Azure AI Faceの照合"],"correct":["Whisper"],
 "explanation":"WhisperはOpenAIの音声認識モデルで、Azure OpenAIから利用でき、多言語の文字起こしに使えます。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"独自データを根拠にした回答を作る際、関連文書の検索基盤としてよく組み合わせるAzureサービスはどれですか？",
 "options":["Azure AI Search","Azure AI Face","Azure AI Speech のみ","Azure SQL のみ"],"correct":["Azure AI Search"],
 "explanation":"Azure AI Search（旧Cognitive Search）はRAG構成で関連文書を検索する基盤として広く使われます。"},
{"area":E,"sub":"生成AIのAzureサービスと機能","type":"single",
 "q":"Azure OpenAI ServiceとオープンなOpenAI APIの主な違いとして適切なものはどれですか？",
 "options":["Azure版は企業向けの認証・ネットワーク制御・コンプライアンスがAzure基盤で提供される","モデルの中身が全く別物である","Azure版は生成AIではない","Azure版はテキストを扱えない"],"correct":["Azure版は企業向けの認証・ネットワーク制御・コンプライアンスがAzure基盤で提供される"],
 "explanation":"Azure OpenAIは同等のモデルを、Azureの認証(Entra ID)・仮想ネットワーク・コンプライアンス・コンテンツフィルター等の企業向け基盤で利用できる点が特徴です。"},
]
