# -*- coding: utf-8 -*-
# Azureのアーキテクチャとサービス (48問) — 本番難度版
B = "Azureのアーキテクチャとサービス"
QB = [
# ---- コアアーキテクチャコンポーネント (12) ----
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"関連するリソースをまとめて管理・削除できる論理コンテナーはどれですか？",
 "options":["リソースグループ","管理グループ","サブスクリプション","可用性ゾーン"],"correct":["リソースグループ"],
 "explanation":"リソースグループは関連リソースをまとめる論理コンテナーで、グループ単位で展開・管理・削除・権限付与ができます。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"複数のサブスクリプションにポリシーやアクセスをまとめて適用する上位階層はどれですか？",
 "options":["管理グループ","リソースグループ","可用性ゾーン","テナント"],"correct":["管理グループ"],
 "explanation":"管理グループはサブスクリプションの上位階層で、複数サブスクリプションにポリシーやRBACをまとめて適用できます。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"Azureの課金とリソース管理の境界となる単位はどれですか？",
 "options":["サブスクリプション","リソースグループ","管理グループ","リージョン"],"correct":["サブスクリプション"],
 "explanation":"サブスクリプションは課金と管理の境界です。組織はこれを分けてコスト・権限・クォータを区切ります。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"同一リージョン内で、独立した電源・冷却・ネットワークを持つ物理的に分離した場所を何と呼びますか？",
 "options":["可用性ゾーン","リージョンペア","可用性セット","リソースグループ"],"correct":["可用性ゾーン"],
 "explanation":"可用性ゾーンはリージョン内で物理的に分離されたデータセンター群です。可用性セットは同一データセンター内での障害/更新ドメイン分散で、範囲が異なります。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"地理的に離れたリージョン同士が組になり、計画メンテナンスや広域災害復旧に使われる仕組みはどれですか？",
 "options":["リージョンペア","可用性ゾーン","エッジゾーン","可用性セット"],"correct":["リージョンペア"],
 "explanation":"リージョンペアは離れた2リージョンの組で、計画更新は片方ずつ行われ、広域災害時の復旧にも利用されます。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"管理グループ・サブスクリプション・リソースグループ・リソースの正しい階層（上位→下位）はどれですか？",
 "options":["管理グループ → サブスクリプション → リソースグループ → リソース","サブスクリプション → 管理グループ → リソースグループ → リソース","リソースグループ → サブスクリプション → 管理グループ → リソース","管理グループ → リソースグループ → サブスクリプション → リソース"],"correct":["管理グループ → サブスクリプション → リソースグループ → リソース"],
 "explanation":"上位から管理グループ、サブスクリプション、リソースグループ、リソースの順で、上位の設定は下位に継承されます。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"Azureの「リージョン」を最もよく説明しているものはどれですか？",
 "options":["低遅延ネットワークで結ばれた1つ以上のデータセンターからなる地理的エリア","単一のサーバーラック","課金の境界となる単位","リソースをまとめる論理コンテナー"],"correct":["低遅延ネットワークで結ばれた1つ以上のデータセンターからなる地理的エリア"],
 "explanation":"リージョンは1つ以上のデータセンターからなる地理的エリアです。課金境界はサブスクリプション、論理コンテナーはリソースグループです。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"特定国の法令やデータ主権要件に対応するために分離された特別なリージョンを何と呼びますか？",
 "options":["ソブリン（主権）リージョン","可用性ゾーン","リージョンペア","エッジゾーン"],"correct":["ソブリン（主権）リージョン"],
 "explanation":"ソブリンリージョン（Azure GovernmentやAzure Chinaなど）は、特定国の規制やデータ主権要件を満たすために分離された環境です。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"Azureのデータセンターについて正しい説明はどれですか？",
 "options":["サーバー等を収容する物理施設で、リージョンや可用性ゾーンを構成する","利用者が個別に購入する仮想マシン","課金を管理する論理単位","ネットワークの暗号化方式"],"correct":["サーバー等を収容する物理施設で、リージョンや可用性ゾーンを構成する"],
 "explanation":"データセンターは物理施設で、複数が集まってリージョンや可用性ゾーンを構成します。利用者が直接データセンターを選ぶことはできません。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"単一データセンターの障害に耐えるため、同一リージョン内でVMを分散配置する仕組みはどれですか？",
 "options":["可用性ゾーンへの分散配置","リソースグループの分割","タグの付与","管理グループの追加"],"correct":["可用性ゾーンへの分散配置"],
 "explanation":"可用性ゾーンは物理的に分離されているため、ゾーンをまたいでVMを配置するとデータセンター単位の障害から保護できます。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"リージョンペアにおける計画メンテナンスの取り扱いとして正しいものはどれですか？",
 "options":["原則としてペアの片方ずつ順番に実施される","両方同時に実施される","メンテナンスは行われない","利用者が手動で実施する"],"correct":["原則としてペアの片方ずつ順番に実施される"],
 "explanation":"リージョンペアでは計画更新が片側ずつ行われるため、もう一方は稼働を維持でき可用性が保たれます。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"single",
 "q":"Azureにおける「リソース」とは何を指しますか？",
 "options":["VM・ストレージ・データベースなど作成・管理できる個々のサービスインスタンス","サブスクリプションの請求書","リージョンの一覧","管理者ユーザーのアカウント"],"correct":["VM・ストレージ・データベースなど作成・管理できる個々のサービスインスタンス"],
 "explanation":"リソースはVM・ストレージ・データベースなど、作成・管理できる個々のサービスインスタンスで、リソースグループにまとめられます。"},

# ---- コンピューティングとネットワーク (16) ----
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"フルマネージドでWebアプリやAPIをホストできるPaaSサービスはどれですか？",
 "options":["Azure App Service","Azure Virtual Machines","Azure Kubernetes Service","Azure Functions"],"correct":["Azure App Service"],
 "explanation":"App ServiceはWebアプリ/APIをホストするPaaSです。AKSはコンテナーオーケストレーション、Functionsはイベント駆動の関数で目的が異なります。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"イベント駆動で短時間のコードを実行する、サーバーレスのコンピューティングサービスはどれですか？",
 "options":["Azure Functions","Azure App Service","Azure Kubernetes Service","Azure Batch"],"correct":["Azure Functions"],
 "explanation":"Functionsはイベントに応じてコードを実行するサーバーレスで、実行時のみ課金されます。App ServiceはWebホスティング、Batchは大規模並列処理です。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"コンテナー化アプリを大規模にオーケストレーションするマネージドサービスはどれですか？",
 "options":["Azure Kubernetes Service（AKS）","Azure Container Instances","Azure App Service","Azure Functions"],"correct":["Azure Kubernetes Service（AKS）"],
 "explanation":"AKSは多数のコンテナーのデプロイ・スケール・管理を自動化します。単一コンテナーを手軽に動かすにはAzure Container Instancesが適します。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"クラウド上にWindowsのデスクトップとアプリをVDIとして提供するサービスはどれですか？",
 "options":["Azure Virtual Desktop","Azure App Service","Azure Functions","Azure Bastion"],"correct":["Azure Virtual Desktop"],
 "explanation":"Azure Virtual Desktop（AVD）はクラウドでWindowsデスクトップ/アプリを仮想化提供します。Bastionはポータル経由の安全なVM接続用です。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"同一構成のVMを多数まとめて負荷に応じ自動スケールできるサービスはどれですか？",
 "options":["仮想マシンスケールセット","可用性セット","Azure Container Instances","Azure Functions"],"correct":["仮想マシンスケールセット"],
 "explanation":"スケールセット（VMSS）は同一構成のVM群を自動的に増減します。可用性セットは障害/更新ドメイン分散が目的でスケールはしません。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"Azure内の仮想ネットワーク同士をAzureバックボーン経由で直接接続する機能はどれですか？",
 "options":["VNetピアリング","VPN Gateway","ExpressRoute","Application Gateway"],"correct":["VNetピアリング"],
 "explanation":"VNetピアリングはVNet同士を低遅延・高帯域なAzureバックボーンで接続します。VPN Gateway/ExpressRouteはオンプレミスとの接続用です。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"オンプレミスとAzureをインターネットを経由せず専用線で接続するサービスはどれですか？",
 "options":["ExpressRoute","VPN Gateway","VNetピアリング","Azure Firewall"],"correct":["ExpressRoute"],
 "explanation":"ExpressRouteは通信事業者の専用接続でAzureに接続し、インターネットを経由しないため高信頼・低遅延・高セキュリティです。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"暗号化トンネルでインターネット越しにオンプレミスとAzureを接続する方法はどれですか？",
 "options":["VPN Gateway（サイト間VPN）","ExpressRoute","VNetピアリング","Load Balancer"],"correct":["VPN Gateway（サイト間VPN）"],
 "explanation":"VPN GatewayはIPsec/IKEで暗号化トンネルを張り接続します。専用線不要で導入しやすい一方、帯域や遅延はインターネット品質に依存します。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"オーケストレーターを使わず単一のコンテナーを手早く実行したい。最適なサービスはどれですか？",
 "options":["Azure Container Instances（ACI）","Azure Kubernetes Service","Azure Virtual Machines","Azure App Service"],"correct":["Azure Container Instances（ACI）"],
 "explanation":"ACIはオーケストレーター不要で単一コンテナーを迅速に起動できます。大規模オーケストレーションが必要ならAKSを使います。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"VM・コンテナー・関数（Functions）の比較として正しいものはどれですか？",
 "options":["関数は最も抽象度が高く管理不要、VMは最も制御範囲が広い","VMはサーバーレスで管理不要","コンテナーはVMより常に高コスト","関数は長時間バッチに最適"],"correct":["関数は最も抽象度が高く管理不要、VMは最も制御範囲が広い"],
 "explanation":"VMは制御範囲が広い反面管理負担が大きく、コンテナーは可搬性が高く、関数は管理不要で短時間のイベント処理に向きます。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"Azure仮想マシンを作成する際に通常あわせて必要となるリソースの組み合わせはどれですか？",
 "options":["仮想ネットワーク・ネットワークインターフェイス・ディスク","料金計算ツール・タグ・ポリシー","管理グループ・サブスクリプション・予算","DNSゾーン・ロードバランサー・WAF"],"correct":["仮想ネットワーク・ネットワークインターフェイス・ディスク"],
 "explanation":"VMにはOS/データ用ディスク、ネットワークインターフェイス（NIC）、接続先のVNetなどが必要です。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"複数のVMを同一データセンター内で障害ドメイン・更新ドメインに分散し、ハードウェア障害や更新時の同時停止を避ける仕組みはどれですか？",
 "options":["可用性セット","可用性ゾーン","スケールセット","リージョンペア"],"correct":["可用性セット"],
 "explanation":"可用性セットはVMを障害/更新ドメインに分散します。可用性ゾーンはデータセンター単位の分離で、保護の範囲が異なります。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"独自ドメインの名前解決（DNSレコードのホスティング）を行えるAzureサービスはどれですか？",
 "options":["Azure DNS","Azure Firewall","Azure Bastion","Azure DDoS Protection"],"correct":["Azure DNS"],
 "explanation":"Azure DNSはドメインのDNSレコードをAzure上でホスティングし名前解決を提供します。他はファイアウォール・接続・DDoS対策です。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"パブリックエンドポイントとプライベートエンドポイントの違いとして正しいものはどれですか？",
 "options":["プライベートエンドポイントはVNet内の非公開IPでサービスへ接続する","パブリックエンドポイントはインターネットから到達できない","両者に違いはない","プライベートエンドポイントはインターネット公開専用"],"correct":["プライベートエンドポイントはVNet内の非公開IPでサービスへ接続する"],
 "explanation":"プライベートエンドポイントはVNet内のプライベートIPで接続しトラフィックを外部に出しません。パブリックはインターネット経由でアクセスします。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"single",
 "q":"仮想ネットワーク（VNet）内をさらに分割し、用途ごとにリソースを分けてネットワーク制御を行う単位はどれですか？",
 "options":["サブネット","リソースグループ","管理グループ","可用性ゾーン"],"correct":["サブネット"],
 "explanation":"サブネットはVNetのアドレス空間を分割した単位で、用途ごとにリソースを分けてセキュリティやルーティングを制御します。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"multi",
 "q":"Azureでアプリケーションをホストする手段として適切なものを2つ選んでください。",
 "options":["Azure App Service（Web Apps）","仮想マシン（コンテナーやVM上のアプリ）","Azure Policy","Microsoft Entra ID"],"correct":["Azure App Service（Web Apps）","仮想マシン（コンテナーやVM上のアプリ）"],
 "explanation":"アプリのホスティングにはWeb Apps、コンテナー、仮想マシンなどが使えます。Azure Policyはガバナンス、Entra IDはID管理でホスティング手段ではありません。"},

# ---- ストレージ (10) ----
{"area":B,"sub":"ストレージ","type":"single",
 "q":"画像・動画・バックアップなどの非構造化オブジェクトの保存に最適なストレージはどれですか？",
 "options":["Blob Storage","Azure Files","Queue Storage","Table Storage"],"correct":["Blob Storage"],
 "explanation":"Blob Storageは非構造化データ（オブジェクト）の格納に最適化されています。Filesは共有ファイル、Queueはメッセージ、Tableはキー値です。"},
{"area":B,"sub":"ストレージ","type":"single",
 "q":"SMB/NFSでマウントして共有フォルダーのように使えるマネージドファイル共有はどれですか？",
 "options":["Azure Files","Blob Storage","Disk Storage","Table Storage"],"correct":["Azure Files"],
 "explanation":"Azure FilesはSMB/NFSでマウント可能なマネージドファイル共有で、オンプレミスのファイルサーバー置き換えにも使えます。"},
{"area":B,"sub":"ストレージ","type":"single",
 "q":"アクセス頻度が非常に低く長期保管向けで、保存単価が最も安いBlobのアクセス層はどれですか？",
 "options":["アーカイブ層","ホット層","クール層","プレミアム層"],"correct":["アーカイブ層"],
 "explanation":"アーカイブ層は保存単価が最も安い一方、取り出しに時間がかかります。頻繁にアクセスするならホット層が適します。"},
{"area":B,"sub":"ストレージ","type":"single",
 "q":"データを別リージョンにも複製し、リージョン障害に備える冗長オプションはどれですか？",
 "options":["geo冗長ストレージ（GRS/GZRS）","ローカル冗長ストレージ（LRS）","ゾーン冗長ストレージ（ZRS）","プレミアムSSD"],"correct":["geo冗長ストレージ（GRS/GZRS）"],
 "explanation":"GRS/GZRSは別リージョンにも複製しリージョン障害から保護します。LRSは単一データセンター内3重、ZRSはゾーン間複製で範囲が異なります。"},
{"area":B,"sub":"ストレージ","type":"single",
 "q":"頻繁にアクセスするデータに最適で、保存単価はやや高いBlobのアクセス層はどれですか？",
 "options":["ホット層","クール層","コールド層","アーカイブ層"],"correct":["ホット層"],
 "explanation":"ホット層はアクセス頻度の高いデータ向けで、保存コストは高めだがアクセスコストは低くなります。"},
{"area":B,"sub":"ストレージ","type":"single",
 "q":"単一データセンター内でデータを3重に複製する、最も安価な冗長オプションはどれですか？",
 "options":["ローカル冗長ストレージ（LRS）","geo冗長ストレージ（GRS）","読み取りアクセスgeo冗長（RA-GRS）","ゾーン冗長（ZRS）"],"correct":["ローカル冗長ストレージ（LRS）"],
 "explanation":"LRSは同一データセンター内で3コピーを保持する最も安価な方式ですが、データセンター全体やリージョンの障害には対応できません。"},
{"area":B,"sub":"ストレージ","type":"multi",
 "q":"Azure Storageが提供するサービスとして適切なものを2つ選んでください。",
 "options":["Blob Storage","Table Storage","Azure Cosmos DB","Azure SQL Database"],"correct":["Blob Storage","Table Storage"],
 "explanation":"Storageアカウントが提供するのはBlob・File・Queue・Tableです。Cosmos DBやSQL DatabaseはマネージドDBサービスで別物です。"},
{"area":B,"sub":"ストレージ","type":"single",
 "q":"オンプレミスからAzureへ大量のファイルを高速にコピーするコマンドラインツールはどれですか？",
 "options":["AzCopy","Azure Advisor","Azure Monitor","Azure Policy"],"correct":["AzCopy"],
 "explanation":"AzCopyはBlobやFilesへ大量データを効率的にコピーするCLIです。GUIで操作したい場合はAzure Storage Explorerを使います。"},
{"area":B,"sub":"ストレージ","type":"single",
 "q":"オンプレミス環境のAzureへの移行を評価・実行するためのサービスはどれですか？",
 "options":["Azure Migrate","Azure Monitor","Azure Advisor","Azure Arc"],"correct":["Azure Migrate"],
 "explanation":"Azure Migrateはサーバー・データベース・アプリの移行をアセスメントから実行まで支援するハブです。"},
{"area":B,"sub":"ストレージ","type":"single",
 "q":"回線では時間がかかりすぎる大量データを、物理アプライアンスに格納して郵送で移行するサービスはどれですか？",
 "options":["Azure Data Box","Azure File Sync","ExpressRoute","Azure Backup"],"correct":["Azure Data Box"],
 "explanation":"Azure Data Boxは大容量データを物理デバイスで輸送・アップロードするオフライン移行サービスです。"},

# ---- ID・アクセス・セキュリティ (10) ----
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"クラウドベースのID・アクセス管理サービス（旧Azure AD）はどれですか？",
 "options":["Microsoft Entra ID","Azure Policy","Azure Monitor","Microsoft Defender for Cloud"],"correct":["Microsoft Entra ID"],
 "explanation":"Microsoft Entra ID（旧Azure AD）は認証・SSO・MFAなどを提供するクラウドのID管理サービスです。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"「あなたは誰か」を確認するプロセスを何と呼びますか？",
 "options":["認証（Authentication）","承認（Authorization）","監査（Auditing）","暗号化（Encryption）"],"correct":["認証（Authentication）"],
 "explanation":"認証は本人確認、承認は確認後に何を行えるかを判断するプロセスです。両者は区別されます。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"パスワードに加え、スマホ承認やコードなど複数要素で本人確認する仕組みはどれですか？",
 "options":["多要素認証（MFA）","シングルサインオン（SSO）","条件付きアクセス","RBAC"],"correct":["多要素認証（MFA）"],
 "explanation":"MFAは『知っているもの・持っているもの・自分自身』のうち複数で認証し、セキュリティを大幅に高めます。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"一度サインインすれば複数のアプリに再認証なしでアクセスできる仕組みはどれですか？",
 "options":["シングルサインオン（SSO）","多要素認証（MFA）","条件付きアクセス","リソースロック"],"correct":["シングルサインオン（SSO）"],
 "explanation":"SSOは一度の認証で複数アプリにアクセスできる仕組みで、利便性とID管理の効率を高めます。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"場所・デバイス・リスクなどの条件に基づいてアクセス可否やMFA要求を制御するEntraの機能はどれですか？",
 "options":["条件付きアクセス","RBAC","リソースロック","Azure Policy"],"correct":["条件付きアクセス"],
 "explanation":"条件付きアクセスは、ユーザー・場所・デバイス・リスクなどのシグナルに応じてブロックやMFA要求を行うEntraの機能です。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"ユーザーやグループに『誰が・何に・何をできるか』を最小権限で割り当てる仕組みはどれですか？",
 "options":["ロールベースアクセス制御（RBAC）","条件付きアクセス","多要素認証","リソースロック"],"correct":["ロールベースアクセス制御（RBAC）"],
 "explanation":"RBACは組み込み/カスタムロールで最小権限を割り当てます。条件付きアクセスはアクセス条件、ロックは誤操作防止で目的が異なります。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"「決して信頼せず常に検証する」を原則とするセキュリティモデルはどれですか？",
 "options":["ゼロトラスト","多層防御","責任共有モデル","最小権限の原則のみ"],"correct":["ゼロトラスト"],
 "explanation":"ゼロトラストは『Never trust, always verify』を原則とし、ネットワーク内外を問わずアクセスごとに明示的な検証を求めます。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"複数の防御層を重ねて段階的に保護する考え方を何と呼びますか？",
 "options":["多層防御（Defense in Depth）","ゼロトラスト","フェールオーバー","責任共有モデル"],"correct":["多層防御（Defense in Depth）"],
 "explanation":"多層防御は物理・ID・境界・ネットワーク・コンピューティング・アプリ・データの各層で保護を重ね、1つが突破されても他で食い止めます。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"クラウドリソースのセキュリティ態勢（セキュアスコア）を評価し、脅威保護を強化するサービスはどれですか？",
 "options":["Microsoft Defender for Cloud","Microsoft Sentinel","Azure Monitor","Azure Advisor"],"correct":["Microsoft Defender for Cloud"],
 "explanation":"Defender for Cloudはセキュアスコアによる態勢評価とワークロード保護（CWPP）を提供します。SentinelはSIEM/SOARで役割が異なります。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"single",
 "q":"パスワードを使わず、Windows HelloやFIDO2キー、認証アプリで本人確認する方式を何と呼びますか？",
 "options":["パスワードレス認証","ベーシック認証","共有キー認証","匿名認証"],"correct":["パスワードレス認証"],
 "explanation":"パスワードレス認証はWindows Hello・FIDO2・Microsoft Authenticatorなどを使い、パスワードに依存せず安全に認証します。"},
# ---- 追加：複数選択（実測20%へ校正・実在サービスで消去法対策） ----
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"multi",
 "q":"可用性ゾーンを利用できるAzureリソースを2つ選んでください。",
 "options":["仮想マシン","Azure SQL Database","サブスクリプション","リソースグループ"],"correct":["仮想マシン","Azure SQL Database"],
 "explanation":"可用性ゾーンはVMやAzure SQL Databaseなどのゾーン対応リソースで利用します。サブスクリプションやリソースグループは論理的な管理単位で、ゾーンの概念を持ちません。"},
{"area":B,"sub":"コアアーキテクチャコンポーネント","type":"multi",
 "q":"Azureサブスクリプション内に作成されるものを2つ選んでください。",
 "options":["リソースグループ","リソース","管理グループ","Microsoft Entra のユーザーアカウント"],"correct":["リソースグループ","リソース"],
 "explanation":"サブスクリプションにはリソースグループとリソースが作成されます。管理グループはサブスクリプションを束ねる上位、Microsoft Entraのユーザーはテナント（ディレクトリ）レベルの存在です。"},
{"area":B,"sub":"ストレージ","type":"multi",
 "q":"Azure Blob ストレージの一般的なユースケースを2つ選んでください（各正解は完全な解決策）。",
 "options":["画像やドキュメントをブラウザに直接配信する","バックアップと復元のためのデータを保存する","複数の仮想マシンで仮想ドライブとして共有マウントする","WebサイトのASPXファイルをホスティングする"],"correct":["画像やドキュメントをブラウザに直接配信する","バックアップと復元のためのデータを保存する"],
 "explanation":"Blobは非構造化データの配信やバックアップに適します。共有ドライブのマウントはAzure Files、ASPXのホスティングはApp Serviceの役割です。"},
{"area":B,"sub":"ID・アクセス・セキュリティ","type":"multi",
 "q":"Microsoft Entra が提供するサービスを2つ選んでください。",
 "options":["認証","シングルサインオン（SSO）","データ暗号化","名前解決（DNS）"],"correct":["認証","シングルサインオン（SSO）"],
 "explanation":"Microsoft Entra IDは認証とSSO（およびMFAや条件付きアクセス）を提供します。データ暗号化や名前解決はEntraの役割ではありません。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"multi",
 "q":"オンプレミスのネットワークとAzure仮想ネットワークを接続する方法を2つ選んでください。",
 "options":["VPN Gateway（サイト間VPN）","ExpressRoute","可用性セット","ネットワークセキュリティグループ（NSG）"],"correct":["VPN Gateway（サイト間VPN）","ExpressRoute"],
 "explanation":"オンプレミス接続はVPN Gateway（暗号化トンネル）またはExpressRoute（専用回線）を使います。可用性セットは耐障害性、NSGはトラフィックのフィルタリングで接続手段ではありません。"},
{"area":B,"sub":"ストレージ","type":"multi",
 "q":"Azure Storage の冗長（レプリケーション）オプションを2つ選んでください。",
 "options":["ローカル冗長ストレージ（LRS）","geoゾーン冗長ストレージ（GZRS）","可用性セット","リソースロック"],"correct":["ローカル冗長ストレージ（LRS）","geoゾーン冗長ストレージ（GZRS）"],
 "explanation":"LRSやGZRSはストレージの冗長オプションです。可用性セットはVMの耐障害性、リソースロックは誤削除防止で、ストレージ冗長の選択肢ではありません。"},
{"area":B,"sub":"コンピューティングとネットワーク","type":"multi",
 "q":"Azureの『コンピューティング』の種類として正しいものを2つ選んでください。",
 "options":["仮想マシン","コンテナー","ネットワークセキュリティグループ（NSG）","リソースグループ"],"correct":["仮想マシン","コンテナー"],
 "explanation":"コンピューティングにはVM・コンテナー・関数（Functions）が含まれます。NSGはネットワーク、リソースグループは管理単位で、コンピューティングの種類ではありません。"},
]
