# -*- coding: utf-8 -*-
# Azureの管理とガバナンス (40問) — 本番難度版
C = "Azureの管理とガバナンス"
QC = [
# ---- コスト管理 (10) ----
{"area":C,"sub":"コスト管理","type":"single",
 "q":"オンプレミス運用とAzure移行後の総保有コストを比較見積もりするツールはどれですか？",
 "options":["TCO（総保有コスト）計算ツール","料金計算ツール","Microsoft Cost Management","Azure Advisor"],"correct":["TCO（総保有コスト）計算ツール"],
 "explanation":"TCO計算ツールはオンプレミスとAzureのコストを比較し削減効果を見積もります。実績分析はCost Management、見積もりは料金計算ツールです。"},
{"area":C,"sub":"コスト管理","type":"single",
 "q":"利用予定のサービスを構成して、月額などの見積もり金額を事前に算出するツールはどれですか？",
 "options":["料金計算ツール（Pricing Calculator）","TCO計算ツール","Microsoft Cost Management","Azure Service Health"],"correct":["料金計算ツール（Pricing Calculator）"],
 "explanation":"料金計算ツールは利用予定サービスを選んで見積もりを作成します。実績コストの分析はCost Managementが担当します。"},
{"area":C,"sub":"コスト管理","type":"single",
 "q":"実際の利用コストを可視化・分析し、予算超過のアラートを設定できる機能はどれですか？",
 "options":["Microsoft Cost Management","料金計算ツール","TCO計算ツール","Azure Advisor"],"correct":["Microsoft Cost Management"],
 "explanation":"Cost Management（+ Billing）は実支出の可視化・分析・予算設定・アラートを行います。見積もりは料金計算ツールです。"},
{"area":C,"sub":"コスト管理","type":"single",
 "q":"リソースに付与してコストの分類・集計に使える「キー:値」のメタデータを何と呼びますか？",
 "options":["タグ","リソースロック","ポリシー","ロール"],"correct":["タグ"],
 "explanation":"タグはリソースに付ける『キー:値』のメタデータで、部署や環境ごとのコスト集計・整理に役立ちます。"},
{"area":C,"sub":"コスト管理","type":"multi",
 "q":"Azureのコストに影響を与える要因として適切なものを2つ選んでください。",
 "options":["リソースの種類とサイズ","データの送信（egress）量とリージョン","リソースに付けたタグの個数","リソースグループの名前の長さ"],"correct":["リソースの種類とサイズ","データの送信（egress）量とリージョン"],
 "explanation":"コストはリソース種類・サイズ・稼働時間、配置リージョン、egress量、課金モデルなどに左右されます。タグ数や名前の長さは課金要因ではありません。"},
{"area":C,"sub":"コスト管理","type":"single",
 "q":"同じリソースでも配置するリージョンによって料金が異なることがある理由はどれですか？",
 "options":["リージョンごとに運用コストや需給が異なるため","リージョン名の文字数で決まるため","常に全リージョン同額のため","タグの数で決まるため"],"correct":["リージョンごとに運用コストや需給が異なるため"],
 "explanation":"電力・土地・需給などの違いからリージョンごとに価格差が生じます。コスト最適化ではリージョン選択も考慮します。"},
{"area":C,"sub":"コスト管理","type":"single",
 "q":"24時間安定稼働する本番VMのコストを、従量課金より抑える方法として最も適切なものはどれですか？",
 "options":["1年/3年の予約（Reserved Instances）","スポットVMに切り替える","毎日VMを作り直す","タグを増やす"],"correct":["1年/3年の予約（Reserved Instances）"],
 "explanation":"安定稼働するリソースは予約で割引されます。スポットは中断され得るため、停止できない本番には不向きです。"},
{"area":C,"sub":"コスト管理","type":"single",
 "q":"Azureのデータ転送課金について一般的に正しいものはどれですか？",
 "options":["多くの場合、外部への送信（egress）に課金され、受信（ingress）は無料","受信に課金され送信は無料","送受信とも常に無料","送受信とも一律同額"],"correct":["多くの場合、外部への送信（egress）に課金され、受信（ingress）は無料"],
 "explanation":"一般にAzureへのingressは無料で、Azureから外部へ出るegressに課金されます。設計時に転送量を意識するとコストを抑えられます。"},
{"area":C,"sub":"コスト管理","type":"single",
 "q":"部署ごとにAzureコストをCost Managementで分類・集計したい。最も有効な手段はどれですか？",
 "options":["リソースに部署名のタグを付ける","リソースを1つの名前に統一する","リージョンを統一する","リソースを削除する"],"correct":["リソースに部署名のタグを付ける"],
 "explanation":"タグを付与するとCost Managementでタグ別にコストをフィルタ・集計でき、部署やプロジェクト単位の費用配賦が容易になります。"},
{"area":C,"sub":"コスト管理","type":"single",
 "q":"開発環境のVMを夜間・週末に自動停止する運用の効果として正しいものはどれですか？",
 "options":["稼働時間が減りコンピューティング課金を削減できる","ストレージが自動削除される","SLAが自動的に向上する","タグが自動付与される"],"correct":["稼働時間が減りコンピューティング課金を削減できる"],
 "explanation":"VMのコンピューティング課金は稼働時間に比例するため、不要時間帯の停止で費用を抑えられます（停止後もディスクの保存課金は続きます）。"},

# ---- ガバナンスとコンプライアンス (10) ----
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"リソースの作成や構成を組織ルールに従わせ、準拠状況を監査・強制する機能はどれですか？",
 "options":["Azure Policy","リソースロック","RBAC","Azure Advisor"],"correct":["Azure Policy"],
 "explanation":"Azure Policyは許可リージョンやSKU、必須タグなどのルールを定義し、準拠状況の監査や非準拠リソースの作成拒否を行います。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"重要なリソースの誤削除・誤変更を防ぐために設定する仕組みはどれですか？",
 "options":["リソースロック（CanNotDelete / ReadOnly）","タグ","Azure Policy","条件付きアクセス"],"correct":["リソースロック（CanNotDelete / ReadOnly）"],
 "explanation":"リソースロックは『削除禁止』や『読み取り専用』を設定し、操作権限の有無に関わらず誤操作を防ぎます。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"ISOやSOCなどMicrosoftの監査レポートやコンプライアンス文書を入手できるポータルはどれですか？",
 "options":["Service Trust Portal","Azure Portal","Microsoft Purview","Azure Advisor"],"correct":["Service Trust Portal"],
 "explanation":"Service Trust PortalではISOやSOCなどの監査レポートやコンプライアンス関連ドキュメントを入手できます。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"組織のデータを検出・分類・カタログ化し、データガバナンスを支援するサービスはどれですか？",
 "options":["Microsoft Purview","Azure Policy","Azure Monitor","Microsoft Defender for Cloud"],"correct":["Microsoft Purview"],
 "explanation":"Microsoft Purviewはデータの検出・分類・カタログ化・統制を行う統合データガバナンスサービスです。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"複数のAzure Policyをまとめて一括で割り当て・管理する仕組みを何と呼びますか？",
 "options":["イニシアティブ（ポリシーセット）","管理グループ","リソースロック","タグ"],"correct":["イニシアティブ（ポリシーセット）"],
 "explanation":"イニシアティブは複数のポリシー定義をまとめた単位で、関連規則をまとめて適用・評価できます。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"リソースロックの『CanNotDelete』と『ReadOnly』の違いとして正しいものはどれですか？",
 "options":["CanNotDeleteは削除のみ禁止、ReadOnlyは変更も削除も禁止","両者は同じ","ReadOnlyは削除のみ禁止","CanNotDeleteは読み取りも禁止"],"correct":["CanNotDeleteは削除のみ禁止、ReadOnlyは変更も削除も禁止"],
 "explanation":"CanNotDeleteは削除を防ぎ変更は可能、ReadOnlyは読み取りのみ許可し変更も削除も禁止します。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"「特定リージョンにしかリソースを作成できないようにする」統制を実現するのに最適なものはどれですか？",
 "options":["Azure Policy","タグ","RBAC","Azure Monitor"],"correct":["Azure Policy"],
 "explanation":"Azure Policyで許可リージョンを制限すると、対象外リージョンでのリソース作成を拒否できます。RBACは人の権限制御で目的が異なります。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"すべての新規リソースに必須タグ（例: CostCenter）を強制したい。最適な手段はどれですか？",
 "options":["Azure Policyでタグの付与を要求/強制する","RBACで権限を外す","リソースロックをかける","Azure Advisorを実行する"],"correct":["Azure Policyでタグの付与を要求/強制する"],
 "explanation":"Azure Policyには必須タグの要求や既定値付与の組み込みポリシーがあり、ガバナンスを自動的に強制できます。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"Azure PolicyとRBACの役割の違いとして正しいものはどれですか？",
 "options":["Policyはリソースの構成ルールを統制し、RBACは人/IDの操作権限を制御する","どちらも同じ機能","RBACがリソースの構成を統制する","Policyがユーザーのログインを制御する"],"correct":["Policyはリソースの構成ルールを統制し、RBACは人/IDの操作権限を制御する"],
 "explanation":"Policyは『リソースがどう構成されるべきか』、RBACは『誰が何をできるか』を制御し、両者は補完関係にあります。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"single",
 "q":"セキュリティとガバナンスをクラウドで一元化することの利点として最も適切なものはどれですか？",
 "options":["ポリシーやテンプレートで全社に統一基準を一貫適用しやすい","物理的な鍵管理が増える","コスト把握ができなくなる","監査が不可能になる"],"correct":["ポリシーやテンプレートで全社に統一基準を一貫適用しやすい"],
 "explanation":"Policyやテンプレート、RBACにより統一基準を組織全体に一貫適用・監査しやすくなります。"},

# ---- リソースの管理とデプロイ (10) ----
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"すべてのAzureリソースの作成・更新・削除を担う、デプロイと管理の統合レイヤーはどれですか？",
 "options":["Azure Resource Manager（ARM）","Azure Monitor","Azure Advisor","Azure Policy"],"correct":["Azure Resource Manager（ARM）"],
 "explanation":"ARMはポータル・CLI・PowerShell・テンプレートからの要求を受け付け、リソースの展開と管理を一元的に処理します。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"オンプレミスや他クラウドのサーバー・KubernetesをAzureの管理面から一元管理できるサービスはどれですか？",
 "options":["Azure Arc","Azure Migrate","Azure Bastion","Azure Lighthouse"],"correct":["Azure Arc"],
 "explanation":"Azure ArcはオンプレミスやマルチクラウドのリソースをAzureの管理基盤に取り込み、ポリシーや監視を一貫適用できます。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"ブラウザからCLIやPowerShellを使え、認証済みでツール準備が不要な対話環境はどれですか？",
 "options":["Azure Cloud Shell","Azure Portal","Azure Mobile App","ARMテンプレート"],"correct":["Azure Cloud Shell"],
 "explanation":"Cloud Shellはブラウザ上の対話型シェルで、Azure CLIとPowerShellをインストール不要・認証済みで利用できます。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"インフラをコード（JSON）で宣言的に定義し、繰り返し同じ環境を展開できるものはどれですか？",
 "options":["ARMテンプレート","Azure Portal","Cloud Shell","Azure Advisor"],"correct":["ARMテンプレート"],
 "explanation":"ARMテンプレート（およびBicep）はリソース構成をコードで宣言的に定義し、再現性のある自動デプロイ（IaC）を実現します。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"GUIでAzureリソースをブラウザから視覚的に管理できる統合管理コンソールはどれですか？",
 "options":["Azure Portal","Azure CLI","ARMテンプレート","Azure Monitor"],"correct":["Azure Portal"],
 "explanation":"Azure Portalはブラウザからリソースを作成・構成・監視できるGUIの統合管理コンソールです。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"クロスプラットフォームで動作し、azコマンドでAzureを操作するコマンドラインツールはどれですか？",
 "options":["Azure CLI","Azure Portal","ARMテンプレート","Azure Advisor"],"correct":["Azure CLI"],
 "explanation":"Azure CLIは『az』で始まるコマンドでAzureを操作できるクロスプラットフォームのCLIで、自動化に適します。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"コマンドレット（Verb-Noun形式）でAzureを操作・自動化するスクリプト環境はどれですか？",
 "options":["Azure PowerShell","Azure Portal","Azure Monitor","Service Health"],"correct":["Azure PowerShell"],
 "explanation":"Azure PowerShellはコマンドレットでAzureを管理・自動化するモジュールで、Cloud Shellからも利用できます。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"インフラ構成をコードで管理し、手作業を排して再現性をもって環境を構築する考え方を何と呼びますか？",
 "options":["Infrastructure as Code（IaC）","Software as a Service","Platform as a Service","Defense in Depth"],"correct":["Infrastructure as Code（IaC）"],
 "explanation":"IaCはインフラ構成をコードで管理し、自動・反復可能・バージョン管理可能なデプロイを実現する手法です。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"ARMテンプレート（JSON）より簡潔な構文でIaCを記述できる、Azure専用のドメイン固有言語はどれですか？",
 "options":["Bicep","Terraform HCL","PowerShell DSC","Ansible Playbook"],"correct":["Bicep"],
 "explanation":"BicepはARMテンプレートを簡潔に書けるAzure専用のIaC言語で、デプロイ時にARMへ変換されます。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"single",
 "q":"オンプレミスのサーバーにAzure Policyや監視を適用したい。使うべきサービスはどれですか？",
 "options":["Azure Arc","Azure Cloud Shell","Azure Migrate","Azure Bastion"],"correct":["Azure Arc"],
 "explanation":"Azure ArcはAzure外のマシンやKubernetesをAzureに接続し、ポリシーや監視などの管理機能を一貫適用できます。Migrateは移行用です。"},

# ---- 監視ツール (10) ----
{"area":C,"sub":"監視ツール","type":"single",
 "q":"コスト・セキュリティ・信頼性・パフォーマンスなどの観点で改善を推奨してくれる無料サービスはどれですか？",
 "options":["Azure Advisor","Azure Monitor","Azure Policy","Microsoft Sentinel"],"correct":["Azure Advisor"],
 "explanation":"Azure Advisorは利用状況を分析し、コスト最適化・セキュリティ・信頼性・パフォーマンス・優れた運用の観点で推奨事項を提示します。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"アプリやインフラのメトリック・ログを収集して可視化・アラートする中核サービスはどれですか？",
 "options":["Azure Monitor","Azure Advisor","Azure Service Health","Microsoft Purview"],"correct":["Azure Monitor"],
 "explanation":"Azure Monitorはメトリックやログを収集して可視化・アラート・自動対応を行う監視の中核です。ログのクエリにはLog Analyticsを使います。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"利用中のAzureサービス自体の障害・計画メンテナンス情報を通知するサービスはどれですか？",
 "options":["Azure Service Health","Azure Advisor","Azure Monitor","Azure Policy"],"correct":["Azure Service Health"],
 "explanation":"Azure Service Healthは利用中サービスの障害・計画メンテナンス・正常性勧告など、Azure側の状況をパーソナライズして通知します。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"ログを集約して脅威を検知・対応するクラウドネイティブなSIEM/SOARはどれですか？",
 "options":["Microsoft Sentinel","Microsoft Defender for Cloud","Azure Monitor","Azure Advisor"],"correct":["Microsoft Sentinel"],
 "explanation":"Sentinelは全社のログを集約し相関分析・脅威検知・自動対応を行うSIEM/SOARです。Defender for Cloudは態勢評価/ワークロード保護が中心です。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"Azure Monitorが収集したログを保存し、KQLでクエリ・分析する基盤はどれですか？",
 "options":["Log Analytics","Application Insights","Azure Advisor","Blob Storage"],"correct":["Log Analytics"],
 "explanation":"Log AnalyticsはAzure Monitorのログデータを保存・クエリする基盤で、Kusto照会言語（KQL）で柔軟に分析できます。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"Webアプリの応答時間・例外・利用状況を監視するApplication Performance Monitoring機能はどれですか？",
 "options":["Application Insights","Azure Advisor","Azure Service Health","Azure Policy"],"correct":["Application Insights"],
 "explanation":"Application InsightsはAzure Monitorの一機能で、アプリのパフォーマンス・可用性・利用状況を可視化します。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"メトリックやログがしきい値を超えたときに通知や自動対応を起動するAzure Monitorの機能はどれですか？",
 "options":["アラート（Azure Monitor Alerts）","Log Analytics のクエリ","タグ","リソースロック"],"correct":["アラート（Azure Monitor Alerts）"],
 "explanation":"アラートはしきい値や条件に基づき通知やアクション（自動スケール、Runbook実行など）を起動します。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"Azure Advisorが推奨を提供しないカテゴリはどれですか？",
 "options":["UIの配色デザイン","コストの最適化","セキュリティ","信頼性"],"correct":["UIの配色デザイン"],
 "explanation":"Advisorはコスト・セキュリティ・信頼性・パフォーマンス・オペレーショナルエクセレンスの5観点で推奨します。UIの配色は対象外です。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"「Azure全体の障害」ではなく「自分の特定リソースの正常性」を確認したいときに見るべきものはどれですか？",
 "options":["Resource Health（リソース正常性）","Service Health","料金計算ツール","Azure Policy"],"correct":["Resource Health（リソース正常性）"],
 "explanation":"Resource Healthは個々のリソースの稼働状態を示します。サービス全体やリージョンの障害情報はService Healthで確認します。"},
{"area":C,"sub":"監視ツール","type":"single",
 "q":"Azure Monitorが扱う主なデータの種類として正しい組み合わせはどれですか？",
 "options":["メトリック（数値の時系列）とログ（イベント等の記録）","タグとリソースロック","RBACロールとポリシー","サブスクリプションと管理グループ"],"correct":["メトリック（数値の時系列）とログ（イベント等の記録）"],
 "explanation":"Azure Monitorは主にメトリック（数値の時系列）とログ（イベント・トレース等の記録）を収集・分析します。"},
# ---- 追加：複数選択（実測20%へ校正・実在サービスで消去法対策） ----
{"area":C,"sub":"コスト管理","type":"multi",
 "q":"リソースタグの一般的な利用シナリオを2つ選んでください（各正解は完全な解決策）。",
 "options":["さまざまな環境（開発/本番など）とコストを関連付ける","部門別にコストを分類する","低コストのリージョンを特定する","利用率の低い仮想マシンのサイズを変更する"],"correct":["さまざまな環境（開発/本番など）とコストを関連付ける","部門別にコストを分類する"],
 "explanation":"タグはメタデータで、環境別・部門別のコスト整理に使います。低コストリージョンの特定や仮想マシンのサイズ変更はタグの役割ではありません（前者は料金計算/Advisor、後者はAdvisorの推奨）。"},
{"area":C,"sub":"コスト管理","type":"multi",
 "q":"Azure Cost Management + Billing で利用できる機能を2つ選んでください。",
 "options":["予算の作成と管理","履歴レポートの生成と将来使用量の予測","リソースをデプロイする前のTCO（総保有コスト）見積もり","前払いによる割引価格の提供"],"correct":["予算の作成と管理","履歴レポートの生成と将来使用量の予測"],
 "explanation":"Cost Managementは予算管理とレポート/予測を提供します。デプロイ前の見積もりは料金計算ツール/TCO計算ツール、前払い割引はリザーブドインスタンス（予約）の機能です。"},
{"area":C,"sub":"監視ツール","type":"multi",
 "q":"Azure Monitor に含まれる機能を2つ選んでください。",
 "options":["Log Analytics","Application Insights","Azure Policy","リソースロック"],"correct":["Log Analytics","Application Insights"],
 "explanation":"Azure MonitorはLog Analyticsやアラート、Application Insightsを含みます。Azure Policyはガバナンス、リソースロックは誤削除防止で、監視の機能ではありません。"},
{"area":C,"sub":"ガバナンスとコンプライアンス","type":"multi",
 "q":"Azureのガバナンス/リソース保護を高める仕組みを2つ選んでください。",
 "options":["Azure Policy","リソースロック","ダッシュボードのピン留め","タグの並べ替え"],"correct":["Azure Policy","リソースロック"],
 "explanation":"Azure Policy（標準の強制）とリソースロック（誤削除/変更の防止）はガバナンスの中核です。ダッシュボードのピン留めやタグの並べ替えはUI操作で統制とは無関係です。"},
{"area":C,"sub":"リソースの管理とデプロイ","type":"multi",
 "q":"Infrastructure as Code（IaC）でAzureリソースを宣言的に定義・デプロイできるものを2つ選んでください。",
 "options":["ARMテンプレート（JSON）","Bicep","Azure Service Health","リソースロック"],"correct":["ARMテンプレート（JSON）","Bicep"],
 "explanation":"ARMテンプレートとBicepは宣言的にリソースを定義するIaCです。Service Healthはサービス正常性の通知、リソースロックは削除防止で、IaCの手段ではありません。"},
]
